### ISSUE TITLE
Implement nickname > real name translation

### ISSUE THREAD

**Issue by moritzheiber** [wee-slack/wee-slack#100]
wee-slack right now uses the regular nicknames assigned to each entity within Slack. However, most of my colleagues are using obscure handles I don't necessarily associate them with. It would be amazing to have wee-slack "translate" these nicknames into whatever first and last name people have entered on the website.

Thanks!

**Comment by tfheen** [comment]
I started on this, and it's fairly easy to do, apart from you running into unicode comparison weirdness in a bunch of places, and it feels super odd, so it certainly has to be behind a setting.

**Comment by rawdigits** [comment]
+1 on making it an option and not the default. I have tried this in the normal client and don't recognize anyone by their full name. :)

**Comment by LovesTha** [comment]
Would be nice for this to be a per slack server setting. As the slacks I'm in that have a professional bend are very much about real names, the more social/hobby oriented ones are alias based.

**Comment by LovesTha** [comment]
Any chance your attempt to make this change was in a branch that could be shared. This is a language I'm not particularly familiar with so attempting my own patch could do with a kickstart.

**Comment by trygveaa** [comment]
@LovesTha: I added a global option now, but I agree that having this as a per server setting would be nice. I opened issue #710 for that.
