### ISSUE TITLE
Send multiline messages

### ISSUE THREAD

**Issue by keith** [wee-slack/wee-slack#118]
It would be awesome if there was a way to send multiline messages. According to the [slack API](https://api.slack.com/docs/formatting) this should be possibly by sending `\n` in the `text`, but it seems like before sending the message these get escaped to `\\n`. Any suggestions on how to make this work?

**Comment by Hywan** [comment]
:+1:

**Comment by rawdigits** [comment]
Does weechat support multiline messages? We could add some kind of special escape, but that seems kludge-y.

**Comment by keith** [comment]
It doesn't really seem like weechat does. Maybe that's because of limitations in other services, I'm not sure. I wrote [a thing](https://github.com/keith/edit-weechat) to allow you to draft messages in vim which is super useful for sending code blocks and such. But right now it sends a different message for each line.

**Comment by rawdigits** [comment]
oh, i like your plugin! I'll think on how to make this work.

**Comment by tfheen** [comment]
]] Ryan Huber 

> Does weechat support multiline messages? We could add some kind of
> special escape, but that seems kludge-y.

I suspect glowing-bear too might allow multiline messages (or the devs
can be convinced to support it if we can make the pipeline work).
@torhve, can you comment?

-- 
Tollef Fog Heen
UNIX is user friendly, it's just picky about who its friends are

**Comment by torhve** [comment]
In my matrix protocol script I just have a very small timer that checks for multiple lines being sent in a quick session. This works fine for things like pastes and the typical candidates for multiline. It also works without any additional modification in glowing bear.

Relevant bits in my protocol implementation, which can easily be adapted to wee-slack I reckon:
https://github.com/torhve/weechat-matrix-protocol-script/blob/master/matrix.lua#L1065-L1093

**Comment by JohnMaguire** [comment]
:+1:

**Comment by dhruvasagar** [comment]
:+1: Has someone played with https://weechat.org/scripts/source/multiline.pl.html/ or any other plugin for weechat for doing this ?

**Comment by dhruvasagar** [comment]
Ok I gave it a try, it's slightly awkward to use at first, but seems usable.

**Comment by leifmadsen** [comment]
+1 I was just looking for this feature as well, primarily for posting in code blocks

**Comment by Grogglex** [comment]
Has anyone got a code block to send as a single message rather than a separate message for each line?

**Comment by dhruvasagar** [comment]
For now I think the best option is to use something like gist.github.com

**Comment by Grogglex** [comment]
I've found the best solution to be: https://wiki.gentoo.org/wiki/Wgetpaste .

**Comment by jeffrom** [comment]
http://slackcat.chat/ could be part of a good solution

**Comment by oblitum** [comment]
@Grogglex

> I've found the best solution to be: https://wiki.gentoo.org/wiki/Wgetpaste .
Basically I have it set up to grab the contents of my clipboard, paste it to the service and then set my clipboard contents to the URL of the paste. There might be a way to leverage this library to emulate something like Slack's native snippets.

That solution is not very nice since Slack users are used to their native code snippets, which is displayed inside the client window and not related to any external service or tooling, besides on wee-slack the Slack snippets are visible when someone on Slack writes one, sadly we can't write them.

**Comment by oblitum** [comment]
> Has someone played with https://weechat.org/scripts/source/multiline.pl.html/ or any other plugin for weechat for doing this ?

> Ok I gave it a try, it's slightly awkward to use at first, but seems usable.

This plugin just allows editing in multiple lines but sends each line in a row, not as a single multi line message.

**Comment by trygveaa** [comment]
This is now supported, and you should be able to use the [`multiline.pl`](https://weechat.org/scripts/source/multiline.pl.html/) or [`edit.py`](https://github.com/keith/edit-weechat) plugin to send multiple lines, which will appear as one message in Slack.

**Comment by gianarb** [comment]
Hello @trygveaa I tried the multiline.pl . It seems good to write multiline messages but it doesn't work great when I copy/paste output from my terminal. do you have some feedback to cover that use case? Thanks

**Comment by trygveaa** [comment]
@gianarb: When you paste with multiline.pl enabled, it should detect it, so the lines are sent as one message instead of multiple. Copying isn't affected by multiline.pl. What's your problem with copy and paste?

For the record, I have set `perl.multiline.magic_paste_only = "on"` and bound `/input insert \x0a` to `meta-ctrl-M`, so I can send one-line messages normally, while still sending multi-line messages as one message either by pasting or by pressing alt-enter to input a newline.

**Comment by gianarb** [comment]
Hello @trygveaa probably is just something that I am doing wrong because I started using weechat from a couple of days. So I will try with your tips and I will let you know! thanks

**Comment by trygveaa** [comment]
@neverfox: Squashed into one line in the input field, or in the message after you send it? If you want the input field to expand to multiple lines, you have to set `weechat.bar.input.size` to `0`.

**Comment by neverfox** [comment]
Thanks. As to the recommendation to bind the key, I see where it talks about that in the docs but it says that's for sending a multiline message when finished. Can you help me understand how that lets you `send one-line messages normally, while still sending multi-line messages as one message either by pasting or by pressing alt-enter to input a newline`? I don't get the reference to alt-enter here. Would you mind terribly showing me the steps for entering multiline this way with paste_only on?

**Comment by neverfox** [comment]
@trygveaa Hmm, weechat.bar.input.size is set to 0, and yes I mean squashed into one line in the input field.

**Comment by trygveaa** [comment]
@neverfox: You should just need to set the options I wrote above, i.e. run this:

```
/set plugins.var.perl.multiline.magic_paste_only on
/key bind meta-ctrl-M /input insert \x0a
```

`meta-ctrl-M` is the same as alt-enter.

Seems like you also need to have enter bound to magic_enter. multiline.pl should do that for you, but if you don't have that binding, that might be the reason paste is not working for you. You can set it with:

```
/key bind ctrl-M /input magic_enter
```

**Comment by moorchegue** [comment]
@odknt should this work out of the box or is some configuration required? I tried using current master and copy-pasted multiline messages are still being sent one per line.

**Comment by trygveaa** [comment]
@moorchegue: You need another script to compose multiline messages, as weechat can't do that by default (even if you paste them). You can for example use `multiline.pl`, which can be installed with `/script install multiline.pl`.

As for the commit. you are linking to a fork of this repo. The commit exists in this repo.

**Comment by trygveaa** [comment]
@neverfox: Regarding your issue with paste that you mentioned here. I see that it was a long time ago, so not sure if it's still useful for you, but I have started using kitty myself and encountered the same issue, so I recalled your comment.

I looked into it, and it seems that the terminals do something differently. I haven't really figured out what they do differently, but I managed to fix the issue by doing this:

```
/set plugins.var.perl.multiline.weechat_paste_fix "off"
/key bind ctrl-J /input insert \n
```

**Comment by cfal** [comment]
I'm using kitty but not using wee-slack or multiline.pl and found the same "squashing" problem. It turns out kitty supports bracketed paste mode by default and weechat also now has it enabled by default. Setting `weechat.look.paste_bracketed` to off fixed the problem for me.
