### ISSUE TITLE
Use login api call instead of api tokens

### ISSUE THREAD

**Issue by rawdigits** [wee-slack/wee-slack#135]
We currently use user-generated tokens for auth. Many teams don't allow their users to generate tokens, so we should support login via either OAUTH or the login endpoint.

**Comment by rawdigits** [comment]
use auth.signin

**Comment by scotte** [comment]
It would be nice if this was an option so both can be supported - for cases (like mine) where I can generate an API token, but not use OAUTH/login (which goes through a custom OAUTH implementation requiring a browser).

**Comment by rawdigits** [comment]
support username/password in the tokens var like so:

'xoxp-asdf9asd89f78asdf89asd7f,user:pass,xoxp-a9sdf78asd9fa7sdf89'

**Comment by oblitum** [comment]
Just had my token revoked in a public team (cpplang) I used to join. I'm not sure whether it's a general trend, now I had to request the token and wait for admin response. No idea whether it will ever come.

**Comment by oblitum** [comment]
It seems like oauth was merged once but then vanished from codebase?

- https://github.com/wee-slack/wee-slack/pull/245

**Comment by oblitum** [comment]
Hmm, I'm reading strong backslash against legacy tokens lately, may be the reason I've got my revoked and I think it's not even wise to ask for more:

- https://twitter.com/myetherwallet/status/900327327971897344
- https://altcointalk.io/topic/128/slack-user-info-accesibility

**Comment by kasperlewau** [comment]
I had a bunch of tokens revoked myself, and we've gone the mile of revoking all legacy tokens in our org for the very reasons specified by @oblitum 

The OAuth code appears to have been lost here https://github.com/wee-slack/wee-slack/commit/95fa084893660b655388604084f082a080f1ba32#diff-67e177ac444a14d6bcd7be6306ab4a20L1133 as part of the `wee-ng-merge` #334 

I haven't yet figured out which particular commit removed the code.

fwiw: I absolutely _love_ wee-slack and my heart sank when I had to go back to the CPU drain that is `ssb-interop`, courtesy of the native Slack client on my Arch box.

**Comment by selckin** [comment]
You can extract a token from the websocket traffic in your browser that will work for a while, until a better solution can be made

**Comment by matthijskooijman** [comment]
What's the status of this? When I run `/slack register`, I get offered an url like `https://slack.com/oauth/authorize?client_id=123.456&scope=client` which suggests that oauth is now supported.

The token returned and subsequently passed to `/slack register` does not look like a new-style token, but afterwards `plugins.var.python.slack.slack_api_token` contains a token starting with `xoxp-`, which is a new-style [user token](https://api.slack.com/docs/token-types).

So I think this issue is fixed?

**Comment by tfheen** [comment]
Closing this, the oauth flow gives us what we want.
