### ISSUE TITLE
Document all configuration values

### ISSUE THREAD

**Issue by adamgibbins** [wee-slack/wee-slack#154]
There's a bunch of undocumented configuration options:
plugins.var.python.slack_extension.colorize_private_chats
plugins.var.python.slack_extension.distracting_channels
plugins.var.python.slack_extension.trigger_value
plugins.var.python.slack_extension.unfurl_ignore_alt_text

for example.  It would be good to get these documented, so people aren't forced to read the code when they're not so obvious.  e.g. unclear to me why distracting_channels exists, when I could just /buffer notify highlight

**Comment by tfheen** [comment]
Fixed in 184e05c15e4179a1a24fa260506e7bc7b01b6245.
