### ISSUE TITLE
Allow filtering of slackbot

### ISSUE THREAD

**Issue by emonty** [wee-slack/wee-slack#179]
I'd like to do this:
/filter add slackbot \* nick_slackbot *
since slackbot is annoying. But since wee-slack isn't an IRC buffer from weechat's perspective, that doesn't work.

It would be super awesome if there was a wee-slack option to filter slackbot messages into /dev/null.

**Comment by trygveaa** [comment]
This is now possible using the command you wrote (well, it has been for a while, not sure exactly when it was fixed).
