### ISSUE TITLE
Feature request: tab completion of slack emoji

### ISSUE THREAD

**Issue by rawdigits** [wee-slack/wee-slack#181]
Hitting tab after a ":" or ":partialword" should cycle through emoji from the supported list.

**Comment by kattrali** [comment]
I started on this in weemoji but didn't have any success with [getting tab completion](https://github.com/kattrali/weemoji/blob/master/weemoji.py#L44-L47) working for some reason. It could use a second set of eyes if it makes sense there, or I wouldn't mind moving it to here.

**Comment by rawdigits** [comment]
:eyes:

**Comment by trygveaa** [comment]
It would be nice if this feature took the way you can add reactions into account as well, so it works when you start to type a reaction, not only when you type a standalone emoji.

Examples of typing a reaction:
```
+:smile:
2+:smile:
-:smile:
2-:smile
```

**Comment by torhve** [comment]
This script does emoji completition, but not all slack aliases are supported I suspect, but I guess could be added: https://weechat.org/files/scripts/pending/emoji.lua

**Comment by auscompgeek** [comment]
This has been mostly added in 1.0-RC1. One needs to symlink/copy weemoji.json into ~/.weechat, and append `|%(emoji)` to `weechat.completion.default_template`, I believe.

**Comment by SevereOverfl0w** [comment]
I can confirm that the above instructions worked for me.

**Comment by trygveaa** [comment]
Instructions for enabling this has now been added in the readme, so I'm closing this. My request for it to work for reactions still stands though, but I think that's more difficult to solve.

**Comment by wohali** [comment]
Just for others who may run into this - a `/python reload` was necessary for me after following instructions in the README to get weechat to pick up on the tab completions.

**Comment by skrat** [comment]
@trygveaa I think that `/python reload` line that @wohali suggested should go in the docs, to avoid confusion on why isn't it working when following the docs

**Comment by trygveaa** [comment]
@skrat: Done.
