### ISSUE TITLE
Help text for settings

### ISSUE THREAD

**Issue by torhve** [wee-slack/wee-slack#189]
The weechat api allows specifying help text for script settings, so users can tell how/why/when/what to use them.

Relevant example from another script:

https://github.com/torhve/weechat-matrix-protocol-script/blob/master/matrix.lua#L3092-L3113

**Comment by rawdigits** [comment]
definitely. we have avoided this a bit too long. :)

**Comment by tfheen** [comment]
This was fixed in 184e05c15e4179a1a24fa260506e7bc7b01b6245.
