### ISSUE TITLE
Multiple accounts

### ISSUE THREAD

**Issue by keith** [wee-slack/wee-slack#2]
Loving this plugin thanks! It would be awesome if it could support multiple slack accounts though. Seems like most plugins do that by nested the token setting under the server name ([example](https://github.com/thoughtbot/weechat-slacklog/blob/master/slacklog.rb#L23-L27)). I might have a chance to try and tackle this if this isn't something that interests you.

**Comment by ikwyl6** [comment]
Hi - I didn't see any on the main page, but are there instructions somewhere on how to use multiple accounts?

**Comment by trygveaa** [comment]
@ikwyl6: Instructions for adding multiple accounts is here: https://github.com/wee-slack/wee-slack#optional-connecting-to-multiple-teams

If you mean other usage than adding, it works the same as multiple irc servers.

**Comment by ikwyl6** [comment]
I saw that but assumed it was for multiple teams on the same account. Thanks
