### ISSUE TITLE
Automatic detachment inconsistencies with wee-slack and irc buffers

### ISSUE THREAD

**Issue by chuckharmston** [wee-slack/wee-slack#209]
A combination of `buffers.look.detach` and `buffers.look.immune_detach_buffers` can be used to detach all but a whitelist of buffers when they've been inactive for a period of time. wee-slack doesn't appear to work consistently in this way with IRC buffers, and I haven't quite put my finger on why (maybe due to the way buffers are renamed to indicate status?). What I've noticed:
- It appears to operate on a different timeout than `buffers.look.detach`.
- `buffers.look.immune_detach_buffers` doesn't seem to be used, regardless of how `slack_extension.server_alias` is used.

Any thoughts?

**Comment by rawdigits** [comment]
Hi @chuckharmston - I don't use that particular feature. Can you describe what it does and what the expected behavior would be? Also does this involve a plugin or only core weechat?

**Comment by chuckharmston** [comment]
Hi @rawdigits, it's part of `buffers.pl`. There are a few settings related to automatic detachment of buffers:

- `buffers.look.detach` - detach buffer from buffers list after a specific period of time (in seconds) without action (weechat ≥ 0.3.8 required) (`0` means "off")
- `immune_detach_buffers` - comma separated list of buffers to NOT automatically detach. Allows `*` wildcard. Ex: `"BitlBee,freenode.*"`
- `detach_buffer_immediately` - comma separated list of buffers to detach immediately. A query and highlight message will attach buffer again. Allows `*` wildcard. Ex: `"BitlBee,freenode.*"`

**Comment by trygveaa** [comment]
Since `buffers.pl` has been replaced with a plugin included in WeeChat, I don't think this issue is relevant anymore. Please comment or open a new issue if this is not the case.
