### ISSUE TITLE
Highlighting ignores word boundaries

### ISSUE THREAD

**Issue by ghost** [wee-slack/wee-slack#220]
Wee-slack highlights me when my nick (Na) is part of another word (eg binary, native, finally).

As far as I can tell, the code responsible for this is in Channel.buffer_prnt on [line 622](https://github.com/rawdigits/wee-slack/blob/master/wee_slack.py#L622)

``` python
elif message.find(self.server.nick.encode('utf-8')) > -1:
            tags = ",notify_highlight,log1"
```

Being able to provide a regex or list of words would probably be ideal, but requiring the nick to be its own word would work sufficiently well.

**Comment by tfheen** [comment]
I think this got fixed when we changed to letting weechat itself handle highlighting. Can you test and see if this is still a problem?

**Comment by trygveaa** [comment]
Your nick without @ is not highlighted by wee-slack anymore, as mentioned by @tfheen (if you still want this, you can add your nick to the option `weechat.look.highlight`). Your nick prefixed with @ is still highlighted, but only on exact matches. So this is fixed.
