### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'identifier'

### ISSUE THREAD

**Issue by petr-fischer** [wee-slack/wee-slack#224]
I have this error in weechat log buffer (after joining channel):

http://pastebin.com/raw/TuvXvsyV

**Comment by BlitzKraft** [comment]
```
11:53     weechat =!= | python: wrong arguments for function "buffer_set" (script: slack_extension)
11:53     weechat     | python: stdout/stderr: TypeError: must be string, not None
11:53     weechat =!= | python: error in function "slack_command_cb"
```
I see this when I open a new chat. A new buffer is opened and the action continues as expected. So, I am not sure why there is an error. Seems to be relevant.

**Comment by tfheen** [comment]
Are you still seeing this after #215 was merged? Also, what are the exact steps you are taking to reproduce this? Just join an existing channel?

**Comment by petr-fischer** [comment]
Yes, still with this errors, but everything looks fine. My steps:

    /join #channel

Then, error occurs in weechat buffer.

**Comment by trygveaa** [comment]
I'm pretty sure this is fixed now, so closing this issue.
