### ISSUE TITLE
Failed to connect

### ISSUE THREAD

**Issue by dhruvasagar** [wee-slack/wee-slack#232]
Here is a screenshot of what failed. Not exactly sure what is wrong, will have a look at the source later.
<img width="1141" alt="wee_slack" src="https://cloud.githubusercontent.com/assets/88258/15930311/c995d432-2e6f-11e6-86c4-50f093945939.png">

**Comment by dhruvasagar** [comment]
Actually, it is able to connect, that is not the problem. The problem is just that our team name consists of a unicode character that it isn't able to print. After a bit of fiddling I have found that this is mostly a weechat issue since I am able to print the character within python repl.

**Comment by tfheen** [comment]
Can you test if changing this to `self.buffer_prnt(u'{:<20}…` helps?  (That is, add a u immediately in front of the string to make it treat it as a unicode string?

**Comment by dhruvasagar** [comment]
I'll close this issue for the time being
