### ISSUE TITLE
Tab complete channels

### ISSUE THREAD

**Issue by kostajh** [wee-slack/wee-slack#235]
First, thanks for your amazing work on this! The plugin works great.

I'm wondering if tab completion of channels is something that should work, because I haven't been able to get it working properly. The `Ctrl-K` switcher in the official Slack client has a leg up on wee-slack in that regard, as it's much easier to switch by typing a few characters followed by `[tab]`.

**Comment by tfheen** [comment]
What method are you using for switching channels? I just use go.py which mostly removes the need for tab completion, but if there's a reasonable place we're missing tab completion, we should probably add it.

**Comment by adamgibbins** [comment]
I too use go.py with great success.
However, the out of box method for switching channels in weechat is to use /buffer #somechannel - this doesn't auto complete Slack channels for some reason but does others.

**Comment by mattrobenolt** [comment]
+1

my hunch is it has something to do with `weechat.completion.default_template`. The value is `%(nicks)|%(irc_channels)`, though I'm not sure how to coerce weechat into using Slack channels for completion.

**Comment by zubieta** [comment]
I found that when you cycle through all the buffers with tab, the slack buffers appear as `python.team.slack.com.#channel` and also as `team.slack.com.#channel`. But it will be a lot more convenient if we could complete the names with `#some_chars + tab`.

**Comment by wolfsage** [comment]
Yeah, `/buffer foo.#b<tab>` is no fun. I'd like to be able to `/buffer #b<tab>` like I used to
