### ISSUE TITLE
Retry on connection issues doesn't seem to do anything (except print reconnect message)

### ISSUE THREAD

**Issue by simeng** [wee-slack/wee-slack#238]
It claims to be retrying but doesn't seem to do anything.
Slack was down today for a short period and after it came back up wee_slack claimed to be trying to reconnect but only after reloading the script it reconnected.
This happened on two different clients with a 30 minute period between reloading the script so fairly sure it is bugged.

**Comment by torhve** [comment]
Exerpienced the same thing

**Comment by terlar** [comment]
Yes, definitely something wrong here, I experience the same every time my computer wakes up from sleep
