### ISSUE TITLE
Messages are sometimes sent to previously closed buffer/user

### ISSUE THREAD

**Issue by o2dazone** [wee-slack/wee-slack#242]
I haven't been able to completely reproduce this problem, but occasionally a message sent to a user will sometimes go to a buffer you've closed instead. Sending the same message again will then go to the correct person. 
- It seems to always send to the last buffer you closed
  - Though I haven't closed many channels, I assume it only affects buffers that are users.
- It never falsely sends to an existing/open buffer
- The bug has never occurred when sending a message to a newly opened buffer 
- In this scenario, I'm using a hotkey to invoke the `/close` command, not sure if that matters

**Comment by mrrsm** [comment]
This is happening to me again as well. 
There was a previously squashed bug #141 that addressed this in the past.

**Comment by nicksergeant** [comment]
How often does this bug happen? I love the idea of this plugin but am terrified of this bug, lol.

**Comment by o2dazone** [comment]
Enough to where I start all my conversations with a "." and then quickly remove it with s/// and type my message.

**Comment by nicksergeant** [comment]
Eek.

**Comment by adsr** [comment]
Just experienced this bug. Luckily it was an innocuous pm but this has the potential to be absolutely disastrous.

**Comment by o2dazone** [comment]
An update: I haven't had this issue since using `wee-ng` which has now been merged into the `wee-slack` repo. Closing for now, but I'll reopen it if it rears it's ugly head again.
