### ISSUE TITLE
failure and error in function "slack_command_cb" when connecting to channel

### ISSUE THREAD

**Issue by thingscouldbeworse** [wee-slack/wee-slack#256]
I'm not sure if this is part of an older issue, but I couldn't find information on it.

when attempting to connect to a channel, I receive this error;

```
python: stdout/stderr:     Traceback (most recent call last):                                                                                                 
python: stdout/stderr:     line 1009, in slack_command_cb
python: stdout/stderr:     command = cmds[function_name](current_buffer, args)
python: stdout/stderr:     line 1137, in command_join          
python: stdout/stderr:     servers.find(domain).channels.find(args).open()
python: stdout/stderr:     line 574, in open
python: stdout/stderr:     async_slack_api_request(self.server.domain, self.server.token, SLACK_API_TRANSLATOR[self.type]["join"], {"user": users.find(self.name).identifier}) 
python: stdout/stderr:     AttributeError: 'NoneType' object has no attribute 'identifier'
python: error in function "slack_command_cb"
```

**Comment by jayofdoom** [comment]
I'm seeing this issue as well. Well, to be exact; I see issue #22 unless I'm in the slack buffer. If I'm in the slack buffer, I see this issue.

Platform is Fedora 24, using the shipped fedora 24 websocket-client and shipped weechat.

**Comment by jayofdoom** [comment]
At least for my case, this is somewhat user error with a bad error message:

Case 1: Join a channel that doesn't exist: Get a good error saying it doesn't exist
Case 2: Join a channel that does exist: works as expected
Case 3: Join a channel I'm already in, it throws the traceback from OP

**Comment by thingscouldbeworse** [comment]
Hmm on a reinstall today I can't seem to replicate it. Maybe I just didn't realize I was connected to a specific channel last time I tried it out

**Comment by tfheen** [comment]
Let's keep this open so we can avoid spewing a backtrace when you rejoin a channel you're already a member of.

**Comment by trygveaa** [comment]
This has now been fixed.
