### ISSUE TITLE
alerts other than @$name and @all broken

### ISSUE THREAD

**Issue by tidux** [wee-slack/wee-slack#272]
I use Slack rooms that have custom alerts that only hit a subset of the full users present (such as @here for all users in the room set to active), and these currently do not work with wee-slack.  They show as !foo and do not highlight or set the notification bell in tmux.

**Comment by mattrobenolt** [comment]
Via the IRC gateway, Slack would translate these into `[cc matt]` or something akin to that to make sure you got pinged.

**Comment by mattrobenolt** [comment]
This behavior seems to be coming from https://github.com/rawdigits/wee-slack/blob/master/wee_slack.py#L562-L577

So not sure if it makes sense to replicate the same behavior as the IRC gateway did, and rewrite the message to include an explicit mention for your nick, or if there's a better weechat API to leverage to explicitly trigger the alert.

**Comment by tfheen** [comment]
We can set a tag on the line to generate a highlight, that's easy enough. However, I'm not sure if we can get a list of groups we're a member of, from which to generate highlights. There's also a discussion whether we should trust Slack's notification rules or the use the built-in bits in weechat.

**Comment by auscompgeek** [comment]
I think channel/everyone pings work in the latest version now.
