### ISSUE TITLE
doc fix

### ISSUE THREAD

**Issue by bechampion** [wee-slack/wee-slack#273]
/set buffers.look.short_names off
is needed before 
/set plugins.var.python.slack_extension.server_alias.my-slack-subdomain "mysub"

greetings from sebastian28

**Comment by tfheen** [comment]
@rawdigits, iirc you use buffers.pl, can you verify and write this up properly in the docs?

**Comment by trygveaa** [comment]
Weechat now as a buffer list built in, and you don't need to change any options for that when you set an alias, so I'm closing this.
