### ISSUE TITLE
Odd output on multiline code messages

### ISSUE THREAD

**Issue by grubernaut** [wee-slack/wee-slack#274]
Been getting some odd output on multiline code-block messages

Received:
![image](https://cloud.githubusercontent.com/assets/3082319/20023326/c42d276a-a2b5-11e6-9fe8-9a81491100a9.png)

From:
![image](https://cloud.githubusercontent.com/assets/3082319/20023336/d442e4c8-a2b5-11e6-81f7-fe0146e8bc2b.png)

**Comment by grubernaut** [comment]
Debug logs from message (token redacted)
```
17:44:55 | DEBUG: URL: url:https://hashicorp.slack.com/api/channels.mark?token=<redacted>&ts=1478295895.42&channel=<redacted> context: (dp0
17:44:55 | S'post_data'
17:44:55 | p1
17:44:55 | (dp2
17:44:55 | S'token'
17:44:55 | p3
17:44:55 | S'xoxp-<redacted>'
17:44:55 | p4
17:44:55 | sS'ts'
17:44:55 | p5
17:44:55 | F1478295895.417841
17:44:55 | sS'channel'
17:44:55 | p6
17:44:55 | VC0Z0YEUHY
17:44:55 | p7
17:44:55 | ssg3
17:44:55 | g4
17:44:55 | sS'request'
17:44:55 | p8  
17:44:55 | S'channels.mark'
17:44:55 | p9
17:44:55 | s. params: {'useragent': 'wee_slack 0.99.9'}
```

**Comment by grubernaut** [comment]
I can close my weechat client, and re-open it, and the messages are pulled correctly into scrollback, looks like it's only when a new message comes across.

**Comment by scharfie** [comment]
I'm also experiencing this issue in a more general case.  It seems any multiline message is rendered like this.

**Comment by grubernaut** [comment]
@scharfie yeah, I should have written another update to this a couple days ago, but I'm also seeing it on any multiline message, or webhook link.

**Comment by scharfie** [comment]
@grubernaut can you try out my fork to see if it solves the problem for you?

**Comment by grubernaut** [comment]
@scharfie that's worked for me for the past hour or so.

**Comment by tfheen** [comment]
This debug log just shows that wee-slack sends back "mark those bits as read", so it's not the incoming message. (I think we fail to actually log that, which we should fix.)

I don't understand why splitting it on newlines works around this, needs further investigation, since doing that split is not what we want.

**Comment by floored1585** [comment]
Any news on this or ideas about what is causing it?

**Comment by norbu09** [comment]
seen this as well and it gets more and more annoying - happy to test any bugfixes of patches for this.

I only see it if people paste something into slack as far as I can tell.

**Comment by tstelzer** [comment]
Had this problem myself, solved by using the latest update.

**Comment by antoyo** [comment]
I still get this issue in `wee-ng`.
@tstelzer How did you fixed this issue?
Thanks for your help.

**Comment by tstelzer** [comment]
@antoyo updated to `wee-ng`, haven't had the problem since.

**Comment by antoyo** [comment]
I applied this patch to the `slack.py` script available on the weechat website:
```patch
--- .weechat/python/slack.py    2017-04-24 10:29:23.122472569 -0400
+++ slack.py    2017-04-24 10:28:42.625806875 -0400
@@ -703,6 +703,7 @@
                         message)

             message = HTMLParser.HTMLParser().unescape(message)
+            message = message.replace("\n", "\n\t")
             data = u"{}\t{}".format(name, message).encode('utf-8')
             w.prnt_date_tags(self.channel_buffer, time_int, tags, data)
```
It fixes this issue in case anyone is interested.

**Comment by dzfweb** [comment]
i'm getting this error and don't know how to fix.

**Comment by trygveaa** [comment]
I have created a PR (#439) which hopefully fixes the issue without altering the behavior for users that don't experience the bug. Please test it and report if it fixes the problem or not.

**Comment by antoyo** [comment]
@trygveaa This fixes the issue for me.
Thank you so much.

**Comment by trygveaa** [comment]
This is now hopefully fixed.

@antoyo: Thank you for testing, and providing the initial patch :)
