### ISSUE TITLE
Allow making `/slack neveraway` permanent

### ISSUE THREAD

**Issue by s3rvac** [wee-slack/wee-slack#276]
Would it be possible to include a plugin setting for making `/slack neveraway` permanent, i.e. to survive a restart of WeeChat? Currently, I need to run the command manually whenever I start WeeChat because `neveraway` is always initialized to `False` when the plugin is loaded.

I have some experience with WeeChat plugins, so if you are interested, I can try to implement this and submit a PR.

**Comment by tfheen** [comment]
This sounds quite reasonable, so happy to take a PR.

**Comment by rawdigits** [comment]
This has been added in the merge of wee-ng. The setting is (predictably) called `never_away` and defaults to false
