### ISSUE TITLE
Ignore lists aren't respected

### ISSUE THREAD

**Issue by mattrobenolt** [wee-slack/wee-slack#277]
Not sure where to point the blame, but nicks that I've added to `/ignore add <nick>` doesn't seem to carry over into wee-slack. Specifically, I've had `slackbot` ignored over IRC gateway, and I seem to have lost the ability to block him now. :(

**Comment by BrianGallew** [comment]
I'd like to bump this.  Slack has the really annoying "feature" of not enabling any kind of ignore, so using Weechat's /ignore feature would really make using Slack a lot better for me (too many bots reporting things that I don't ever care about in channels where other important conversations happen)

**Comment by trygveaa** [comment]
`/ignore` is specific to irc. It is possible to read the list of ignores, but I can't find a way to notice when the list is changed.

`/filter` works with wee-slack. Is that not enough?

**Comment by BrianGallew** [comment]
Of course it is.  I totally missed that filter works here.  Please feel free to close this then.
