### ISSUE TITLE
slack_api_request failing on user identifier find on Arch Linux

### ISSUE THREAD

**Issue by Cyberdr8gon** [wee-slack/wee-slack#280]
on line 593, when users.find(self.name) is run, it is returning NoneType object. As a result the call to join the channel fails. This may be a environment issue, as this plug-in runs on python2 (i think i read that somewhere) and arch defaults to python3. I tried adding a shebang to the top of the file to run as python2 but I have had no luck so far and it continues to throw the error on trying to join a channel. 

10:28:19                      weechat     | python: stdout/stderr: Traceback (most recent call last):                                                                                                 │
10:28:19                      weechat     | python: stdout/stderr:   File "/home/player/.weechat/python/autoload/wee_slack.py", line 1038, in slack_command_cb                                        │
10:28:19                      weechat     | python: stdout/stderr:     cmds[function_name](current_buffer, args)                                                                                      │
10:28:19                      weechat     | python: stdout/stderr:   File "/home/player/.weechat/python/autoload/wee_slack.py", line 1199, in command_join                                            │
10:28:19                      weechat     | python: stdout/stderr:     servers.find(domain).channels.find(args).open()                                                                                │
10:28:19                      weechat     | python: stdout/stderr:   File "/home/player/.weechat/python/autoload/wee_slack.py", line 593, in open                                                     │
10:28:19                      weechat     | python: stdout/stderr:     async_slack_api_request(self.server.domain, self.server.token, SLACK_API_TRANSLATOR[self.type]["join"], {"user":               │
                                          | users.find(self.name).identifier})                                                                                                                        │
10:28:19                      weechat     | python: stdout/stderr: AttributeError: 'NoneType' object has no attribute 'identifier'                                                                    │
10:28:19                      weechat =!= | python: error in function "slack_command_cb"

**Comment by trygveaa** [comment]
If you have weechat installed from the Arch repos, that is compiled against python2 and will use that, so that should not be your problem.

To debug this, I would start with checking which name it tries to find, and which user names exist. E.g. by putting this in the find method in SearchList: `dbg("{}, {}".format(name, self))`

Also, what are you doing to trigger this issue?

**Comment by trygveaa** [comment]
`users.find` is not used anymore in the current version, so this problem should be fixed.
