### ISSUE TITLE
Notified when my nick is a substring of any word

### ISSUE THREAD

**Issue by tnguyen14** [wee-slack/wee-slack#294]
I get notified on any message that includes my username as a substring in any word. Unfortunately for me, since my nick is very short (`tri`), it is included in a lot of words, such as `district` or `substring`!

Is there a way to improve mention detection?

**Comment by trygveaa** [comment]
I checked now, and this does not happen for me. I don't recall if anything has changed in the last year, but as of now, wee-slack only sets up highlights for your nick prefixed with @ as its own word, so you will only be highlighted when someone mentions you.

Highlights for @here, @channel and @everyone, plus the words you have defined in the slack client are also set up, but they also need separate words.

If you still experience the issue, check the highlights you have defined in weechat yourself.
