### ISSUE TITLE
New threads feature in slack

### ISSUE THREAD

**Issue by BlitzKraft** [wee-slack/wee-slack#298]
Are there any plans to implement the threads feature? Any ideas/thoughts on it?

**Comment by tfheen** [comment]
We need to handle it in some form or fashion, at least. Details to be determined.

**Comment by keith** [comment]
Old versions of the Slack desktop app just show the responses like normal messages. I assume that part is at least working now?

**Comment by trygveaa** [comment]
The thread messages show up as normal now, except that they get a blank line beneath them, like this: http://s.whoop.wtf/ymw9r.png

One way to handle thread messages would be to prefix them with some text indicating which message they are in, e.g. like this:

> [20:30:10 trygveaa] test

Which would be a message containing "test" in a thread on a message from me at 20:30:10.

**Comment by cmhamill** [comment]
I'm a random user of this software, and just wanted to suggest a possible interface for this, along the lines of what @trygveaa said. Prefix messages as he suggested, but with a short, unique identifier:

```
[aghyp] test
```

Or perhaps `thread-<n>` test, if that's easier to implement. I'm not sure what the difficulty is of doing the next part in WeeChat's plugin API, but if you could register the short identifier in the auto-completion, and take messages of the form `aghyp: foo` and `@aghyp: foo` to be replies to that thread, it would make Slack threads work the way ad-hoc conversations already work in IRC.

Assuming the WeeChat API can be made to do this, the hardest part, I think, would be making the identifier unique across other thread identifiers and all usernames in the Slack organization. If that's too much of a mess, then another option is to take replies of the form `/reply adhyp foo`, perhaps as an alias for `/slack reply ahyp foo`.

Just my two cents. Thanks for the amazing work on this project already!

**Comment by BlitzKraft** [comment]
@cmhamill : I think that's a great idea. I use [weetweet](https://github.com/DarkDefender/weetweet) for twitter on weechat. It generates a sequential identifier for the tweets to be addressed for retweeting/adding favorites. 

Example, a to favorite a tweet, the command is `:fav e9` where e9 is the identifier. I guess something like that would be possible.

**Comment by rawdigits** [comment]
@cmhamill I brought up a similar idea in the `#wee-slack` irc channel a few days ago. Replies would be much like you say, but to expand it, I was going to allow you to open a 'channel' with the unique ID as well. This would let you keep a thread open for ongoing discussion.

**Comment by cro** [comment]
Now *that* would be slick.

**Comment by Wolf480pl** [comment]
Apparently it's been already implemented in [wee-slack/wee-ng](https://github.com/wee-slack/wee-ng)

**Comment by rawdigits** [comment]
Wee-ng has been merged to master, so threads support is now in mainline. 🎉
