### ISSUE TITLE
Stalls on /python reload or unload/load

### ISSUE THREAD

**Issue by barn** [wee-slack/wee-slack#301]
No stack trace, just doesn't do a whole bunch.

Not the most useful bug report but @rawdigits told me to make it anyway.

On release 85ca2dd820d64d1ce717ba44338f6dc26fe9e886 on weechat 1.7

**Comment by Ryuno-Ki** [comment]
Affects me, too.

```
14:18:50          weechat    | python: unloading script "slack_extension"
14:18:50          weechat    | python: loading script "$HOME/.weechat/python/autoload/wee_slack.py"
14:18:50          weechat    | python: registered script "slack_extension", version 0.99.9 (Extends weechat for typing notification/search/etc on slack.com)
14:18:50          weechat    | slack: DEBUG: Loading messages from cache.
14:18:50          weechat    | slack: DEBUG: Completed loading messages from cache.
14:20:59          weechat    | python: stdout/stderr: websocket connection error: [Errno 110] Connection timed out
14:21:02 $COMPANY.slack.com -- | Disconnected from slack, trying to reconnect..
```

**Comment by f0o** [comment]
Same here

**Comment by trygveaa** [comment]
The error messages should be improved now. Can you check if this is still an issue, and post which errors you get. Also, enable [debug mode](https://github.com/wee-slack/wee-slack#development) and post any errors/stacktraces printed there.

The error @Ryuno-Ki posted is an error with the network connection though, nothing wee-slack can do anything about.

**Comment by Ryuno-Ki** [comment]
For the record: My company was bought up. By now, I don't have the permissions to connect weechat with slack any more (workspace admin would need to grant it).

Personally I don't have any interest in Slack.

Thanks for this plugin, though :-)
