### ISSUE TITLE
Text between less-than greater-than signs are deleted

### ISSUE THREAD

**Issue by DirtYiCE** [wee-slack/wee-slack#304]
If you type text between < and > signs, like templates in C++ code, they'll be removed by wee-slack, but only client-side. Text containing <>s are sent correctly to slack servers, and displayed correctly in the html client.

Commenting out the body of `unfurl_refs` fixes this problem. Maybe it should ignore unknown patterns.

**Comment by trygveaa** [comment]
This has now been fixed (by commits 0523eb9 and 40c937f).

**Comment by tfheen** [comment]
Closing, per @trygveaa's comment.
