### ISSUE TITLE
Bare mode (alt-l) shows garbled text

### ISSUE THREAD

**Issue by bzar** [wee-slack/wee-slack#306]
Bare mode (no output formatting) is instrumental in opening links in weechat. This mode sometimes shows an incoherent jumble of previous messages in wee-slack buffers. The issue may be related to edited multiline messages. I could reproduce the issue by posting a multiline code block, editing it, then adding messages under it.

Regular: http://i.imgur.com/ZHolApP.png
Bare: http://i.imgur.com/hQpPaen.png

**Comment by trygveaa** [comment]
This should be fixed with #414.

**Comment by tfheen** [comment]
Closing, per @trygveaa's comment.

**Comment by auscompgeek** [comment]
#414 hasn't been merged yet though.

**Comment by tfheen** [comment]
That is an excellent point. :-)
