### ISSUE TITLE
Feature Request: Private Messages and Pushover

### ISSUE THREAD

**Issue by Grogglex** [wee-slack/wee-slack#312]
I've been using the WeeChat plugin for Push Notifications called "Pushover". I'm wondering why it is that when I recieve a private message on an IRC channel WeeChat registers it as a private message but when I recieve a private message in WeeSlack it doesn't seem to register it as a private message. 

Is this something that could be integrated?

The hooks that are defined in pushover.pl are:

[Pushover Plugin](https://weechat.org/scripts/source/pushover.pl.html/)
`weechat::hook_print("", "notify_message,notify_private,notify_highlight", "", 1, "print_cb", "");`

I assume I could just edit these hooks to include whatever event is fired on recieving a private message in WeeSlack?

**Comment by Grogglex** [comment]
I suspect that it is related to #211. I'll make the modifications to the Pushover.pl script and report back.

**Comment by tfheen** [comment]
@Grogglex : did changing pushover.pl fix anything?

**Comment by tfheen** [comment]
No response from submitter, so closing this. Feel free to reopen if it's still an issue.
