### ISSUE TITLE
Emoji reactions for file upload messages misbehave

### ISSUE THREAD

**Issue by bzar** [wee-slack/wee-slack#316]
Upload messages are shown in wee-slack as "&lt;nick&gt; uploaded a file: &lt;url&gt; (&lt;more information&gt;)". Adding an emoji reaction to this message works, but doesn't show up in slack web client. Conversely, adding a reaction to the message in web slack doesn't show in wee-slack.

To replicate, upload an image in web slack, add reaction in wee-slack. Then add a different reaction in web slack. Compare.

**Comment by trygveaa** [comment]
Slack recently changed file uploads to be normal messages with files attached. This change fixed this issue, so now it works just like any other message.
