### ISSUE TITLE
Messages sent to wrong buffer after a buffer move/close

### ISSUE THREAD

**Issue by major0** [wee-slack/wee-slack#317]
== Condition #1 ==
Closed a private Slack conversation in WeeChat via `/close`.

Started a new Slack conversation via `/msg <nick>`.

WeeChat created a new buffer and sent the message to the destination user correctly, but all subsequent messages within that buffer went to the nickname which was previously in that buffer (prior to the `/close`).

== Condition #2 ==
Closed a private Slack conversation in WeeChat via `/close`.

A new buffer was created upon the reception of a private Slack message from a user.

Replies in the new buffer went to the user which was previously attached to the buffer prior to the `/close`.

**Comment by mrrsm** [comment]
Condition 2 just hit me on Friday last week. It seems to have just cropped back up recently though as I haven't had an issue in quite a while with wrong buffers.

**Comment by major0** [comment]
I have had it happened fairly reliably today. Both conditions as described above happened w/in 5 minutes of one another.

I currently have 14 buffers open, 4 of which are IRC+SSL, 9 Slack, and 1 Relay monitor (WeeChat-Andriod).

**Comment by rawdigits** [comment]
Wee-ng has been merged to master and fixes this issue. We no longer use the .find methods, so this shouldn't be possible anymore.
