### ISSUE TITLE
python: stdout/stderr: NameError: name 'book' is not defined

### ISSUE THREAD

**Issue by ibrokemypie** [wee-slack/wee-slack#321]
weechat     | python: loading script "/Users/Conor/dotfiles/.weechat/python/autoload/wee_slack.py"
 weechat     | python: stdout/stderr: Traceback (most recent call last):
 weechat     | python: stdout/stderr:   File "/Users/Conor/dotfiles/.weechat/python/autoload/wee_slack.py", line 1, in <module>
 weechat     | python: stdout/stderr:     book
 weechat     | python: stdout/stderr: NameError: name 'book' is not defined
 weechat =!= | python: unable to parse file "/Users/Conor/dotfiles/.weechat/python/autoload/wee_slack.py"

**Comment by bendem** [comment]
You might want to open that file to see what's in it. Because it's not the script. You probably downloaded the html page instead of the raw script.
