### ISSUE TITLE
Feature Request: Bold and italics terminal font

### ISSUE THREAD

**Issue by mcastorina** [wee-slack/wee-slack#325]
It would be nice to display text surrounded by * or _ as bold or italic in the buffer like in Slack.
e.g. `*this text is bold* and _this text is italic_`

**Comment by ToxicFrog** [comment]
Implemented in #338

**Comment by auscompgeek** [comment]
I'm not seeing italics.

**Comment by ToxicFrog** [comment]
IRC doesn't support italics (and neither do most terminal emulators); italics in slack get rendered as underlines in IRC, and vice versa.

**Comment by chreekat** [comment]
I'm not upset with the way things are, but my terminal (Gnome Terminal) *does* support italics, and I think it would be nice to keep the option open for the future.

**Comment by ToxicFrog** [comment]
It looks like weechat itself supports italics if the terminal and libcurses do, so I don't see any technical obstacles to this.

It shouldn't be hard to add a configuration setting to toggle between rendering italics as underline vs. as italics.

**Comment by chreekat** [comment]
Yeah, I was just trying it out -- weechat's `/help trigger` even lists the necessary trigger for bold/underline/italic as an example[1]. :) Unfortunately it wasn't immediately successful: it did the "use reverse in place of italics" hack that I've seen elsewhere and don't immediately recall how to fix...

[1]: Copied here: 
```
/trigger add effects modifier weechat_print "${tg_tag_nick}" "==\*(\S+)\*==*${color:bold}${re:1}${color:-bold}*== ==_(\S+)_==_${color:underline}${re:1}${color:-underline}_== ==/(\S+)/==/${color:italic}${re:1}${color:-italic}/"
```

**Comment by mcastorina** [comment]
Bold and italic doesn't appear to be working: `*_bold and italic_*`

**Comment by ToxicFrog** [comment]
Testing: `*_bold and italic_*` renders as `_bold and italic_` in bold, and `_*italic and bold*_` renders as `*italic and bold*` in italic (well, underlined).

Looking at the code I would expect the former to work even if the latter doesn't.

**Comment by ToxicFrog** [comment]
If they aren't nested side by side it works, e.g. `_italic and *bold* in the middle_` renders correctly.

**Comment by auscompgeek** [comment]
> IRC doesn't support italics

IRC does have italics. weechat has the default keybind of <kbd>C-c i</kbd> to make text italics.

**Comment by ToxicFrog** [comment]
What does this turn into on the wire? Because most clients don't support it, and last time I saw someone try to use an italics-enabled client on IRC it sent `^I` as the italics code, otherwise known as TAB, which didn't really work out so well.

**Comment by auscompgeek** [comment]
That's why everyone standardised on `\x1D`. I don't know of any maintained clients that _don't_ support italics nowadays.

**Comment by ToxicFrog** [comment]
Huh. I don't think I've ever seen that in the wild, or if I did, it didn't work with the clients I was using (mostly hexchat and weechat).

At any rate, I'm working on a patch that should enable italic support for weeslack, but someone else will need to test it, because I don't have my tty set up for italic support.

**Comment by ToxicFrog** [comment]
Looks like this is going to add three new settings:
- `render_bold_as` controls how incoming `*bold*` is rendered
- `render_italic_as` controls how incoming `_italic_` is rendered
- `map_underline_to` controls how outgoing underlines are rendered in slack

**Comment by ToxicFrog** [comment]
See PR #350

**Comment by ToxicFrog** [comment]
PR/#350 adds italics support, and options to translate italics to underline for people whose terminals don't support italics.

I/#354 tracks issues with nested formatting characters.
