### ISSUE TITLE
Direct messages are sometimes sent to wrong recipients

### ISSUE THREAD

**Issue by bzar** [wee-slack/wee-slack#327]
I've noticed that sometimes when I send a direct message to a person, the message doesn't appear in the buffer on the first try, but on the second. Now I've verified that when this happens, the message is actually being sent to *another* direct messaging buffer. This has caused some funny stuff on occasion, but could be quite severe at the wrong moment.

**Comment by bzar** [comment]
I just noticed the "other" buffers might have been immediately after the buffer being written to, and it might be relevant that I have one IRC channel buffer open as well, located before (in the buffer number order) all of them. So could be some kind of off-by-one error.

**Comment by bzar** [comment]
Possibly related to #317

**Comment by rawdigits** [comment]
Wee-ng has been merged to master and fixes this issue. We no longer use the .find methods, so this shouldn't be possible anymore.
