### ISSUE TITLE
Multiline messages are shown as python | channel-name

### ISSUE THREAD

**Issue by antoyo** [wee-slack/wee-slack#332]
Hello.
When I receive a multiline message it shows as such:

> username | Test
> python | org.slack.com.channel
> python | org.slack.com.channel
> python | org.slack.com.channel

instead of the usual:

> username | Test
> username | Multi
> username | Line
> username | Message

If I leave and open again WeeChat, I see the multiline message correctly.

Thanks to fix this issue.

**Comment by V13Axel** [comment]
I've seen reports that this is fixed in [wee-ng](https://github.com/wee-slack/wee-ng). 

Have you tried using it instead?

**Comment by V13Axel** [comment]
This is also a duplicate of #274

**Comment by dzfweb** [comment]
i'm having this problem, and the https://github.com/wee-slack/wee-ng don't exists.
