### ISSUE TITLE
Slack has moved their token generation page

### ISSUE THREAD

**Issue by jetpacktuxedo** [wee-slack/wee-slack#333]
This is perhaps related to #135 

Slack seems to have moved their token generation from https://api.slack.com/web to
https://api.slack.com/custom-integrations/legacy-tokens , presumably in an effort to push more people towards the login api. The readme should probably be updated to reflect this move.

**Comment by jetpacktuxedo** [comment]
Or alternatively, have the readme direct users to `/slack register` that I just found poking around in help :P

**Comment by rawdigits** [comment]
Fixed!
