### ISSUE TITLE
Server alias broken

### ISSUE THREAD

**Issue by OzQu** [wee-slack/wee-slack#337]
/set plugins.var.python.slack_extension.server_alias.my-slack-subdomain "mysub"

Seems like the latest version broke server_alias option.

**Comment by trygveaa** [comment]
The syntax for the server alias config has changed a bit. It is now:

```
/set plugins.var.python.slack.server_aliases "my-slack-subdomain:mysub"
```

@rawdigits: I guess server aliases was not migrated to the new way of setting it?

**Comment by OzQu** [comment]
Ok, now it works! I haven't noticed that change before. Documentation is not yet updated, at least regarding that.

**Comment by rawdigits** [comment]
Ah damn, you're right @trygveaa - i guess it wasn't migrated properly. sorry about that @OzQu
