### ISSUE TITLE
Weechat takes 100% cpu after sleep and wake

### ISSUE THREAD

**Issue by cro** [wee-slack/wee-slack#349]
I've noticed that after sleeping and waking my MacBook Pro, weechat will take 100% CPU.  Haven't had a chance to investigate more fully, just wanted to record the issue before I forgot.

This is with the NG code.

**Comment by dbarrosop** [comment]
I can confirm I have experienced the same problem.

**Comment by adamgibbins** [comment]
I have weechat chewing 100% CPU in some occasions, however, it's not caused by suspension - this is on a server that's continually on. I'm running weechat 1.7-1 on Ubuntu Trusty (14.04).

**Comment by oschwald** [comment]
This is also happening to me after upgrading to the rewrite. In my case, it did occur after a sleep and wake, but it does not seem to happen every time. I am on Ubuntu 16.10.

**Comment by norbu09** [comment]
seems to be a websocket issue, I see this in `truss` on FreeBSD-12-current:

```
poll({ 5/POLLIN 0/POLLIN 16/POLLIN 18/POLLIN 19/POLLIN 17/POLLIN 20/POLLIN 25/POLLIN 26/POLLIN 29/POLLIN 30/POLLIN 32/POLLIN },12,8) = 1 (0x1)
read(32,0x80fc5e703,5)				 ERR#35 'Resource temporarily unavailable'
stat("/usr/home/USER/.weechat/python/autoload/wee_slack.py",{ mode=-rw-r--r-- ,inode=2132303,size=124755,blksize=124928 }) = 0 (0x0)
stat("/usr/local/lib/python2.7/site-packages/websocket/_core.py",{ mode=-rw-r--r-- ,inode=350650,size=16444,blksize=16896 }) = 0 (0x0)
stat("/usr/local/lib/python2.7/site-packages/websocket/_core.py",{ mode=-rw-r--r-- ,inode=350650,size=16444,blksize=16896 }) = 0 (0x0)
stat("/usr/local/lib/python2.7/site-packages/websocket/_core.py",{ mode=-rw-r--r-- ,inode=350650,size=16444,blksize=16896 }) = 0 (0x0)
stat("/usr/local/lib/python2.7/site-packages/websocket/_core.py",{ mode=-rw-r--r-- ,inode=350650,size=16444,blksize=16896 }) = 0 (0x0)
stat("/usr/local/lib/python2.7/site-packages/websocket/_abnf.py",{ mode=-rw-r--r-- ,inode=350644,size=12382,blksize=12800 }) = 0 (0x0)
stat("/usr/local/lib/python2.7/site-packages/websocket/_abnf.py",{ mode=-rw-r--r-- ,inode=350644,size=12382,blksize=12800 }) = 0 (0x0)
stat("/usr/local/lib/python2.7/site-packages/websocket/_abnf.py",{ mode=-rw-r--r-- ,inode=350644,size=12382,blksize=12800 }) = 0 (0x0)
stat("/usr/local/lib/python2.7/site-packages/websocket/_core.py",{ mode=-rw-r--r-- ,inode=350650,size=16444,blksize=16896 }) = 0 (0x0)
stat("/usr/local/lib/python2.7/site-packages/websocket/_socket.py",{ mode=-rw-r--r-- ,inode=350665,size=3603,blksize=4096 }) = 0 (0x0)
stat("/usr/local/lib/python2.7/ssl.py",{ mode=-rw-r--r-- ,inode=10821,size=37805,blksize=37888 }) = 0 (0x0)
stat("/usr/local/lib/python2.7/ssl.py",{ mode=-rw-r--r-- ,inode=10821,size=37805,blksize=37888 }) = 0 (0x0)
```

**Comment by rawdigits** [comment]
It is definitely spinning on a dead file descriptor. I'm going to figure out how to detect this.

**Comment by gilbertw1** [comment]
I've noticed this as well on Arch linux. Happens frequently on resume, and I've noticed it occasionally if I'm on relatively sketchy internet connections.

**Comment by yeled** [comment]
does anyone have some gdb commands I can run to help debug this?

**Comment by gilbertw1** [comment]
I've tried to debug this to no avail using primitive means (I'm not very familiar with python or the weechat api's).

It's a pretty thorny bug, I have to be very diligent about quitting weechat when I suspend my laptop or it'll wake up and take 100% cpu and a chunk of my battery life if I don't realize it quickly.

**Comment by denibertovic** [comment]
I can confirm this happens to me after resuming from suspend.

**Comment by gilbertw1** [comment]
Yep, I wrote a systemd script to kill weechat and pop a notification if it's running on suspend/resume (/lib/systemd/system-sleep/kill-weechat):

```
#!/bin/sh
if pgrep -x "weechat" > /dev/null
then
    sudo -u $USER DISPLAY=:0 DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus notify-send "Terminating WEECHAT process. (HIGH CPU BUG)"
    killall -9 weechat
fi
```

Crude, but it prevents my battery life from getting destroyed.

**Comment by ToxicFrog** [comment]
Simply reloading the slack plugin (`/python reload slack`) fixes it as well, although I don't know if there's a way to send commands to weechat automatically from "outside".

**Comment by adamgibbins** [comment]
On June 22, 2017 5:35:40 PM GMT+01:00, Ben Kelly <notifications@github.com> wrote:
>Simply reloading the slack plugin (`/python reload slack`) fixes it as
>well, although I don't know if there's a way to send commands to
>weechat automatically from "outside".
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/wee-slack/wee-slack/issues/349#issuecomment-310434534

You can send commands to weechat via the fifo plugin, gives you the ability to just pipe stuff into a socket.
