### ISSUE TITLE
/slack upload fails for files dropped on Terminal.app/iTerm2

### ISSUE THREAD

**Issue by vilhalmer** [wee-slack/wee-slack#360]
The file upload code currently does:

    file_path = file_path.replace(' ', '\ ')

to try to shell-escape the provided path. However, on macOS, both of the major terminals do this automatically when you drop a file on the window. This leads to the backslashes being escaped by the existing backslashes, and the upload failing because the file doesn't exist.

The easiest solution to this is probably to add a preference to skip the automatic escaping, but I thought I'd raise it here to see if anyone has a clever-er solution before just submitting a PR. I'm more than happy to do the work for this either way.

**Comment by bendem** [comment]
Should probably just check if the file exist before escaping.

**Comment by nicholma** [comment]
Could something along the lines of work?
```python
file_path = re.sub(r'([^\\]) ', r'\1\\ ', file_path)
```

If I have a file with a `\` in the name, example '\.txt' created by 
```bash
echo 'yo' > '\.txt'
```
To upload it I have to escape the name: `\slack upload \\.txt` 
Are there any other odd cases?

**Comment by vilhalmer** [comment]
There's also `pipes.quote` that should cover any and all shell weirdness. https://docs.python.org/2/library/pipes.html#pipes.quote
