### ISSUE TITLE
wee-slack has no help command

### ISSUE THREAD

**Issue by deepy** [wee-slack/wee-slack#363]
/help slack -> Use /slack help [command] to find out more -> Command not found: help

This should either be removed from:
https://github.com/wee-slack/wee-slack/blob/master/wee_slack.py#L3159

Or a help command added.

**Comment by auscompgeek** [comment]
This existed before the wee-ng refactor. Copying the help command from before that should work.

**Comment by deepy** [comment]
While that might restore some of the functionality that won't solve the issue, the commands do not work the same as before and restoring the old help would be even more confusing than what's currently there.

**Comment by auscompgeek** [comment]
How so? iirc, the help command used to simply print the docstrings of the command functions. The help strings weren't part of the help command's code.
