### ISSUE TITLE
Sender nicks don't have colors

### ISSUE THREAD

**Issue by bzar** [wee-slack/wee-slack#364]
I asked about this at wee-slack IRC channel. After updating wee-slack I lost all nick coloring functionality, not just in messages but also sender ones that should be handled by weechat. To be clear, I mean the ones to the left of sent messages.

Installing colorize_nicks.py alleviates this, but it's still not the same coloring as with weechat's own system. For example for user's nick.

Should be reproducible by otherwise having nick colors working in IRC, not having colorize_nicks.py loaded and viewing a wee-slack buffer.

**Comment by trygveaa** [comment]
> Should be reproducible by otherwise having nick colors working in IRC, not having colorize_nicks.py loaded and viewing a wee-slack buffer.

Nick colors for the nicks to the left of the messages are working for me, without `colorize_nicks.py`, so there must be something more to it.

**Comment by bzar** [comment]
Any idea what that could be? I'm open to testing possibilities.

Because of *reasons* I am using an old (but patched) version of weechat (1.4), also a 256 color theme.

**Comment by gilbertw1** [comment]
@bzar: This is likely your problem:  arza-zara/weechat@ce4e66e

It looks like the color functionality was internalized into the plugin infrastructure in 1.5 and wee-slack is using this functionality: ```w.info_get('nick_color_name', self.name)```

It looks like the ```info_get``` keys were changed, so you might be able to simply fix the issue by doing a string replace of ```nick_color_name``` with ```irc_nick_color_name```. On a side note, it looks like ```irc_nick_color_name``` is still used in [colorizing private chats](https://github.com/wee-slack/wee-slack/blob/master/wee_slack.py#L1539).

Hope that helps!

**Comment by ToxicFrog** [comment]
Per discussion on IRC -- `irc_nick_color_name` was deprecated in 1.5, which is why we stopped using it, and will probably go away entirely at some point.

The best way to handle this, if we want to support older weechat versions (which we should, for people on debian if nothing else), is probably to automatically select the `irc_` version or not depending on what weechat version we're running under.

**Comment by bzar** [comment]
Yes, this fixes the issue! Thank you all.

**Comment by ToxicFrog** [comment]
Leaving this open until this is fixed in weeslack proper -- we want it to just work™, not just point users at what they need to change to make it work. :)

**Comment by bendem** [comment]
I fixed this 2 months ago. It's still waiting there https://github.com/wee-slack/wee-slack/pull/318

**Comment by ToxicFrog** [comment]
Oh, awesome. I'll see about getting that conflict-resolved and merged in this week. Thanks!

**Comment by bendem** [comment]
Fixed the conflict, it's all yours
