### ISSUE TITLE
/slack setallreadmarkers disappeared

### ISSUE THREAD

**Issue by blendmaster** [wee-slack/wee-slack#368]
in https://github.com/wee-slack/wee-slack/pull/334 . Still mentioned in the readme though.

I'm still having the problems with sync mentioned in https://github.com/wee-slack/wee-slack/issues/323 , perhaps related.

**Comment by auscompgeek** [comment]
I believe this was deprecated in favour of simply marking all weechat buffers as read.

**Comment by trygveaa** [comment]
You can now mark all the channels as read by running `/input set_unread` (note that this will move the unread markers on all buffers, non wee-slack as well). Does this suffice, or is there still a need for the `/slack setallreadmarkers` command?

**Comment by blendmaster** [comment]
I just wanted #323 fixed, which looks like that's closed now. `setallreadmarkers` is still mentioned in the readme though, probably good to remove it.

**Comment by trygveaa** [comment]
Great. I've removed `setallreadmarkers` from the readme now in d02bde0, so I'll close this.
