### ISSUE TITLE
weechat crashes when initializing wee-slack in German (de_DE) locale

### ISSUE THREAD

**Issue by dennistang** [wee-slack/wee-slack#373]
weechat crashes when initializing wee-slack when I'm running in de_DE locale.

### Notes
* I recall the de_DE locale working fine when I was on a ThinkPad running Ubuntu 16.04 LTS
* Currently experiencing this issue on macOS 10.12.5 on a Late 2016 MacBook Pro
* Running `/set env LANG en_US.UTF-8` and then `/upgrade` resolves the issue, and wee-slack works perfectly after!

**Comment by tfheen** [comment]
How does it crash/what is the error?

**Comment by trygveaa** [comment]
Closing since we never got any response from the author, so it's hard to know what kind of error he got.
