### ISSUE TITLE
Slash command responses not showing

### ISSUE THREAD

**Issue by OzQu** [wee-slack/wee-slack#374]
Slack Custom Slash command responses are not shown in my weechat via wee-slack. Do I have some config property incorrectly or is this a bug? Response is shown in Slack web-UI. My custom slash command response prints command correctly to wee-slack but actual response is not shown. Response is visible to all users in Slack.

**Comment by mcritchlow** [comment]
This looks like a dup of #369 , and is apparently still an issue as I'm experiencing the same on the most current version.
