### ISSUE TITLE
Strange Notification Behaviour

### ISSUE THREAD

**Issue by frioux** [wee-slack/wee-slack#375]
This is hard to explain because I can't quite tell what all is going wrong, but I suspect it's going wrong for everyone so I might as well create a ticket and people can chime in.

It used to be that if I muted a channel in the web client, I wouldn't get notifications in that channel in wee-slack (right?  I am pretty sure it worked that way.)

Additionally, lately I have gotten notifications that a message was sent to, for example, channel 2, so I switch to channel 2, see wee-slack pause to pull down messages, and nothing shows up, even to the point that I have seen a channel be absurdly out of sync.  For example I can change to channel `#alcohol` right now and wee-slack shows a message from *May 23* even though the web client shows activity from today.

**Comment by auscompgeek** [comment]
Sounds like a dead websocket is lingering around. You'll probably find weechat is using 100% CPU as well.

**Comment by frioux** [comment]
why would a dead websocket make notifications *appear* when they didn't used to?

**Comment by frioux** [comment]
Created a separate, more clear ticket for this.
