### ISSUE TITLE
Support longer back history

### ISSUE THREAD

**Issue by oblitum** [wee-slack/wee-slack#376]
Currently the back history I can access on a channel is very short, and I need to get to the web client to view a longer back history. Would it be possible to add support to going further back in the history log?

**Comment by tfheen** [comment]
Does doing `/rehistory` get you sufficient amounts of history?

**Comment by oblitum** [comment]
@tfheen no, it just gets to the same limit as initially.

**Comment by virus-found** [comment]
I second this question.

**Comment by trygveaa** [comment]
This can now be configured with the option `history_fetch_count`. The minimum supported value is 1 and the maximum supported value is 1000.
