### ISSUE TITLE
Getting notified for own message in private chat

### ISSUE THREAD

**Issue by denibertovic** [wee-slack/wee-slack#378]
I'm using `notify.py` weechat script to get notified via libnotify when someone highlights me. This works great in all IRC channels and IRC private messages. It works in slack channels as well.

The only place I'm seeing this problem is in Slack direct messages where I get notified for both my own messages (that i sent) and the messages I got from the other slack user I was chatting with.

(I'm using wee-slack from latest master, as of today... and I'm using notify.py from the weechat scripts directory [here](https://weechat.org/scripts/source/notify.py.html/).

**Comment by mkraemer** [comment]
While I'm using https://github.com/s3rvac/weechat-notify-send instead of notify.py I noticed the same behaviour.

As a workaround, I set notify_send to not send notifications for the nick 'unknown':

    /set python.notify_send.ignore_nicks = "unknown"

Maybe something similar can be used w/ notify.py :)

**Comment by denibertovic** [comment]
@mkraemer thanks! This works perfectly. I'm still unclear about the reason this happens though... It probably has to do with slack having @myusername be something like @Q09WE3 and then wee-chat replaces that with the actual username. But somewhere in that pipeline this happens.

**Comment by auscompgeek** [comment]
I suspect this has something to do with wee-slack not setting the usual nick variable on messages (at least I don't think this is happening since the wee-ng refactor).

**Comment by dzfweb** [comment]
i'm facing the same problem.
the problem is on the empty variable `localvar_nick`  used to check my name.

**Comment by dzfweb** [comment]
in my case i'm getting notified even when getting history on open channel / private message

**Comment by denibertovic** [comment]
I'm not sure if this was fixed with a new update to wee-slack or if  the fix lies in me switching to this script: https://weechat.org/scripts/source/notification.py.html/ but in any case it works now so I'm closing this.

**Comment by chunkhang** [comment]
If you're using `notification_center.py`, you can add an additional check to ignore notifications if the message is coming from the current buffer you're viewing.
```
if prefix == ('@%s' % own_nick) or prefix in tags or buffer == weechat.current_buffer():
	return weechat.WEECHAT_RC_OK
```
