### ISSUE TITLE
`/slack channels`, `/slack users` not working

### ISSUE THREAD

**Issue by jessebye** [wee-slack/wee-slack#379]
Using commands `/slack channels` as well as `/slack users` results in the following error:  `Command not found: channels` or `Command not found: users`.

**Comment by auscompgeek** [comment]
These existed before the wee-ng refactor. Copying them from before that will probably work.

**Comment by hshin23** [comment]
`/slack join` doesn't work either. Is there a way to resolve this issue?

**Comment by dzfweb** [comment]
@auscompgeek  where is the wee-ng code which i could copy?

**Comment by dzfweb** [comment]
i fixed on my repository #https://github.com/dzfweb/wee-slack/commit/796894e1b9d45c5d1e830afd548e6b5f442ae52e 

already open a PR for it and other fixes #https://github.com/wee-slack/wee-slack/pull/386

**Comment by tfheen** [comment]
Please don't intermingle fixes in PRs, it makes it very hard to review and selectively merge bugfixes and discuss features separately.

**Comment by trygveaa** [comment]
This has now been fixed with #449.
