### ISSUE TITLE
Disable link preview

### ISSUE THREAD

**Issue by denibertovic** [wee-slack/wee-slack#381]
Is there a way to disable the url preview feature? I'd like to just see the url and be able to open it normally in my browser but what happens is it expands into a bunch of urls and some text that isn't easily discernible from the original text from person who shared the url. 

I tried disabling image/url preview in the slack interface but that works only for the web client. Wee-slack still expands the urls.

**Comment by dbarrosop** [comment]
It doesn't disable link preview but I think this PR I just opened might be of help:

https://github.com/wee-slack/wee-slack/pull/387

**Comment by denibertovic** [comment]
This is fixed with the latest wee-slack from master so I'm closing.

**Comment by wohali** [comment]
@denibertovic How are you managing to disable link preview? I don't see an option. Neither `unfurl_ignore_alt_text` nor `unfurl_auto_link_display` prevent link expansion.

This might need to be re-opened?

**Comment by denibertovic** [comment]
I did not have to do anything. Just used the latest master after the above PR was merged and it worked fine.

**Comment by wohali** [comment]
@denibertovic OK, thanks. The above PR only prevents mulitiple URL expansions.

I'll submit my own PR for fully disabling that feature.
