### ISSUE TITLE
buflist.look.nick_prefix_empty doesn't work in buffer

### ISSUE THREAD

**Issue by yeled** [wee-slack/wee-slack#382]
expected behaviour: `buflist.look.nick_prefix_empty` should leave a space blank if a person types two or more lines in a row, to clean up the aligned prefix style.

example from an IRC buffer:

![2 _mosh_wee-slack_w12__p01_mosh-client_2017-07-03_15-30-02](https://user-images.githubusercontent.com/200421/27798076-dcab223c-6007-11e7-9095-49f1d8cdaf70.png)

This doesn't work in a slack buffer:

![2 _mosh_sanfrancisco_w12__p01_mosh-client_2017-07-03_15-32-40](https://user-images.githubusercontent.com/200421/27798087-e870c4fa-6007-11e7-9533-58d2398ea345.png)

**Comment by auscompgeek** [comment]
Uh, I'm pretty sure `buflist.*` are settings for the buflist plugin. Did you mean `weechat.look.prefix_same_nick`? #357 is open for that.

**Comment by yeled** [comment]
Argh. Yep!
