### ISSUE TITLE
Persist order of Slack Teams

### ISSUE THREAD

**Issue by bascht** [wee-slack/wee-slack#383]
First and all: Thanks for creating `wee-slack` and helping me to save about 1.5 GB of RAM that I'd otherwise have to waste on keeping multiple slack teams open in the official app! 👍 

I've got a small(-ish) issue I couldn't resolve via the docs: 

Is it possible to keep the order of the Slack teams across restarts of Weechat? It currently looks like they're ordered by the time they connected, which makes it harder to find the channel / team I'm looking for.

Having them connect in the order I set them in `plugins.var.python.slack.slack_api_token` or `plugins.var.python.slack.server_aliases` would be great. 😄

**Comment by yeled** [comment]
I find the hand-ordering by buffer # also is lost across reloads

**Comment by ToxicFrog** [comment]
In my experience this isn't reliable in weechat for IRC networks either; the expectation is that you'll get them organized the way you like (using `/buffer move|swap|merge`) and then use `/layout store` to save the buffer ordering. Once you've done that it'll remember it across restarts no matter what order it connects to its networks in.

**Comment by yeled** [comment]
I take it back. `/layout store` and a reload of the plugin worked to keep the buffers in order. Sorry for derailing.

**Comment by bascht** [comment]
Can confirm @yeled's observation. Storing the layout via `/layout store` and re-applying via `/layout apply` does work quite nicely. 

Closing this issue as this solves the problem. 😄
