### ISSUE TITLE
history not loading

### ISSUE THREAD

**Issue by drselump14** [wee-slack/wee-slack#393]
Suddeny history is no longer loaded when open weechat. Is there any setting that I missed here?
any help would be appreciated

**Comment by kalbasit** [comment]
I'm having the same issue, but for a while now. The history is always a few days behind when I open weechat. Also, whenever the connection drops, the history is reset to a few days ago again. Is it possible to add a command to force refresh history?

**Comment by rawdigits** [comment]
there is already a command: `/rehistory` in the buffer will grab it again.

**Comment by kalbasit** [comment]
oh awesome, I didn't know about `/rehistory`, is it documented anywhere?

**Comment by kalbasit** [comment]
@rawdigits `/rehistory` is not working. I just received a message on slack but not on weeslack, I tried to `/rehistory` and it did not work. I restarted weeslack, the message was still missing, `/rehistory` did not help again, but I did get newer messages.

**Comment by drselump14** [comment]
The issue disappear when I updated the script/plugin using the command below

```
wget https://raw.githubusercontent.com/wee-slack/wee-slack/master/wee_slack.py
cp wee_slack.py ~/.weechat/python/autoload
```

I'll close this issue .. however isn't there any better way to update the script?using script command for example ...
