### ISSUE TITLE
Channels with new messages not added to the hotlist on startup

### ISSUE THREAD

**Issue by gilbertw1** [wee-slack/wee-slack#396]
Slack very recently updated their rtm.start endpoint to remove 'latest', 'unread_count', and 'unread_count_display' properties from all channel objects.

Wee-slack relies on 'unread_count_display' to determine if there are new unread messages in a channel. Since this value is missing, wee-slack no longer adds any channels to the hotlist on startup.

Details here: https://api.slack.com/changelog/2017-04-start-using-rtm-connect-and-stop-using-rtm-start

**Comment by tardypad** [comment]
Ah! Thanks. Finally the culprit is found.
I was wondering what was happening lately...
I thought this was a problem with my local config or so.

Hopefully this can be fixed soon :pray:, since it is currently "unusable"

**Comment by gilbertw1** [comment]
Hah, I thought the same thing. I even went so far as to start reproducing my config from scratch with an older version of Weechat before I realized the problem might be in wee-slack.
