### ISSUE TITLE
Display user online status (presence)

### ISSUE THREAD

**Issue by spectralsun** [wee-slack/wee-slack#398]
It would be awesome if there was some way to indicate whether a user is online or not according to slack.

Slack has 3 modes: online, snooze and offline. There are no indicators of who is admin, so maybe we could use the voice (+) and another op flag to indicate presence.

**Comment by auscompgeek** [comment]
wee-slack originally split the nicklist into two groups: online and offline. This ended up being removed due to performance concerns, I believe, although there have been several requests since then to add it back. Perhaps we could see a return of this feature behind a setting.
