### ISSUE TITLE
Thread logging no longer works

### ISSUE THREAD

**Issue by ToxicFrog** [wee-slack/wee-slack#409]
So, my logging configuration for all my slacks looks like:

`logger.mask.python.<net>.slack.com = "<net>.slack.com/$channel/%Y-%m-%d"`

And until recently this worked fine.

After a recent pull, though, it stopped working, and every thread now produces errors like:

`logger: unable to start logging for buffer "<net>.slack.com.<channel>.<threadID>": filename "/home/ben/.weechat/logs/<net>.slack.com/$channel/<date>" is already used by another buffer (check your log settings)`

It looks like `$channel` with respect to threads now returns the name of the thread's parent channel, rather than the thread ID.

Ideally it should either be the thread ID on its own, or perhaps `<channel>.<thread>` or similar.

**Comment by auscompgeek** [comment]
Does this work again after #411?

**Comment by ToxicFrog** [comment]
Yep, that fixes it! Thanks :)
