### ISSUE TITLE
Groups and MPDMs should be distinguishable by prefix

### ISSUE THREAD

**Issue by auscompgeek** [wee-slack/wee-slack#410]
It is currently not possible to distinguish between groups (private channels) and multi-person DMs by looking at their buffer name prefix.

I would like to propose the prefixes for groups and MPDMs be configurable, and have the following defaults:
* `&` for groups — on IRC `&` is historically used for server-local channels
* `@` for MPDMs — the web client shows `@name1,name2` in the title when focused

This would also allow for groups to be auto-sorted after public channels, similarly to the official client setting (which funnily enough doesn't apply on mobile; I wonder if we know anyone who could fix this…).

As an alternative to the configurable MPDM name prefix, I would also like to suggest changing the prefix between (space) and `+` whenever anyone in the MPDM is online. (Note that the prefix for MPDM buffers is only used for the short name, which is commonly used in buffers.pl/buflist/the hotlist.)

**Comment by tfheen** [comment]
I like the first part here, having different prefixes. I don't use buflist, so I don't mind the last bit (but i dislike the general usage of + to show when people are online or not)

**Comment by auscompgeek** [comment]
After thinking about this a bit more, I realised there isn't any good reason for making the MPDM prefix configurable. Since it isn't used in the long buffer name (only the short), the only place it's actually shown is in buflist/hotlist.

I think the group prefix should still be configurable though. Some may be relying on the prefix for those to be `#`, and `&` is a fairly arbitrary choice too. The official clients show a padlock, so users may wish to use one of the lock emoji or powerline's read-only glyph there.
