### ISSUE TITLE
Using Reminder Slackbot stops further message from displaying

### ISSUE THREAD

**Issue by ageekymonk** [wee-slack/wee-slack#420]
If we use reminder slackbot, no further messages show up in history after that.

**Comment by kpmeen** [comment]
I'm seing the same behaviour. In the logs it complains about `KeyError u'B01''` whenever it stumbles upon a reminder message from slackbot.

**Comment by kpmeen** [comment]
Re my previous comment, it seems the `u'B01'` is actually the `bot_id` of the slackbot that wrote the reminder.
