### ISSUE TITLE
Open current channel / DM in browser?

### ISSUE THREAD

**Issue by nicksergeant** [wee-slack/wee-slack#422]
Love wee-slack for 95% of my Slack activity, but there are times when I'd like to view the currently-opened-buffer in a browser. As an example, some bots/integrations have complex UIs with buttons. Would be really neat if we could quickly open the current channel/DM in a browser (which would work fine assuming you're logged into Slack via browser as well).

I looked through the code to see if there's an obvious place to stick this, but I'm a bit unfamiliar. I'd love to take a crack at it if someone could point me in the right direction of where I might start. I'll keep poking around regardless.

Thanks!

**Comment by trygveaa** [comment]
Have you tried `/slack openweb`?

**Comment by nicksergeant** [comment]
@trygveaa ah, I didn't realize that existed. However, I just tried it, but nothing happens. No log in the main buffer with an error, either.

**Comment by nicksergeant** [comment]
Looking at the code, I don't see where it would actually be opening a browser: https://github.com/wee-slack/wee-slack/blob/master/wee_slack.py#L3043

**Comment by trygveaa** [comment]
Ah, I guess I've just assumed that it does from the name of the command. Maybe it pointed you a bit in the right direction at least then :)

**Comment by nicksergeant** [comment]
Indeed! Thanks! I ended up fixing this locally with the following:

```@@ -3047,8 +3047,8 @@ def command_openweb(data, current_buffer, args):
          url = "https://{}".format(channel.team.domain)
      else:
          now = SlackTS()
 -        url = "https://{}/archives/{}/p{}000000".format(channel.team.domain, channel.slack_name, now.majorstr())
 -    w.prnt_date_tags(channel.team.channel_buffer, SlackTS().major, "openweb,logger_backlog_end,notify_none", url)
 +        url = "https://{}/messages/{}".format(channel.team.domain, channel.slack_name)
 +    ret = w.prnt_date_tags(current_buffer, SlackTS().major, "openweb,logger_backlog_end,notify_none", url)
  
  
  def command_nodistractions(data, current_buffer, args):```

The main issue I ran into was that the message was not writing to the current buffer, so the iTerm trigger would never fire. When I write to the current buffer, however, iTerm fires the trigger... often, since the string is always there.

I ended up just writing the current team/channel URL to the buffer, and using the `urlgrab` script to open it up manually.

**Comment by nicksergeant** [comment]
I'm going to close this because my use-case is solved (and might help anyone searching for this issue), but my solution doesn't help the project in any way, and it seems that the feature might have been deprecated in the move to 1.0.
