### ISSUE TITLE
Sort buffers alphabetically on startup.

### ISSUE THREAD

**Issue by jemc** [wee-slack/wee-slack#427]
Since upgrading to the completely-rewritten version of wee-slack, my buffers show up in a (seemingly) arbitrary order. In the old version of wee-slack, the behaviour was that buffers were sorted alphabetically on startup, but if you opened new buffers they showed up at the end (as you might expect).

I have about 60-70 buffers open at a time, and not being able to alphabetize them is driving me a little crazy, as I have to scan through all of the buffers before I find the channel or DM conversation that I'm looking for.

Is it possible to restore the old behaviour of sorting buffers alphabetically on startup?

**Comment by trygveaa** [comment]
Do you mean channels within a team, or buffers for multiple teams?

Either way, you can use [autosort.py](https://weechat.org/scripts/source/autosort.py.html/) to sort the buffers.

**Comment by jemc** [comment]
@trygveaa - I'd settle for any system that lets me look for a particular channel in a particular direction from where I am now.

**Comment by tfheen** [comment]
I'm very happy with [go.py](https://weechat.org/scripts/source/go.py.html/), so maybe take a look at that?

**Comment by tfheen** [comment]
That said, I don't have any particular feelings about sorted-vs-unsorted.  If somebody shows up with a reasonable patch, I'm happy to merge.

**Comment by jemc** [comment]
Looks like `autosort.py` works fine for me. I'll close this ticket.
