### ISSUE TITLE
Feature request: add some kind of id or hash to every message for reply (and edit)

### ISSUE THREAD

**Issue by OzQu** [wee-slack/wee-slack#429]
At the moment if you want to reply or edit lines, you have to know how many lines ago it was ("/reply 3 message" edits third newest message on channel). If conversation is fast paced, it is hard to have a chance to reply to correct message. My proposition is that before every message, there could be some kind of small id, which you could refer in your reply command instead of number. User could hide this id with some key binding when not needed and show again when you want to reply. This same id could be used also with editing messages. 

Current way: 
/reply 3 This is reply to third newest message
New way:
/reply a8f3 This is reply to message with id a8f3

**Comment by bzar** [comment]
Maybe also allow emoji reactions: `a8f3+:thumbs_up:`?

**Comment by k4k** [comment]
Hashing messages in this way makes so much more sense than trying to react or reply to a message by specifying the specific number of messages in the past it was. Doing this in even the most modestly busy chat rooms is pretty much impossible.

**Comment by bddenhartog** [comment]
Just starting to use weechat, and wee-slack. This request has been inactive for a while - **if** I get some free time in the next few weeks I'll see if I can tackle this.

**Comment by trygveaa** [comment]
You can now get the hash of a message by using weechats cursor mode or mouse mode. This can be used instead of the number. See the readme for details on how to use this.
