### ISSUE TITLE
IOError on initial installation

### ISSUE THREAD

**Issue by GoodMorningBob** [wee-slack/wee-slack#431]
After following the installation instructions in the ReadMe (copy wee_slack.py to the python/autoload directory) nothing appears to happen when following the /python reload cmd.

Enabling debug results in seeing an error - `IOError(2, 'No such file or directory')`.

No indication of what file is missing is given making it difficult to trouble shoot.

The missing file was the weemoji.json file. After copying this into the .weechat directory the error no longer occurred.

It would be helpful if an extra line could be added to the install instructions detailing the requirement to copy the weemoji.json file as well as the wee_slack.py script.

It would also be useful if the error message included some extra details about which file is missing.

**Comment by trygveaa** [comment]
It now prints this instead, which should be much clearer:

> Couldn't load emoji list: [Errno 2] No such file or directory: u'/home/trygve/.weechat/weemoji.json'

Instructions for enabling emoji completion, which includes copying this file has been added to the readme.
