### ISSUE TITLE
Restore Functionality To List Slack Channels

### ISSUE THREAD

**Issue by jandrusk** [wee-slack/wee-slack#445]
There was a command for listing Slack channels by the command: '/slack channels'. This was removed as part of code refactoring and I would like to see this functionality restored in some way to be able to list Slack channels. The command is still documented on the wee-slack front page on Github.

**Comment by k4k** [comment]
This is a duplicate of https://github.com/wee-slack/wee-slack/issues/379

**Comment by trygveaa** [comment]
This has now been fixed with #449.
