### ISSUE TITLE
weechat seems to connect but cannot join channels

### ISSUE THREAD

**Issue by lplatter** [wee-slack/wee-slack#455]
I am running Ubuntu 16.04 and have weechat 1.4 installed. I followed the slack plugin installation instructions.

After starting weechat, I get a message that I an connected to the right slack team. My member id etc are also displayed correctly.

I cannot do anything. For example, when I try to join a channel I get the message

"irc:command "join" must be executed on irc buffer (server or channel)"

**Comment by trygveaa** [comment]
Which buffer are you trying to run the join command from?

After connecting to Slack, buffers for your channels should be automatically opened. If they don't you can enable debug mode (run `/set plugins.var.python.slack.debug_mode true`), which should open a new buffer with debug messages. Reload wee-slack and see if any errors appear in the debug buffer.

**Comment by lplatter** [comment]
Ok, I didn't appreciate that all buffers are immediately opened. I was also thrown of by the error message that I don't get on an irc server. Thanks for taking the time to look at this.
