### ISSUE TITLE
Flakey connection

### ISSUE THREAD

**Issue by frioux** [wee-slack/wee-slack#459]
I have noticed lately that my wee-slack connection flakes out pretty often; probably tens of times a day.  I know that the browser does it too, but the browser also reconnects fairly quickly, while with wee-slack almost never seems to.  Is there a way to have it use TCP Keepalives to notice when the socket goes stale?  Can we hook into /reconnect -all ?

**Comment by wavded** [comment]
I have noticed this as well.  Seems when my Mac goes to sleep it doesn't reconnect or takes a while to reconnect.

**Comment by frioux** [comment]
It has been happening to me lately *during a conversation while plugged into wired internet.*

**Comment by frioux** [comment]
I think I tracked this down to a flaky ethernet cable.
