### ISSUE TITLE
wee-slack fails to start

### ISSUE THREAD

**Issue by smotti** [wee-slack/wee-slack#466]
Hello, I'm unable to get wee-slack to work on my system. After loading the script the debug output is as follows:

```
12:48:07 | DEBUG: <type 'unicode'>
12:48:07 | DEBUG: Unexpected error: (<type 'exceptions.IOError'>, IOError(2, 'No such file or directory'), <traceback object
         | at 0x10b310a28>)
12:48:07 | DEBUG: RECEIVED FROM QUEUE
12:48:07 | DEBUG: stored context IJLJQR4TFI2Z0UXYQOAGGRAMT0P0A2G3SOFJD9LK https://api.slack.com/api/rtm.start?token=token
12:48:08 | DEBUG: RECEIVED CALLBACK with request of rtm.start id of e6c7ae9e608984e375f944cd0be2c2677af13366 and  code -2 of
         | length 23
```

And there's no output from any of the `/slack [command]` commands . I also don't know if it's possible to actually get the stacktrace for the IOError somehow. Would be great if such thing was also logged.

I installed weechat as follows (python 2 already present, installed via brew too):

```
brew install weechat --with-python --with-perl
```

After that I followed the instructions mentioned in the readme, to install wee-slack.

OS: Mac OS Sierra 10.12.6
Python: Python 2.7.14
WeeChat: 1.9.1

**Comment by trygveaa** [comment]
The IOError is probably caused by not finding `weemoji.json`, so not related to the connection problem (the error message has been improved in #437).

Could you check what the response from `rtm.start` is? I.e. do something like this:

```
diff --git a/wee_slack.py b/wee_slack.py
index 2ac50c0..1c09a6a 100644
--- a/wee_slack.py
+++ b/wee_slack.py
@@ -334,6 +334,8 @@ class EventRouter(object):
         request_metadata = self.retrieve_context(data)
         try:
             dbg("RECEIVED CALLBACK with request of {} id of {} and  code {} of length {}".form
+            if request_metadata.request == 'rtm.start':
+                dbg("Response from rtm.start: {}".format(out))
         except:
             dbg(request_metadata)
             return
```

And then check what is printed on the line after `RECEIVED CALLBACK with request of rtm.start [...]`.

**Comment by smotti** [comment]
@trygveaa, thanks for the quick response. The following is the debug output from that statement:

```
15:20:49 | DEBUG: Response from rmt.start: [44;1H[?1049l [?1l>
```

I myself can't make anything out of it :/.

**Comment by trygveaa** [comment]
Hm, okay. I have heard someone previously having a similar problem, and that was caused by encoding issues. Could you try running `export LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8` in your terminal before starting weechat?

**Comment by smotti** [comment]
@trygveaa thank you very much. That resolved it.
