### ISSUE TITLE
User list does not appear when you /join a new channel

### ISSUE THREAD

**Issue by ToxicFrog** [wee-slack/wee-slack#473]
Reported by K4k on IRC. When you /join a channel, no other users appear. Messages appear normally, and if you reload the plugin the user list appears correctly.

After a bit of bisecting, it looks like one of the commits merged in 37b3c1c broke this, likely 27153da or fa8dc9a -- those modify the way channel joining works to use a new Slack API.

**Comment by ToxicFrog** [comment]
Update: this does not appear to happen consistently. After reloading the plugin the first channel joined has no users listed. The second lists one user (out of hundreds). K4k reports that the second channel joined works fine for them. trygveaa reports that it consistently works.

I wonder if there is some sort of race condition or performance issue with fetching the user list; I'm in the largest slack of us three, and trygveaa is in the smallest.

**Comment by trygveaa** [comment]
Unfortunately, I can't fix this without a way to reproduce it. I've tried reproducing in both large and small teams, and I don't experience this.

If this is still happening, can you give me any more details on when it happens, and in what conditions? For instance, what type of channel is this happening in?

If it is in a private channel, the recent commit ecf30aadb4780d2e83b56dd312402c6ecc53c931 might help.

**Comment by ToxicFrog** [comment]
It seems to have stopped happening sometime in the last two years; I can't reproduce it now either.
