### ISSUE TITLE
Read markers ignored when connection reset

### ISSUE THREAD

**Issue by Craige** [wee-slack/wee-slack#479]
# Use Case
Run wee-slack on a laptop, or a device with non-persistent connection. Chat with teammates for a period, and then disconnect from the network (e.g. suspend laptop).

# Expected Result
Wee-slack will re-connect automatically and notify you of messages since your disconnect.

# Actual Result
Upon re-connecting to the network, wee-slack does not automatically start receiving messages again. When it _does_ start receiving messages again (triggered by scrolling into a buffer, causing it to refresh), it treats every message in every buffer since your last graceful exit (`/exit`) as unread.

Read markers are persisted correctly on graceful `/exit`

# Technical Information
wee-slack@1.99
weechat@1.9.1
OSX@10.12.6

**Comment by Gonzih** [comment]
Yeah I experience exactly the same problem. So far if I suspend/hibernate my laptop for a long perioud of time i just shutdown weechat. Probably I can automate this, but does not feel like a proper solution tbh.

**Comment by trygveaa** [comment]
This should be fixed now, with 71a2e61.
