### ISSUE TITLE
No reconnect on wifi connection loss

### ISSUE THREAD

**Issue by benkoller** [wee-slack/wee-slack#480]
Hi!

first of all thanks for your work on this plugin. However, I'm currently stuck with a bug that "disconnects" weechat whenever I the wifi connection of my Mac is interrupted. As there is no manual reconnect I have to `/python reload slack`, which can be quite annoying on flakey wifi connections. Is there a fix for this that I'm not aware of?

**Comment by k4k** [comment]
Seems like there should be a setting similar to `plugins.var.python.slack.slack_timeout` for this.  I don't know much about the capabilities exposed to plugins with WeeChat but something like `plugins.var.python.slack.slack_autoreconnect` that could be triggered by `plugins.var.python.slack.slack_timeout` seems like ti would work well.

**Comment by toxinu** [comment]
`plugins.var.python.slack.slack_autoreconnect` would be nice to have. Like weechat works with irc server.
