### ISSUE TITLE
wee-slack no longer rejoins channels on reload

### ISSUE THREAD

**Issue by ToxicFrog** [wee-slack/wee-slack#481]
I first observed this today, but I reload wee-slack perhaps once a month, so it could have been broken for a while.

If I reload weeslack (either with `/python reload` or with `/python unload` followed by `/python load`, it doesn't reopen any of the channels I was in except the mandatory-presence channel for each slack. Everything else evaporates and has to be manually `/join`ed.

**Comment by trygveaa** [comment]
Are you still experiencing this? I have never had this issue.
