### ISSUE TITLE
wee-slack broken in Weechat 2.0

### ISSUE THREAD

**Issue by jandrusk** [wee-slack/wee-slack#483]
I upgraded to Weechat 2.0 last night and the wee-slack module would not load any of its components.

**Comment by ToxicFrog** [comment]
Can you paste the error message(s) here?

**Comment by jandrusk** [comment]
There are no messages, just none of my wee-slack servers or channels show up in Weechat. Works up to 1.9.1 I believe. Tried 2.0 last night and nothing shows up until I downgrade.

**Comment by ToxicFrog** [comment]
Try:
```
/set plugins.var.python.slack.debug_level 0
/set plugins.var.python.slack.debug_mode true
/save
```
and then loading the plugin and seeing what it says.

**Comment by nwykes** [comment]
Take a look at the weechat 2.0 release notes and be sure that you've added the additional package needed for python scripts.  The different languages have been split out into separate plugins.

https://weechat.org/files/releasenotes/ReleaseNotes-2.0.html

**Comment by jandrusk** [comment]
Installing the specific Weechat Python package did the trick. Thanks for the reference.

**Comment by jandrusk** [comment]
Installing the specific Weechat Python package did the trick. Thanks for the reference.
