### ISSUE TITLE
How to sort channels by Slack account

### ISSUE THREAD

**Issue by PowerSchill** [wee-slack/wee-slack#484]
I have several Slack accounts setup but since they don't appear to show up as actual servers the channels are being shown below their respective accounts. Is there a way to specify to autosort the ability to sort the channels by Slack account?

**Comment by auscompgeek** [comment]
They should show up as "actual servers" - we try to make the server buffers look as much like IRC server buffers as possible. Any autosorting script that sorts by server should work fine. If not, there's either a bug in wee-slack, or the autosort script.

**Comment by auscompgeek** [comment]
I fixed a related bug in #460 a couple of months ago with Glowing Bear not being able to group wee-slack buffers correctly (we forgot to set a certain buffer variable).

**Comment by PowerSchill** [comment]
Below is my autosort.conf file.

```
[sorting]
case_sensitive = off
replacements = ""
rules = ""
signal_delay = 5
signals = "buffer_opened buffer_merged buffer_unmerged buffer_renamed"
sort_on_config_change = on

[v3]
helpers = "{"core_first": "${if:${buffer.full_name}!=core.weechat}", "irc_raw_last": "${if:${buffer.full_name}==irc.irc_raw}", "irc_last": "${if:${buffer.plugin.name}==irc}", "hashless_name": "${info:autosort_replace,#,,${buffer.name}}", "irc_first": "${if:${buffer.plugin.name}!=irc}", "irc_raw_first": "${if:${buffer.full_name}!=irc.irc_raw}"}"
rules = "["${core_first}", "${irc_last}", "${buffer.plugin.name}", "${irc_raw_first}", "${if:${plugin}==irc?${server}}", "${if:${plugin}==irc?${info:autosort_order,${type},server,*,channel,private}}", "${if:${plugin}==irc?${hashless_name}}", "${buffer.full_name}", "irc.server.*.&* = 0", "irc.server.*.#* = 1", "irc.server.*.\\*status = 2"]"
```

**Comment by trygveaa** [comment]
I don't know the syntax of autosort.conf, but I noticed that there are many references to irc there. Note that wee-slack buffer names start with `python`, not `irc`. E.g. `python.teamname.slack.com.#channelname`. Run `/buffer` to see a list of all the buffer names.

**Comment by PowerSchill** [comment]
Thanks for that I was able to fix it by using the following rules:

```
rules = "[${core_first}", "${irc_last}", "${buffer.plugin.name}", "${irc_raw_first}", "${if:${plugin}==irc?           ${server}}", "${if:${plugin}==irc?${info:autosort_order,${type},server,*,channel,private}}", "${if:${plugin}==irc?    ${hashless_name}}", "${buffer.full_name}","irc.server.*.&* = 0", "irc.server.*.#* = 1", "irc.server.*.\\*status =     2","python.*.&* = 0", "python.*.#* = 1", "python.*.\\*status = 2"]"
```

**Comment by Gonzih** [comment]
Can this configuration be mentioned somewhere in documentation or on a wiki page?
