### ISSUE TITLE
Unable to complete people's usernames in threads

### ISSUE THREAD

**Issue by SevereOverfl0w** [wee-slack/wee-slack#486]
User list should sync up with the parent channel's user list. This would fix @<tab> in threads. Right now, there doesn't appear to be a user list.

**Comment by SevereOverfl0w** [comment]
Would be resolved by https://github.com/wee-slack/wee-slack/pull/490

**Comment by SandyRogers** [comment]
Ah yes, sorry forgot to link this issue on the PR

**Comment by trygveaa** [comment]
The PR mentioned above was merged, so this has been fixed. Note that we don't show the nick list in threads though, which means that you can only complete usernames by starting with @, not bare usernames without @.
