### ISSUE TITLE
Send thread message to parent channel

### ISSUE THREAD

**Issue by SevereOverfl0w** [wee-slack/wee-slack#491]
This is a feature present in the slack for web client & others. Where a message can go to both the thread & parent channel. Very useful for announcing the conclusion of the thread.

**Comment by aereaux** [comment]
How this works is documented here: https://api.slack.com/messaging/sending#threading .  You just need to set a flag in the json message.  I've started implementing it, but I'm not sure what would be the best way to expose this functionality to the user.  Any ideas on that?  Might be able to add a flag to /reply, but I'm not sure what would be the best way would be when one is in a thread buffer.

**Comment by trygveaa** [comment]
@aereaux: I think `/slack broadcast <message>` for thread buffers and `/reply -broadcast <id> <message>` for channel buffers is good.
