### ISSUE TITLE
Use display names when labeling MPDMs

### ISSUE THREAD

**Issue by ToxicFrog** [wee-slack/wee-slack#498]
At the moment, an MPDM is named server-side based on the usernames (not display names) of the participants, of the form `mpdm-user1--user2--user3-1`; we clean up this name a bit for display (drop the prefix and suffix, separate usernames with `|`) but otherwise leave it alone. We should instead create the name client-side based on the display names of the participants.

**Comment by trygveaa** [comment]
Fixed by a648de170db0b974857c669480bd5188a12f8219.
