### ISSUE TITLE
Slack disabling IRC and XMPP - is this plugin affected?

### ISSUE THREAD

**Issue by bruno-** [wee-slack/wee-slack#509]
Hi,

with [slack disabling IRC and XMPP](https://news.ycombinator.com/item?id=16539857) is this plugin affected is some way?

The readme states this plugin uses websockets which is still fine to use and all is good, right?

**Comment by adamgibbins** [comment]
No, wee-slack utilises the APIs, not the gateways, there's zero dependency on the IRC/XMPP gateways.
