### ISSUE TITLE
cannot send messages

### ISSUE THREAD

**Issue by dromer** [wee-slack/wee-slack#510]
When I try to talk in a channel or query I just get:

```
python: stdout/stderr: WS ERROR
```

With latest wee_slack.py from master and weechat-2.0.1-1

**Comment by dromer** [comment]
Problem seemed to have been python version.

**Comment by mattcl** [comment]
@dromer I think I'm having this issue as well. What specifically about the python version was your problem?

**Comment by dromer** [comment]
iirc it was 2.6.x where it had to be 2.7.x
