### ISSUE TITLE
only one line is shown at a time in wee-slack buffers

### ISSUE THREAD

**Issue by SethMilliken** [wee-slack/wee-slack#514]
In all wee-slack buffers, only the most recent line is ever shown. Any new chat activity replaces that one line in the buffer.

It turns out that this problem is caused by having any non-zero number for `weechat.history.max_buffer_lines_minutes`. Setting this value to 0 restores normal buffer behavior.

Not a high-priority issue. Leaving this here primarily to save someone else the time, effort, and aggravation of tracking down the source of this strange symptom.

**Comment by f0o** [comment]
Seeing the same behavior. I use 1440 as `weechat.history.max_buffer_lines_minutes` value to keep memory imprint low on my tiny jumphost. This issue is slightly annoying.

**Comment by demure** [comment]
I'm seeing the same thing as well, changing `weechat.history.max_buffer_lines_minutes` was able to the history. I do hope that this can be corrected >_<
