### ISSUE TITLE
handle dnd_updated_user and groupsmark events

### ISSUE THREAD

**Issue by cleverca22** [wee-slack/wee-slack#521]
ive been getting #497 
* `dnd_updated_user`
*  `groupsmark`
* `channelsmark`
* `desktop_notification`
* `update_thread_state` fires when messages occur in a thread and when a thread becomes seen
* `thread_subscribed` probably a new thread?
* `immark` a checkmark placed on a message
* `dnd_updated_user`
unhandled events on the slack i'm in

**Comment by cleverca22** [comment]
and closing a DM triggers unhandled `conversationsclose`

**Comment by cleverca22** [comment]
how best should these issues be managed?, one per handler, or just keep tossing them into here?

**Comment by trygveaa** [comment]
I don't think we need to handle all events, and having them all in one issue is a bit messy.

Please open issues for missing features instead. One for each feature, describe the feature, and mention the event if you know the event we can use to implement it.
