### ISSUE TITLE
Fully disable URL previews / unfurling

### ISSUE THREAD

**Issue by wohali** [wee-slack/wee-slack#526]
Despite comment #381 wee-slack still displays the full URL previews, even after disabling URL preview in the web client (no effect).

Example:
```
19:10 <wohali> I've added the wee-slack application for our Slack space. This
               lets me connect to Slack from weechat, a text-mode client that I
               prefer. Open source, if you have any concerns, look here:
               https://github.com/wee-slack/wee-slack
19:10 wee-slack/wee-slack
19:10 wee-slack - A WeeChat plugin for http://Slack.com (Slack.com).
      Synchronizes read markers, provides typing notification, search, etc..

```

Ideally, disabling URL previews could be blacklisted/whitelisted, or possibly limited in the number of characters returned. (Example: an in-lined Twitter status is less disruptive than an inlined generic webpage description.

I have a code modification for this I'm working on, and hope to submit a PR soon.

**Comment by sjl** [comment]
I'd also like this.  Here's an example where I sent one line of text with a link and it got turned into half a screen of garbage:

![screenshot of awful unfurl garbage](https://i.imgur.com/ESmCmSs.png)

**Comment by smaslennikov** [comment]
I'm also unclear on how one is to disable link previews entirely. Walls of text can be pretty annoying, if there's no PR open and the feature is absent, I can work on that.

**Comment by trygveaa** [comment]
Yeah, there is no way to disable previews as of now. I agree that getting a full screen of text is pretty useless, so we should limit that in some way.

We could have an option for the number of characters to truncate the preview to, and disable the previews if that's set to 0.

**Comment by pabelanger** [comment]
+1

**Comment by cemeyer** [comment]
@trygveaa line count might be a better metric?  It may be easier for users (admittedly, for me) to estimate visual impact that way than doing the math of line count times current weechat width.

**Comment by trygveaa** [comment]
@cemeyer: I see your point, but then the amount of text will vary based on the window size. So if you resize it, new messages will show more/less than previous messages (I don't want to redraw the messages when the window size changes). I guess that's not necessary an issue though.

**Comment by nriitala** [comment]
+1

**Comment by mkaito** [comment]
I find the main offender is usually github links. I'd be fine if you could blacklist certain domains. Alternatively, I'm also entirely fine disabling previews completely.

**Comment by wavexx** [comment]
@wohali news on the PR ? ;)

I'd be fine disabling the preview entirely. I had to do the same in slack itself. Despite the slack client also truncating the output, it's still too long and makes it impossible to follow a conversation anyway.

**Comment by ta** [comment]
+1 to have an option to disable preview/unfurling entirely.

**Comment by wavexx** [comment]
This is probably the major annoyance I have with wee-slack. Receiving a link to a github PR in slack is horrendous. I'm fine with hard-coding behavior to remove all previews even without a setting!

I was reading the comments from @wohali in the #529 PR.
Why is this not a complete solution?

**Comment by wohali** [comment]
@wavexx It suppresses only part of the content, I need to dig deeper to find all of the changes necessary. Since then I haven't had time to dig into it further.

I'll try and pull this forward on my priority list, as URL embeds have gotten ridiculously huge as of late.

**Comment by ta** [comment]
Does anyone know of a patch/diff in the wild that will disable unfurling entirely? Posting a GitHub source link with some lines highlighted to a channel yields all the highlighted lines in the source - which is kinda odd, as I surely would have pasted the lines directly instead of providing a link, if I wanted to clutter others workspace :)

**Comment by wohali** [comment]
I think I have it now - going to re-open my PR on this.
