### ISSUE TITLE
Won't work in headless mode

### ISSUE THREAD

**Issue by JulienPalard** [wee-slack/wee-slack#539]
I'm using `weechat-headless 2.1-1` from `https://weechat.org/debian stretch/main`.

Problem is at line `j = json.loads(self.reply_buffer[request_metadata.response_id].getvalue())`, the getvalue() returns:

```
WeeChat is running in headless mode (Ctrl-C to quit).\n{"ok":true,"self":{"id":"U…
```

**Comment by trygveaa** [comment]
Using weechat-headless works for me now, so this seems fixed.
