### ISSUE TITLE
AttributeError: 'SlackTeam' object has no attribute 'send_message'

### ISSUE THREAD

**Issue by klausman** [wee-slack/wee-slack#543]
21:50 python: stdout/stderr (slack): Traceback (most recent call last):
21:50 python: stdout/stderr (slack):   File "/home/klausman/.weechat/python/autoload/wee_slack.py", line 119, in wrapper
21:50 python: stdout/stderr (slack):     return f(*decode_from_utf8(args), **decode_from_utf8(kwargs))
21:50 python: stdout/stderr (slack):   File "/home/klausman/.weechat/python/autoload/wee_slack.py", line 676, in buffer_input_callback
21:50 python: stdout/stderr (slack):     channel.send_message(data)
21:50 python: stdout/stderr (slack): AttributeError: 'SlackTeam' object has no attribute 'send_message'

I *think* this may be happening when using `/away`, but I am not 100% sure.

**Comment by trygveaa** [comment]
This happened if you tried to write text in the team buffer. It will now print a proper error instead of a traceback.
