### ISSUE TITLE
Option to De-thread Threads

### ISSUE THREAD

**Issue by tomatosoupcan** [wee-slack/wee-slack#546]
Would it be possible to have an option setting to disable threads entirely? I'm not really feeling opening up a new channel everytime I want to jump into a thread, I'd prefer they just log as regular chat messages, maybe with an indicator that they belong to a thread, instead of being in their own channel.

**Comment by mkaito** [comment]
This would definitely be great to see!

I think prefixing messages with a thread id, so you can `/reply <thread id> <message>` would be nice.

**Comment by huyz** [comment]
Yes, I like the hybrid model of Mattermost: you can open a separate window to look at just the thread, but the main window still has threaded messages, with a "threaded" indicator like a bar `| `.
