### ISSUE TITLE
Add wee-slack to the Slack App directory

### ISSUE THREAD

**Issue by royger** [wee-slack/wee-slack#560]
Hello,

Currently wee-slack is not in the Slack app directory, which makes it hard for admins to actually allow it's usage. Could we get wee-slack added to the official Slack App repo?

Thanks, Roger.

**Comment by iKarith** [comment]
In order to do that, Slack is probably going to insist that the auth process become better handled.  Unfortunately I haven't got a brilliant suggestion for what to do about that just now.  But I'd like to see it in the app directory.  Some slacks are pretty permissive.  Some are pretty locked down.  I'm in both.

**Comment by auscompgeek** [comment]
#503 is probably a step needed before this would actually happen.

**Comment by matthijskooijman** [comment]
There is a submission checklist, which isn't explicit about this kind of situation (but also seems to be geared towards web applications running on a central server, rather than code running on users' own systems).

https://api.slack.com/docs/slack-apps-checklist

Anothe issue that might pop up is that the application OAuth client secret is actually public in the source code, which might violate some condition somewhere...

**Comment by iKarith** [comment]
It really would be good if someone involved with slack could be approached about the problem.  I don't know that they will be terrible responsive if approached in the usual manner.  "Your request is very important to us, and we'll get back to you just as soon as we finish that dark mode we've said we were open to back in 2014…"

**Comment by auscompgeek** [comment]
@rawdigits Assuming we eventually stop bikeshedding #503, would there be any problem with publishing on the app directory?

**Comment by trygveaa** [comment]
Hm, I just noticed that the [FAQ](https://api.slack.com/faq) states:

> The client scope is useful but overly broad and not suitable for an app distributed on the App Directory.

This seems like a deal breaker, as we probably need that scope to act as a full client. I haven't checked though, so maybe we can get what we need by specifying lots of other scopes (if that's any better). Or we could try to ask Slack if it's okay for our use case.

**Comment by absolutejam** [comment]
Sorry to interject - Does this mean that WeeSlack does in fact support using OAuth tokens as well as legacy tokens? I was trying to find the answer but it looks like this issue hints at that?

**Comment by trygveaa** [comment]
@absolutejam: Yes, it supports oauth tokens. See https://github.com/wee-slack/wee-slack#4-add-your-slack-api-keys

**Comment by absolutejam** [comment]
@trygveaa Thanks for clarifying. Are the scopes documented anywhere? Getting some pushback in getting this added, but I can't bare enough electron app! Thanks.

**Comment by trygveaa** [comment]
@absolutejam: Since it's a full client for one user, it needs permission to act as that user. That means we require the `client` scope. It's mentioned at https://api.slack.com/docs/oauth-scopes, under "Special scopes".

**Comment by madchap** [comment]
I was wondering if this request was getting any chance of being achieved? Maybe some things would have made it a bit easier 1 year later?

Cheers.

**Comment by auscompgeek** [comment]
Might be worth noting that IRCCloud isn't listed in the app directory either.

**Comment by trygveaa** [comment]
I'm pretty sure it will never be possible to submit wee-slack to the App directory. As mentioned above, it requires the `client` scope, and the documentation states that apps which requires this isn't suitable for the app directory. There is nothing we can do about this and I doubt it will change. I've talked with Slack about a couple of API issues, and they aren't really interested in catering for third party clients anymore. I haven't talked with them about adding wee-slack to the App directory, but I'm pretty sure there's no point.

As an alternative for people that can't install the app in Slack, I've documented how to pull a token out of the web client [in the readme](https://github.com/wee-slack/wee-slack#get-a-session-token). This token can be used without any approval from admins. Note however that the token can't be revoked, so be careful not to misplace it, and also note that it's not officially supported and may stop working at any time (but I've been using one for a long time without any issues).

**Comment by drselump14** [comment]
Hi guys, does it mean that there is no way for admin to install the 'wee-slack` app? I've requested the admin of channel to install the app, but it only redirect page to https://raw.githubusercontent.com/rawdigits/wee-slack/master/README.md

**Comment by trygveaa** [comment]
As far as I know admins can still add the app when the team is configured to only allow apps from the app directory, even if wee-slack is not in it. They will have to go to https://my.slack.com/apps/A1HSZ9V8E-wee-slack and click the "Approve" button as shown in the image below (not the "Add to Slack" button).

![image](https://user-images.githubusercontent.com/601966/86096607-c7125080-bab3-11ea-9e27-339d0cb086f2.png)

**Comment by de-vri-es** [comment]
I don't know if this used to work, but if you click the button "Add to Slack" now, it just links to the README.

**Comment by trygveaa** [comment]
It's always been like that (or at least for a very long time). Unfortunately, I don't have access to the Slack app that is used, so I can't change it. You will have to do what I wrote in the previous comment instead (or preferably [use a session token](https://github.com/wee-slack/wee-slack?tab=readme-ov-file#get-a-session-token) instead of the app).
