### ISSUE TITLE
Connection seems to die after some time

### ISSUE THREAD

**Issue by neverfox** [wee-slack/wee-slack#561]
I have noticed that after some time (usually after I wake from sleep in the mornings but also intermittently) that I stop getting updates on slack channels and I cannot send messages (they just silently fail). I notice because I get the alerts on my Android app or in the Slack UI, which I sometimes open. I have to restart weechat to get things working again.

Are there any known causes of this I might be able to address?

**Comment by tomasv** [comment]
I'm encountering this as well. Waking up from sleep on a Macbook Pro freezes the connection: no updates come at all.

My workaround is to run `/script reload slack`.

**Comment by mattiz** [comment]
I experience the same issue after waking my computer up from sleep. I run Ubuntu 16.04 on a Thinkpad T460s.

**Comment by guyfedwards** [comment]
I get this on OSX and Arch, sleeping results in most often connection dropping and having to restart weechat to reconnect.

**Comment by lnikkila** [comment]
For some reason `/python reload slack` doesn’t always work for me, however `/script reload slack` seems to work.
