### ISSUE TITLE
Respect short_name changes

### ISSUE THREAD

**Issue by robertmeta** [wee-slack/wee-slack#563]
If you like to change short_name on channels, either directly using the /buffer set short_name dogfood/general or via /buffer_autoset -- either way, wee-slack doesn't respect the change made. 

I think that when updating the typing notification it doesn't respect the new short name so instead of going ">dogfood/general" then "dogfood/general" it goes to its internal name ">general" "#general".  

I will look at submitting a patch to fix this behavior.

**Comment by auscompgeek** [comment]
One workaround could be to disable `plugins.var.python.slack.channel_name_typing_indicator`.

**Comment by robertmeta** [comment]
@auscompgeek that work around does work -- hence confirming the source of the bug.

**Comment by skrzyp** [comment]
I can confirm - changed short_name is restored on some other events other than typing notification too.

I'm using `short_name`s on `buflist` to maintain its small size, some abbrevs are also very handy with `go.py` plugin to jump between bufers with few taps (I have about 300+ buffers)

**Comment by wavexx** [comment]
I had the same issue today. I have a channel which is created in slack with the group names of 5 people, becoming over 50 chars in length, making the buflist unusable :/

Having the ability to set a short name and still retain typing indicators would be nice.
Instinctively I tried to use "/label" that normally works on threads. Maybe it should work on channels as well?

**Comment by trygveaa** [comment]
`/label` now works for channels and groups. If you set short_name, the label will be set to that name so it's preserved when typing notices are used.

@wavexx: This fixes your issue, but you should also know that you can set a max size for the buflist with `weechat.bar.buflist.size_max` so weechat truncates longer names.

**Comment by wavexx** [comment]
Didn't know about ``weechat.bar.buflist.size_max``, however when the buflist is put at the top, it sets the number of lines so channels names can still get very long (limiting the number of columns). Is there a way around that?

**Comment by trygveaa** [comment]
You would do that by truncating the name explicitly. So for instance:

```
/set buflist.format.name "${cut:10,+,${name}}"
```

See `/help eval` for info about what kind of expressions you can use in such config options.

**Comment by wavexx** [comment]
Thanks again, great tip!

**Comment by mhoran** [comment]
I had been using `plugins.var.python.slack.channel_name_typing_indicator = false` and `buffer_autoset` to rename channels before this change, but since this change that no longer works. I tried using `/label`, which works great, but when I reload this plugin or weechat, the label is not persisted.

The README states that `/label` does not persist. So how do I get the behavior I had before with `buffer_autoset` with this change?

**Comment by mhoran** [comment]
My mistake; turns out this was due to a73203a3ec5d5ee0d2ca2e33b13aa9537a301cef. It would be nice to know how to persist `/label` though, so I could turn the typing indicator back on.

**Comment by trygveaa** [comment]
@mhoran: I did some further changes. Now you should be able to use buffer_autoset to set name and/or short_name, and the name will be kept when having the typing indicators enabled.

wee-slack doesn't currently have any way to persist things (except for the config options), so I don't think I will add persisting of `/label`, but since you can use buffer_autoset it shouldn't be necessary.

**Comment by mhoran** [comment]
> @mhoran: I did some further changes. Now you should be able to use buffer_autoset to set name and/or short_name, and the name will be kept when having the typing indicators enabled.

This works great, thanks!

**Comment by dschrempf** [comment]
Hi, sorry for bumping this thread. When I set the `short_name` of a buffer, the typing indicator (and the + sign for people being online) is removed from the buffer name in the buflist. Is this behavior expected, or is this a bug?

Further, if I set the buffer `name`, the buffer gets sorted before any other buffers using `autosort`. Any idea why this is the case?

**Comment by trygveaa** [comment]
@dschrempf: Sorry, very late answer here, forgot to answer when I first saw it and noticed it again now. This should probably be documented, but the current behavior is that if you set a `short_name` starting with a space the space will be replaced with the presence indicator. If it doesn't start with a space the presence won't be shown. The typing indicator should always be shown when someone is typing if you have `channel_name_typing_indicator` on and the channel isn't muted though. It should replace the first character of the `short_name` regardless of what it's set to. If it doesn't behave like this for you, you can file a new issue for it.

You can also use the `/label` command to set just the name and keep the prefix and typing indicator exactly like it's with the default name.

> Further, if I set the buffer `name`, the buffer gets sorted before any other buffers using `autosort`. Any idea why this is the case?

Are you removing the `slack.<team>` prefix from the name? That could cause it. You should keep it. I'm not sure changing the `name` at all is really supported though.
