### ISSUE TITLE
Using wee-slack with Weechat's IRC relay

### ISSUE THREAD

**Issue by mrrcollins** [wee-slack/wee-slack#564]
Is there anyway to use wee-slack with Weechat's built in IRC relay?

It could be a limitation of Weechat's relay capability, my wee-slack connection doesn't show up in Glowing Bear. (I stand corrected, wee-slack does show up in Glowing Bear.)

**Comment by bradyt** [comment]
@mrrcollins from https://weechat.org/files/doc/stable/weechat_user.en.html#relay_plugin

> The Relay plugin is used to relay data via network, using different protocols:
> 
> - irc: IRC proxy: used to share connections to IRC servers with one or many other IRC clients
> - weechat: protocol used by remote interfaces to display and interact with WeeChat, for example:

I read this as, irc relay will only work with IRC servers, and weechat relay will only work with Weechat clients.

**Comment by paddatrapper** [comment]
I use wee-slack with weechat-android without issue. It shows up fine there. I'll check if I can see it in glowing bear.

**Comment by auscompgeek** [comment]
weechat-android is not an IRC client; it is a weechat relay client.

**Comment by paddatrapper** [comment]
I can view wee-slack connections in Glowing Bear - both the command buffers and actual channels

**Comment by trygveaa** [comment]
As mentioned, the irc relay only forwards irc commands. Since wee-slack doesn't use irc commands, that doesn't work. However, it should work fine with the weechat relay. Some features, like viewing message edits isn't working with the relay, but that's a limitation of the relay protocol.
