### ISSUE TITLE
Automatically subscribe to threads

### ISSUE THREAD

**Issue by Zumochi** [wee-slack/wee-slack#572]
Hi, I'm trying to come up with a solution that automatically logs all Slack chats, and this includes threads.

Would it be possible to automatically subscribe to all threads of all channels I'm in?

**Comment by max-arnold** [comment]
Find the `subprocess_thread_message()` function and change one line:

```diff
             channel.change_message(parent_ts)

             text = message.render()
-            # channel.buffer_prnt(message.sender, text, message.ts, **kwargs)
+            channel.buffer_prnt(message.sender, text, message.ts)
             if parent_message.thread_channel:
                 parent_message.thread_channel.buffer_prnt(message.sender, text, message.ts)
```

**Comment by trygveaa** [comment]
This is now supported by setting `auto_open_threads = true` (implemented in #617).

**Comment by max-arnold** [comment]
@trygveaa Thanks a lot!

**Comment by max-arnold** [comment]
@trygveaa I upgraded to the latest revision today (c8dfe1030974b7d34dbcbc805a3e1cf02d9073ee), set `python.slack.auto_open_threads = "true"` in my `plugins.conf` and I do not see any threads being logged.

Any ideas?
