### ISSUE TITLE
Feature Request: View Status Outside Of Conversation With Self

### ISSUE THREAD

**Issue by Noah-Huppert** [wee-slack/wee-slack#574]
It would be nice if there was an option to view your Slack status besides opening the Slack conversation with yourself (Where your Slack status is displayed at the top of Weechat).  

Ideas:

- `/slack status get`
- Display in the bottom bar on the right hand side

PS: Thank you so much for this plugin, it is amazing and I ❤️ it

**Comment by trygveaa** [comment]
The `/slack status` command now prints the current status if no arguments are given. The command for unsetting the status is changed to `/slack status -delete` (matches the `/topic` command).
