### ISSUE TITLE
Hard-coded client_secret

### ISSUE THREAD

**Issue by funk-yourself** [wee-slack/wee-slack#577]
I see that client_secret, along with client_id, is hard-coded [here](https://github.com/wee-slack/wee-slack/blob/89864b5ab952b426e77cd76cc0941035335063df/wee_slack.py#L3104).
Is it safe to do like this? I'd like to use the same approach in my own app, but I'm a bit confused because Slack discourages publishing client secret publicly.

**Comment by auscompgeek** [comment]
We aren't a webapp, so there isn't any other way of doing this.
