### ISSUE TITLE
Allow Space Between "#+" and Emoji Name When Adding Reactions So Auto Complete Works

### ISSUE THREAD

**Issue by Noah-Huppert** [wee-slack/wee-slack#580]
Currently the syntax for adding a reaction is `#+:emoji_name:`.  

If one wants to use emoji name auto completion when adding a reaction they must first add a space between`#+` and `:emoji_name:` for emoji names to tab complete.  
Then they must delete the space between `#+` and `:emoji_name:` for the reaction to actually be added.  

Current user flow:  
1. `#+ :emoji_<TAB>`  
2. `#+ :emoji_name`  
3. `#+<DELETE>:emoji_name:`  
4. `#+:emoji_name:`  
5. Send

It would be nice if the syntax for adding a reaction allowed a space between the two parts (ex: `#+ :emoji_name:`) so emoji name completion could be used more naturally.  

Proposed reaction syntax: `#+:emoji_name:` or `#+ :emoji_name:`.  

Proposed user flow:  
1. `#+ :emoji_<TAB>`  
2. `#+ :emoji_name`  
5. Send

**Comment by auscompgeek** [comment]
Well, the real fix would be to have the autocomplete take into account the `n+` prefix when at the beginning of a line.

**Comment by trygveaa** [comment]
Completion now works when you have text in front of the colon.
