### ISSUE TITLE
Huge amount of crash logs (80+ gb)

### ISSUE THREAD

**Issue by will** [wee-slack/wee-slack#584]
I'm not sure if this is more appropriate to report here or somewhere with weechat itself, however I only use weechat for slack.

```
.weechat ➤ du -hs
 83G	.
.weechat ➤ ls | grep weechat_crash | wc -l
   11549
.weechat ➤ rm weechat_crash_*
zsh: argument list too long: rm
.weechat ➤ ls | grep weechat_crash | xargs rm
.weechat ➤ du -hs
 19M	.
```
I know that it hasn't actually crashed eleven thousand times, and unfortunately I didn't grab any of them to look at what they were.

I'm mostly opening this because I couldn't find anywhere online of anyone talking about weechat producing such a high amount of crash dumps, but I may not have figured out the right keywords to search for. Feel free to close this if it doesn't have anything to do with the plugin.

**Comment by ylorn** [comment]
I can reproduce this as well. I left my mac open during the weekend and when I came back there is a warning said that there is no space left. And I found there are 400+G weechat crash logs generated.

**Comment by trygveaa** [comment]
@ylorn: What did the logs contain?

**Comment by ylorn** [comment]
Most of the logs contains only 398 bytes with following content:

> 
> ======= WeeChat backtrace =======
> (written by WeeChat 2.4, compiled on Feb 17 2019 17:56:51)
> 004  3   ???                                 0x0000000000000008 0x0 + 8
> ======= End of  backtrace =======
> ======= WeeChat backtrace =======
> (written by WeeChat 2.4, compiled on Feb 17 2019 17:56:51)
> 004  3   ???                                 0x0000000000000008 0x0 + 8
> ======= End of  backtrace =======
> 

And as I observed, every time each channel successfully retrieved the chat history, a crash log file with the preceding content will be generated. Besides all these small log files, another huge-sized, continuously-growing crash log file is generated as well. It seems that it contains all the debug info dumped from weechat, and 100 lines of some channel's conversation history. So I guess, every time the wee-slack retrieved the history for a certain channel, a 398 bytes crash log file is generated, and 100 lines of that channel history will be appended to the huge log file with all other debug info dumped from weechat.

**Comment by trygveaa** [comment]
Unfortunately, I can't do anything about this without a way to reproduce, as I have no idea what could cause it, and I have never experienced it myself.

Anyways, the crash logs are generated by WeeChat, so I would say the issue lies there.
