### ISSUE TITLE
In Code Blocks: Does Not Display 2 Consecutive Stars Separated By A Space

### ISSUE THREAD

**Issue by Noah-Huppert** [wee-slack/wee-slack#585]
In code blocks it looks like Wee Slack does not display stars (`*`) if there are 2 stars in a row separated by spaces.

I believe this is because stars are used to indicate bolding in messages. And Wee Slack forgets to turn off this feature in code blocks (Between grave marks).  

Here is what a series of test messages look like in the official Slack client:
![screen shot 2018-05-24 at 11 03 43 am](https://user-images.githubusercontent.com/3323504/40494143-276a4a66-5f42-11e8-9987-1bfe2963bc5b.png)

And here are the same messages in the WeeChat client using Wee Slack:
![screen shot 2018-05-24 at 11 03 24 am](https://user-images.githubusercontent.com/3323504/40494151-2b2007fe-5f42-11e8-9ce6-eed63ccb1704.png)

**Comment by yeled** [comment]
This is to do with [render_formatting()](https://github.com/wee-slack/wee-slack/blob/master/wee_slack.py#L2775)

**Comment by auscompgeek** [comment]
#567 will help with this, but long term we'd want to ensure that code blocks don't get any formatting whatsoever.

**Comment by auscompgeek** [comment]
Actually, this is a duplicate of #566.

**Comment by Noah-Huppert** [comment]
Closing b/c duplicate
