### ISSUE TITLE
#foo is changed to #DlKAJLKDJ (foo)

### ISSUE THREAD

**Issue by wolfsage** [wee-slack/wee-slack#587]
If I type `#foo` in wee-slack, it gets changed to `#D1342342 (foo)` (for example).

Viewed in slack, it provides a link to directly message the user `foo`.

However, if I type `#foo` in slack itself, this doesn't happen!

It'd be great if wee-slack didn't mess with things this way

**Comment by antoyo** [comment]
I have the same issue.
`@username` gets rewritten to `@WAVTLJH40` or something.
If I restart weechat, the correct name is written, though.

**Comment by antoyo** [comment]
Any news on this issue?

**Comment by trygveaa** [comment]
@antoyo: That doesn't sound like the same issue. Please test again with the newest master, and if it's still happens open a new issue with some more details.

**Comment by trygveaa** [comment]
@antoyo: Do you get any errors? Have tried [enabling debug mode](https://github.com/wee-slack/wee-slack#development) and checking if you get any errors in the core or debug buffer?
