### ISSUE TITLE
ImportError: No module named 'sha'

### ISSUE THREAD

**Issue by d3xt3r01** [wee-slack/wee-slack#598]
So for some reason, after messing a little bit with my gentoo system ... I get this:
```
07:42:44  weechat     | python: stdout/stderr:     print "WS ERROR"
07:42:44  weechat     | python: stdout/stderr:                    ^
07:42:44  weechat     | python: stdout/stderr: SyntaxError: Missing parentheses in call to 'print'
```
Adding parantheses to the print statement yells
```
07:44:03  weechat     | python: stdout/stderr:     import sha
07:44:03  weechat     | python: stdout/stderr: ImportError: No module named 'sha'
```
Which seems to be deprecated since 2.5 https://docs.python.org/2/library/sha.html

**Comment by trygveaa** [comment]
You're trying to run the plugin using python 3. This is not supported unfortunately, you have to use python 2.

**Comment by ypuzikov** [comment]
Is there any progress on this issue? It seems that weechat is now built with python3 by default (mentioned in https://github.com/wee-slack/wee-slack/pull/331)

**Comment by trygveaa** [comment]
Yes, I've actually been working on this lately, and will push the changes shortly.

Where is weechat built with python 3 by default now? As far as I know, it shouldn't switch to python 3 before July 1.

**Comment by ypuzikov** [comment]
I have OpenSUSE Leap 15.0 and installed weechat using Yast. Followed the instructions of installing wee-slack and got this sha error. In weechat, running 
```
\python version
``` 
gives "python: 3.6.5"

And the dependencies of weechat in Yast include libpython3.6m.so.1.0()(64bit).

**Comment by trygveaa** [comment]
Ah, okay. I've pushed a branch [`python3`](https://github.com/wee-slack/wee-slack/tree/python3), which should be compatible with python 3. I just want to test it a bit more before merging to master. Please report if you experience any issues with it.

**Comment by ypuzikov** [comment]
Thank you, it works! \(^^)/

**Comment by ainola** [comment]
It's worth noting that Arch Linux is actively [removing](https://www.archlinux.org/todo/die-python2-die/) python 2 packages from repositories. I've [submitted](https://bugs.archlinux.org/task/62348) a task to the maintainer of Arch's Weechat to have him start building with Python 3.

**Comment by trygveaa** [comment]
@ainola: Thanks for the info. wee-slack supports python 3 now, so that shouldn't be a problem. I haven't updated weechat's script repo with the newest version which supports python 3 yet though.
