### ISSUE TITLE
Not seeing image links suddenly

### ISSUE THREAD

**Issue by guyfedwards** [wee-slack/wee-slack#600]
This started a couple of days ago, I no longer see a slack upload link, just a blank message:
![image](https://user-images.githubusercontent.com/1794071/43209915-bb146224-9025-11e8-9105-435d2fd489a6.png)
That blank is an image upload in the slack application. Wondering if they have changed the format of response/link.

**Comment by smaslennikov** [comment]
Same started happening for me a few days ago as well.

**Comment by PaulOstazeski** [comment]
#599 Fixes this problem for me

**Comment by leofiore** [comment]
can confirm #599 fixed the issue for me too

**Comment by guyfedwards** [comment]
Fixed in https://github.com/wee-slack/wee-slack/commit/2d40eac3ddf889d27ff68a0d501484efc4faf45d
