### ISSUE TITLE
Direct messages disaapering

### ISSUE THREAD

**Issue by mberge-rs** [wee-slack/wee-slack#602]
When I log into weechat and connect to slack with the wee-slack plugin all of my open direct messages I have in slack are closed for some reason. In both slack and weechat. I believe these should stay open.

**Comment by trygveaa** [comment]
Do you have any other plugins/scripts which auto closes buffers or something?

When you connect with wee-slack it should open all the direct messages that are open in the web client, and not close any for you. If you close a direct message buffer in weechat, the direct message in Slack will be closed too though.

**Comment by mberge-rs** [comment]
I have no other plugins installed in weechat at all.

________________________________

**Comment by trygveaa** [comment]
Are you still experiencing this issue? If you're still around, can you try this patch and report what is printed to the core buffer?

```
diff --git a/wee_slack.py b/wee_slack.py
index 1bef836..2e2f54e 100644
--- a/wee_slack.py
+++ b/wee_slack.py
@@ -1643,6 +1643,8 @@ class SlackChannel(SlackChannelCommon):
         self.channel_buffer = None
         self.active = False
         if update_remote and not self.eventrouter.shutting_down:
+            print('closing buffer {}:'.format(self.slack_name))
+            traceback.print_stack()
             s = SlackRequest(self.team.token, SLACK_API_TRANSLATOR[self.type]["leave"], {"channel": self.identifier}, team_hash=self.team.team_hash, channel_identifier=self.identifier)
             self.eventrouter.receive(s)
 
```
