### ISSUE TITLE
Cannot mark buffer as read with /input set_unread_current_buffer

### ISSUE THREAD

**Issue by KibaFox** [wee-slack/wee-slack#603]
I'm using the latest from master `2d40eac3ddf889d27ff68a0d501484efc4faf45d` and it appears that I cannot set the current buffer as read with `/input set_unread_current_buffer`.  I noticed the behavior of !319 and realized that the intended bahavior is to explicitly set whether you've read content or not.

I can set all buffers in Slack as read with `/input set_unread`, but I'm in a lot of channels at work and I'd like to be able to do this on a per buffer basis.

When I attempt to do `/input set_unread_current_buffer`, the unread line does not advance/disappear and the channel is still highlighted in the list.

**Comment by trygveaa** [comment]
This works fine for me. Can you check if it works in IRC buffers for you?

> realized that the intended bahavior is to explicitly set whether you've read content or not.

Well, you don't have to set it explicitly unless you don't want to change buffers. It will be marked as read when you change to another buffer.

**Comment by KibaFox** [comment]
Odd.  I've been testing this today and it works.  I can either move between buffers or do `/input set_unread_current_buffer` to move the read line.

When I tested it before, it wasn't.  I basically had to do `ctrl+S` + `ctrl+U` or `/input set_unread` to get things marked as read.

I'm closing this.  Hopefully it was just a fluke on my end.
