### ISSUE TITLE
wee-slack started repeating my messages twice

### ISSUE THREAD

**Issue by ieure** [wee-slack/wee-slack#606]
Probably Slack did something terrible, but all of a sudden, in the middle of a conversation, I started getting any message I sent echoed back to me twice instead of only once.

I restarted and nothing changed.

**Comment by sjl** [comment]
I'm also seeing this.  Every message I send appears duplicated in the buffer.  It happens in both in normal channels and in DMs.  Messages from other people are fine.

**Comment by maxres** [comment]
This might be slack, because I'm also seeing this.

**Comment by ieure** [comment]
> This might be slack, because I'm also seeing this.

Agree that something likely changed on their backend.  Their web client doesn't exhibit this behavior, only wee-slack.

**Comment by brett** [comment]
Also seeing this.

**Comment by 2Shirt** [comment]
Same

**Comment by airencracken** [comment]
Also started seeing this unfortunate behavior today. Cranked up the debugging log level, but not seeing anything super obvious.

**Comment by ieure** [comment]
This stopped happening within the last few minutes.

I hate Slack.

**Comment by sjl** [comment]
@ieure it stopped happening because Slack is down https://status.slack.com/

**Comment by ieure** [comment]
> @ieure it stopped happening because Slack is down https://status.slack.com/

I *hate* Slack.

**Comment by grumps** [comment]
https://github.com/grumps/wee-slack/tree/issue-606-doubling-messages

- [ ] channel messages
- [ ] `reply 1 foobar` doesn't double message
- [ ] thread buffers don't double message

I've forked and added a small fix that prevents doubling of messages in channels. 

Still working on thread messages and reply messages.  Not sure when I'll get to that. I've not touched this code base before and just trying to catch up with it is a bit steep. 

I've had some troubles tracking down where/what is inserting into the `channel.messages` ordered dict and causing a buffer print. I'm also not sure if my handling for the main channels is great. It'd be nice if there were one place to prevent all of this. If someone has some tips, i'll gladly take them.

**Comment by hkdd** [comment]
Thanks Grumps, that resolve the issue for me.

**Comment by grumps** [comment]
@hkdd  I think this is rather incomplete.. just discovered edits wont change update the message.

**Comment by trygveaa** [comment]
This should now be fixed. Please write a comment if you still encounter any issues.

**Comment by hkdd** [comment]
Thanks everyone, I appreciate all the hard work.  I'm a huge fan of wee-slack.

**Comment by jaywilliams** [comment]
Wee-slack makes Slack bearable. Thanks so much!

**Comment by wohali** [comment]
@trygveaa Since applying the patch for this issue, private messages to me are going missing. I see the buffer light up as having new messages, but when I change to the buffer, the message is not there. Neither is the message in the logfile weechat writes to disk.

**Comment by trygveaa** [comment]
@joannac-: Hm, are you sure you are running the newest version from master? If so, can you enable debug mode, set level to 0 (see https://github.com/wee-slack/wee-slack#development) and paste the output from the debug buffer when you're posting a message? Make sure to sensor out the token.

@wohali: By applying the patch, do you mean the patch mentioned above, or are you running master?

**Comment by wohali** [comment]
@trygveaa Thanks, that was the exact issue! I'll update (once I update my patches)

**Comment by onewheelskyward** [comment]
It happens for me in the IRC client as well.
