### ISSUE TITLE
Slack echoing text

### ISSUE THREAD

**Issue by THE-Alan-Hicks** [wee-slack/wee-slack#607]
Howdy,

I noticed this issue this morning (August 17, 2018 around 9:00 a.m. EDT). I believe this is due to a change in how slack processes text sent to it by wee-slack. Whenever I send something through wee-slack, the text is echoed twice in weechat. Here's an example:

  09:23:01 Alan_Hicks | Testing from wee-slack.
  09:23:01 Alan_Hicks | Testing from wee-slack.

However, everything appears normal in the slack app/website (i.e. the text only appears once). Furthermore, text sent by other users isn't echoed and text that I send from the slack app/website also isn't echoed. Example:

  09:23:01 Alan_Hicks | Testing from wee-slack.
  09:23:01 Alan_Hicks | Testing from wee-slack.
  09:24:41 Alan_Hicks | Testing from slack app/website.
  09:24:50 Alan_Hicks | Testing from wee-slack again.
  09:24:50 Alan_Hicks | Testing from wee-slack again.

I verified this with two different instances of weechat/wee-slack on two different computers, so I do not believe this is a local configuration issue (but I acknowledge that it's a possibility). Thanks for any assistance or further information you can give.

**Comment by deathmaz** [comment]
Are you using the latest version of wee-slack, the issue was already fixed.

**Comment by THE-Alan-Hicks** [comment]
/me hangs head in shame.

I feel like such an idiot. I only checked the releases tab; I didn't look in HEAD. The latest wee_slack.py script resolves all difficulties. Mea culpa.
