### ISSUE TITLE
Posting through wee-slack causes the post to appear twice in wee-slack (normal Slack shows it only once)

### ISSUE THREAD

**Issue by StoppingBuck** [wee-slack/wee-slack#610]
For some weird reason, if I post something in wee-slack, my post shows up twice, even though if I look at the same post in ordinary Slack it was only posted once. So it's not _actually_ double-posting, but only shows it that way in wee-slack.

I run weechat in Arch Linux / KDE / Konsole / zsh / tmux

**Comment by StoppingBuck** [comment]
![sepctacle2](https://user-images.githubusercontent.com/8426548/44327959-8cbfdd00-a460-11e8-80b6-d5fbe54a7d18.png)
![spectacle](https://user-images.githubusercontent.com/8426548/44327960-8cbfdd00-a460-11e8-8d3e-dd404dfe42dc.png)
Attaching what a (censored) post looks like in wee-slack vs. the same post in real Slack.

**Comment by deathmaz** [comment]
Update your wee-slack to the latest master, the issue was fixed

**Comment by StoppingBuck** [comment]
Fastest answer I've ever seen! Thanks, will do
