### ISSUE TITLE
recent changes broke search and replace and name no longer showing

### ISSUE THREAD

**Issue by nipsy** [wee-slack/wee-slack#612]
I can't seem to get s/foo/bar/ to work anymore after the last couple days of updates.

And unrelated to that, and possibly intentional, I no longer see my nick appearing is the display buffer after my message is posted.  I see just the time stamp, with the separator, and my message.  But no nick/name.

**Comment by mhoran** [comment]
I'm seeing the latter issue as well.

**Comment by trygveaa** [comment]
Sorry, I managed to introduce this bug in one of the commits yesterday. It's fixed now, thanks for the bug report.
