### ISSUE TITLE
Connects to Slack servers even when `-a` / `--no-connect` CLI argument provided

### ISSUE THREAD

**Issue by qguv** [wee-slack/wee-slack#613]
```
  -a, --no-connect         disable auto-connect to servers at startup
```

The wee-slack plugin will still connect to configured Slack servers even when the above option is given on the CLI. If possible, wee-slack should check and respect this option.

**Comment by trygveaa** [comment]
Currently wee-slack doesn't have a concept of manually connecting and disconnecting to teams. When the script is loaded, you are always connected (or connecting) to all the teams.

While this is of course possible to change, I'm not sure it's worth the effort (or I at least have lots of other things I'd rather prioritize).

Instead, as a workaround, I would recommend removing the script from autoload when you don't want it to auto-connect.

**Comment by yardenac** [comment]
You don't need to manually connect or disconnect from anything. It's just a one-time startup check. If --no-connect was passed, the script should just exit. That'd be better than the current behavior.

**Comment by trygveaa** [comment]
Now the script won't connect to the teams if WeeChat is started with `--no-connect`. Reload the script to connect to the teams.

Note that you need WeeChat version 2.8 or later, since WeeChat didn't have support for checking `--no-connect` in scripts before this.
