### ISSUE TITLE
Own nick not showing

### ISSUE THREAD

**Issue by isene** [wee-slack/wee-slack#614]
Backdrop: Weechat 2.2 running on Ubuntu 16.04 server in tmux, using ssh to connect from laptop. Wee-slack is latest git. Running colorize_nicks as script in weechat.

Issue: My own nick doesn't show in wee-slack channels (but does show as white underlined in other channels). When I reload wee-chat, my nick shows for the previous messages, but new messages do not show my nick. This started happening a few days back.

**Comment by trygveaa** [comment]
Are you sure you are running the latest version? This was fixed in bed3249086f7982281d3919b17c3ad74eff54b67.

**Comment by isene** [comment]
Oh, THAT recent. Updated, and yes it is fixed. Thanks.
