### ISSUE TITLE
Slack presence ('online') should mirror weechat /away setting

### ISSUE THREAD

**Issue by mato** [wee-slack/wee-slack#628]
Current behaviour:

Seems random: when connected to Slack I see a '+' next to my nickname if I've recently sent a message, but not always. Fellow team members see the same behaviour, and think I'm not around even when I am.

Expected behaviour:

I'd like wee-slack to just mirror the weechat `/away [-all]` setting. i.e. If I'm not `/away`, always show me as _online_. As a bonus (though this might be harder, no idea how Slack presence works), if I _am_ `/away` then don't show me as online even if I am messaging.

A long time ago (in wee-slack terms), there used to be a `/slack neveraway` command that almost did what I describe above (sans the linking with `/away`), but that doesn't exist anymore. Any particular reason for that?

**Comment by tfheen** [comment]
Slack doesn't offer explicit away management in their API, so this is rather hard to do.  See https://api.slack.com/methods/users.setPresence for what we have to work with.

I'm closing this since there's very little we can actually do, short of emulating activity.

**Comment by trygveaa** [comment]
> A long time ago (in wee-slack terms), there used to be a /slack neveraway command that almost did what I describe above (sans the linking with /away), but that doesn't exist anymore. Any particular reason for that?

The feature still exists, it's just an option now, instead of a command:

```
/set plugins.var.python.slack.never_away true
```

**Comment by mato** [comment]
Thank you for the explanation. I read through the `setPresence` and linked documentation, and this does indeed seem to be the intended behaviour. 

Having said that: In https://api.slack.com/docs/presence-and-status there is a further reference to https://get.slack.help/hc/en-us/articles/201864558 where I found:


  | You're active when... | You're away after...
-- | -- | --
Desktop | Slack is open and you're **interacting with your computer** | 30 minutes of inactivity
Web browser | You're interacting with Slack in your web browser | 30 minutes of browser inactivity
Mobile | Slack is open | You switch apps, close Slack, or lock your screen

(Emphasis in desktop section mine.) So, I think we could use that as an argument for emulating activity on the basis that wee-slack is more like the "Desktop" scenario.

Anyway, I'll just deal with it for now, and try if the `never_away` option still works. (Thanks @trygveaa for pointing that out.)
