### ISSUE TITLE
Request: Add notification timeout as a configuration variable

### ISSUE THREAD

**Issue by amine177** [wee-slack/wee-slack#636]
I want to extend the new messages notification timeout, can you add it?
If not, please show me where it is in code so i would hard code it or add this functionality.
Thanks in advance.

**Comment by trygveaa** [comment]
What kind of notification are you talking about?

**Comment by amine177** [comment]
The one sent through weechat to the notification daemon

**Comment by amine177** [comment]
I already changed it through dunst's config. Thanks anyway.
