### ISSUE TITLE
Can't edit messages on threads

### ISSUE THREAD

**Issue by Aerex** [wee-slack/wee-slack#648]
I am not sure if this is by design but I am unable to edit my messages in threads using the regex substitute command.

**Comment by trygveaa** [comment]
This was fixed five days ago, so try to update to the latest master.

There is still one bug though. I was just made aware that if you update the very first message in a buffer, it doesn't update in weechat (the message is still edited in Slack). I'll try to fix this.

**Comment by Aerex** [comment]
Alright will do thanks.

**Comment by trygveaa** [comment]
The bug mentioned in my previous comment has now also been fixed, so I'll close this.
