### ISSUE TITLE
Cursor mode: Copying message id etc not working

### ISSUE THREAD

**Issue by OzQu** [wee-slack/wee-slack#659]
Weeslack version 2.2.1
Weechat version 2.2

I updated weeslack to get new features such as copying message id for replying or reacting to it through cursor mode. I've reloaded python script and at the start I can see in the Weechat buffer, that the script is in version 2.1.1.

I followed the instructions on Readme. I can copy the message with 'm' in cursor mode, but 'M' doesn't do anything. 'D', 'L', 'R', 'T' also wont do anything. I don't see any errors on Weechat buffer neither. 

I also tried to define default again (as in Readme) by executing
```
/key bindctxt mouse @chat(python.*.slack.com.*):button2 hsignal:slack_mouse
/key bindctxt cursor @chat(python.*.slack.com.*):D hsignal:slack_cursor_delete
/key bindctxt cursor @chat(python.*.slack.com.*):L hsignal:slack_cursor_linkarchive
/key bindctxt cursor @chat(python.*.slack.com.*):M hsignal:slack_cursor_message
/key bindctxt cursor @chat(python.*.slack.com.*):R hsignal:slack_cursor_reply
/key bindctxt cursor @chat(python.*.slack.com.*):T hsignal:slack_cursor_thread
```

How should I try to solve this?

**Comment by trygveaa** [comment]
Oh, the buffer names in the bindings don't match if you have `short_buffer_names` set to true. Is this the case for you?

To fix the bindings, you can bind the actions yourself without slack as part of the buffer name:
```
/key bindctxt mouse @chat(python.*):button2 hsignal:slack_mouse
/key bindctxt cursor @chat(python.*):D hsignal:slack_cursor_delete
/key bindctxt cursor @chat(python.*):L hsignal:slack_cursor_linkarchive
/key bindctxt cursor @chat(python.*):M hsignal:slack_cursor_message
/key bindctxt cursor @chat(python.*):R hsignal:slack_cursor_reply
/key bindctxt cursor @chat(python.*):T hsignal:slack_cursor_thread
```

We might want to change to this in the script as well.

**Comment by OzQu** [comment]
Yes, that was the case! Thank you for this, problem solved!

**Comment by trygveaa** [comment]
I changed the default bindings to those without `.slack.com` so they work for people with `short_buffer_names` set to true. wee-slack won't overwrite existing bindings so this won't break anyones setup. Users with these bindings already set will just have to set the bindings themselves. None of the registered weechat script uses these bindings, so this is most likely much fewer users than those that have `short_buffer_names` set.
