### ISSUE TITLE
python: stdout/stderr (?): SyntaxError: invalid syntax (line 7)

### ISSUE THREAD

**Issue by bit2qubit** [wee-slack/wee-slack#661]
│01:33:53     | python: stdout/stderr (?):   File "/home/___/.weechat/python/autoload/wee_slack.py", line 7
         │01:33:53     | python: stdout/stderr (?):     <!DOCTYPE html>
         │01:33:53     | python: stdout/stderr (?):     ^
         │01:33:53     | python: stdout/stderr (?): SyntaxError: invalid syntax

Python version 2.7.16
weechat 2.2

**Comment by auscompgeek** [comment]
You downloaded an HTML page instead of the actual Python script.
