### ISSUE TITLE
Feature request: Inline reaction support

### ISSUE THREAD

**Issue by yipengsun** [wee-slack/wee-slack#669]
Hi,

Sometimes I would commend other people's message with inline reaction (see diagram below):
![image](https://user-images.githubusercontent.com/33738176/51995660-1993ab80-2481-11e9-8c60-60db34c401f3.png)

But this is not rendered in wee-slack, nor can I perform this action in wee-slack. It would be nice if this can be supported.

I'm using the `master` branch, with commit `9c178fb3346550f547e9198dbaca05f871ff85f5`

**Comment by adamgibbins** [comment]
You can already do this, see the "Add a reaction to the nth last message" section of the README.
Syntax is like so: `+:smile:`

**Comment by yipengsun** [comment]
Ah, now that you mentioned it, I can see the reactions. My terminal colorscheme makes me harder to noticed. My fault. Sorry.

**Comment by trygveaa** [comment]
Great. You can change the color with `color_reaction_suffix`.
