### ISSUE TITLE
Can't connect to Slack's WS server

### ISSUE THREAD

**Issue by pztrn** [wee-slack/wee-slack#671]
```
weechat     | python: stdout/stderr (slack): Traceback (most recent call last):
weechat     | python: stdout/stderr (slack):   File "/home/pztrn/.weechat/python/slack.py", line 131, in wrapper
weechat     | python: stdout/stderr (slack):     return f(*decode_from_utf8(args), **decode_from_utf8(kwargs))
weechat     | python: stdout/stderr (slack):   File "/home/pztrn/.weechat/python/slack.py", line 694, in reconnect_callback
weechat     | python: stdout/stderr (slack):     EVENTROUTER.reconnect_if_disconnected()
weechat     | python: stdout/stderr (slack):   File "/home/pztrn/.weechat/python/slack.py", line 380, in reconnect_if_disconnected
weechat     | python: stdout/stderr (slack):     team.connect()
weechat     | python: stdout/stderr (slack):   File "/home/pztrn/.weechat/python/slack.py", line 1205, in connect
weechat     | python: stdout/stderr (slack):     dbg("websocket connection error: {}".format(decode_from_utf8(e)))
weechat     | python: stdout/stderr (slack): UnicodeDecodeError: 'ascii' codec can't decode byte 0xd0 in position 10: ordinal not in range(128)
weechat =!= | python: error in function "reconnect_callback"
```
Plugin version 2.2.0.

Can this be related to curl_proxy usage in Weechat? If yes - how can I bypass it?

**Comment by pztrn** [comment]
More info here.

OS: Arch Linux
Weechat: 2.3
python-websockets: 0.54.0

**Comment by Coolgeek789** [comment]
do you have a proxy ? if yes, you have to set weechat.network.proxy_curl with the name of the proxy you defined in weechat
if this one is not set, you won't use a proxy

**Comment by pztrn** [comment]
This error appears despite on this variable. Same output if proxy is set or if not set. Socks5 proxy throws a warning:

```
Warning: weechat.network.proxy_curl is set to socks5 type (name : XYZ, conf string : weechat.proxy.XYZ). Only HTTP proxy is supported.
```

Possibly this error could appear as my Squid didn't support ssl bumping ATM, yet it is unclear to me why plugin throws same trace when proxy_curl isn't set.

**Comment by Coolgeek789** [comment]
it only work with a http proxy. socks proxy are not supported

**Comment by pztrn** [comment]
Please, re-read my previous post. Trace appears even if no proxy is set in Weechat.

I'm not using any kind of global proxy (in DE, /etc/environment or such, only per-application).

**Comment by Coolgeek789** [comment]
I tested with the last version from git and got this error : 

12:55:16     | python : stdout/stderr (slack) : Traceback (most recent call last):
12:55:16     | python : stdout/stderr (slack) :   File "/home/frendu/.weechat/python/autoload/wee_slack.py", line 126, in wrapper
12:55:16     | python : stdout/stderr (slack) :     return f(*decode_from_utf8(args), **decode_from_utf8(kwargs))
12:55:16     | python : stdout/stderr (slack) :   File "/home/frendu/.weechat/python/autoload/wee_slack.py", line 676, in reconnect_callback
12:55:16     | python : stdout/stderr (slack) :     EVENTROUTER.reconnect_if_disconnected()
12:55:16     | python : stdout/stderr (slack) :   File "/home/frendu/.weechat/python/autoload/wee_slack.py", line 367, in reconnect_if_disconnected
12:55:16     | python : stdout/stderr (slack) :     team.connect()
12:55:16     | python : stdout/stderr (slack) :   File "/home/frendu/.weechat/python/autoload/wee_slack.py", line 1185, in connect
12:55:16     | python : stdout/stderr (slack) :     dbg("websocket connection error: {}".format(decode_from_utf8(e)))
12:55:16     | python : stdout/stderr (slack) : UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 20: ordinal not in range(128)

but I can load history from slack.

I downgraded to websocket 0.51 and I don't have the error anymore.

try to downgrade to websocket 0.51 and see if this issue is still there

**Comment by pztrn** [comment]
Downgraded, retried with and without proxy - same trace...

**Comment by Coolgeek789** [comment]
did it work before ?

**Comment by pztrn** [comment]
Nope, I've just installed plugin and tried to connect to two workspaces.

**Comment by Coolgeek789** [comment]
So, you connect through a proxy configured on per-application basis. This proxy is a socks one. Am I right ?
Can you browse the web without a proxy ?

If not, wee_slack only works with direct connection to the internet or via http proxy. Socks one are not supported.

**Comment by pztrn** [comment]
I've already said that I've tried:

1. No proxy, direct connection.
2. HTTP proxy (Squid)
3. Socks5 proxy

As you said, socks5 will not work, I can assume my Squid might also fail somehow due to ssl+websockets (which is unlikely BTW), yet this plugin also **not working even on direct connection and shows same traceback as in first post**. Downgrading python-websockets-client wasn't sufficient and on version 0.51.0 traceback still appearing.

**Comment by Coolgeek789** [comment]
don't know then. Will let a more skillful guys to answer you :)

**Comment by pztrn** [comment]
If realtime communication is needed - I'm pztrn @ #weechat @ freenode :)

**Comment by pztrn** [comment]
After reworking code around line 1205 to:

```
                    print "websocket connection error"
                    print e 
```

I've got Errno 4, system call interrupted. Both with and without proxy.

**Comment by ivasonn** [comment]
Same err, ws connects normally without any other handlers, etc

**Comment by trygveaa** [comment]
@ivasonn: What do you mean?

**Comment by ivasonn** [comment]
For example, create_connection called in python shell is working fine, that's why i think it's not an issue related to setting proxy. i did not know the code of plugin well, but may be connecting interrupted by other block of code?

**Comment by ivasonn** [comment]
may be it help with this issue

**Comment by gianarb** [comment]
btw I saw you mentioned a proxy, but I don't use any proxy

**Comment by ivasonn** [comment]
it did not in use when i got this traceback.Anyway it's  may be my mistake about proxy, it's seems that websocket address not available in my country (no errors when using vpn or proxy (socks5)). @trygveaa, I have question about why socks5 not avaible in wee_slack? after settings this proxy type, removing your checker and install pysocks it working fine. https://github.com/websocket-client/websocket-client/pull/417

**Comment by trygveaa** [comment]
> it's seems that websocket address not available in my country (no errors when using vpn or proxy (socks5)).

Ah

> @trygveaa, I have question about why socks5 not avaible in wee_slack?

Probably just because websocket-client didn't support it when wee-slack got proxy support, and no one has asked for it. Feel free to open a PR for it.

**Comment by ivasonn** [comment]
Of course, as soon as time appears, thanks for help!

**Comment by trygveaa** [comment]
I have fixed the UnicodeDecodeErrors reported here. As for the actual error with connecting, that is the same as #676, so I'm closing this as a duplicate (yes, this issue is older, but I'm keeping the other because it has a much clearer description and discussion).
