### ISSUE TITLE
Weechat hang after handle_next

### ISSUE THREAD

**Issue by lvlts** [wee-slack/wee-slack#678]
Hi,

I'm having issues with the latest [*wee-slack* version](https://github.com/wee-slack/wee-slack/commit/8d778b7ece7c8f484252b719464f7d05bab9bca4) after connecting. I'm running the following setup:

* OS: Arch under WSL
* Weechat: 2.4 (community/weechat)
* websocket-client: 0.55.0 (community/python2-websocket-client)
* Python: 2.7.15

The error message I am getting is referenced below:

```
10:35:26 xxxxxx.slack.com     | Connected to Slack team xxxxxx (xxxxxx.slack.com) with username uname
10:35:27          weechat     | python: stdout/stderr (slack): Traceback (most recent call last):
10:35:27          weechat     | python: stdout/stderr (slack):   File "/home/uname/.dotfiles/_weechat/python/autoload/slack.py", line 582, in handle_next
10:35:27          weechat     | python: stdout/stderr (slack):     EVENTROUTER.handle_next()
10:35:27          weechat     | python: stdout/stderr (slack):   File "/home/uname/.dotfiles/_weechat/python/autoload/slack.py", line 570, in handle_next
10:35:27          weechat     | python: stdout/stderr (slack):     self.handlers[function_name](j, self, **kwargs)
10:35:27          weechat     | python: stdout/stderr (slack):   File "/home/uname/.dotfiles/_weechat/python/autoload/slack.py", line 2455, in handle_channelsinfo
10:35:27          weechat     | python: stdout/stderr (slack):     channel.set_unread_count_display(channel_json['channel'].get('unread_count_display', 0))
10:35:27          weechat     | python: stdout/stderr (slack): KeyError: u'channel'
```
After the error message, the weechat interface is completely unresponsive to key input. I end up killing it after a few minutes.

Is there any recommendation on what steps I should follow next with debugging this, or how to solve it?

Thanks!

**Comment by bobthemighty** [comment]
I have this same error, but no hang.

Some investigation shows that the response from `channels.info` is 

```
{"ok":false,"error":"method_not_supported_for_channel_type"}
```

I've fixed it by adding a check for `channel_json.get("ok", False)` to `handle_channelsinfo` but I'm unsure how to debug further. How would I figure out which channel is causing the problem if I'm unable to fetch from the info API?

**Comment by trygveaa** [comment]
The error your posting seems like the same as issue #664.

I haven't seen anyone else reporting that it hangs weechat though. Does it happen when you load wee-slack, or when you do something specific? Is it consistent, or does it happen randomly? How many teams are you connecting to, and roughly how many users are on those teams?

**Comment by lvlts** [comment]
Hi,

I'm afraid it's unrelated to the issue, but rather related to the new changes in the websocket client or glibc. The same configuration behaves differently (and works) when ran under native Arch instead of under WSL. An `strace` on the weechat pid shows the following:

```
connect(13, {sa_family=AF_INET, sin_port=htons(443), sin_addr=inet_addr("18.204.248.223")}, 16) = ? ERESTARTSYS (To be restarted if SA_RESTART is set)
--- SIGVTALRM {si_signo=SIGVTALRM, si_code=SI_TIMER, si_timerid=0, si_overrun=0, si_value={int=1663992288, ptr=0x7f6f632e81e0}} ---
rt_sigreturn({mask=[]})                 = -1 EINTR (Interrupted system call)
connect(13, {sa_family=AF_INET, sin_port=htons(443), sin_addr=inet_addr("18.204.248.223")}, 16) = ? ERESTARTSYS (To be restarted if SA_RESTART is set)
--- SIGVTALRM {si_signo=SIGVTALRM, si_code=SI_TIMER, si_timerid=0, si_overrun=0, si_value={int=1663992288, ptr=0x7f6f632e81e0}} ---
rt_sigreturn({mask=[]})                 = -1 EINTR (Interrupted system call)
connect(13, {sa_family=AF_INET, sin_port=htons(443), sin_addr=inet_addr("18.204.248.223")}, 16) = ? ERESTARTSYS (To be restarted if SA_RESTART is set)
--- SIGVTALRM {si_signo=SIGVTALRM, si_code=SI_TIMER, si_timerid=0, si_overrun=0, si_value={int=1663992288, ptr=0x7f6f632e81e0}} ---
rt_sigreturn({mask=[]})                 = -1 EINTR (Interrupted system call)
```

It keeps doing the above operation for infinity. No idea why it is happening or what could cause it. If you agree, I'd close this issue, as it appears to be unrelated to `weeslack` but rather an issue with my installation.

**Comment by trygveaa** [comment]
Hm, which version of websocket-client are you using? Version 0.55.0 fixed an issue relating to EINTR (though 0.55.0 is broken in another way, so you should use 0.56.0).

If you are using 0.56.0 and still experiencing the issue, maybe it's worth trying to use python 3 instead of 2, since python 3 handles EINTR on the language level. Though, you will most likely have to compile weechat yourself to get support for python 3, unless you wait until July 1 when it will be the default.

**Comment by lvlts** [comment]
Hi,

I have 0.56.0 at the moment.  It appears to be a problem with the emulation layer from WSL maybe related to https://github.com/Microsoft/WSL/issues/3998 

weechat with python3 exhibits the same behavior. A rsynced native system (non-WSL) is functional using either weechat python2 or weechat python3.

**Comment by trygveaa** [comment]
Okay, then I'll close this issue, since it doesn't seem like there is anything I can do about that issue, and the other issue is covered by #664.
