### ISSUE TITLE
Neveraway Function Error

### ISSUE THREAD

**Issue by Faendrek** [wee-slack/wee-slack#682]
Neveraway seems to be throwing errors. Any suggestions?
```
17:35 =!= python: error in function "slack_never_away_cb"
17:40 python: stdout/stderr (slack): Traceback (most recent call last):
17:40 python: stdout/stderr (slack):   File "/home/w0269804/.weechat/python/autoload/wee_slack.py", line 126, in wrapper
17:40 python: stdout/stderr (slack):     return f(*decode_from_utf8(args), **decode_from_utf8(kwargs))
17:40 python: stdout/stderr (slack):   File "/home/w0269804/.weechat/python/autoload/wee_slack.py", line 831, in slack_never_away_cb
17:40 python: stdout/stderr (slack):     slackbot = t.get_channel_map()['slackbot']
17:40 python: stdout/stderr (slack): KeyError: u'slackbot'
17:40 =!= python: error in function "slack_never_away_cb"

```

**Comment by trygveaa** [comment]
This has been fixed in master. It's a while since I released though, so the issue still appears in the version in weechats script repo. (I should probably release a new version soon.)

**Comment by Faendrek** [comment]
Thank you. I thought that the link in the README was pointing at master already? Do the releases have build steps involved with them or is it literally just coping the wee_slack.py script?

**Comment by Faendrek** [comment]
Ah. I see the relevant change in master: 

```
    if config.never_away:
        for t in EVENTROUTER.teams.values():
            slackbot = t.get_channel_map()['Slackbot']
            channel = t.channels[slackbot]
            request = {"type": "typing", "channel": channel.identifier}
            channel.team.send_to_websocket(request, expect_reply=False)
    return w.WEECHAT_RC_OK
```

Looks like a casing issue. Thank you.

**Comment by trygveaa** [comment]
Yeah, it's just copying wee_slack.py, no build steps. I just mentioned releases in case you were installing from weechats script repo, because that's only updated when there's a new release. And yes, the fix was just too change the case.
