### ISSUE TITLE
Slack upload does not work for me

### ISSUE THREAD

**Issue by gianarb** [wee-slack/wee-slack#695]
Hello!
When I do`/slack upload` nothing happens. I tried with files with different dimensions. Even an empty `txt` file but nothing. The command doesn't generate any output.
I do not know how to debug this issue. Let me know what I can provide.

```
$ uname -a
Linux gianarb 5.1.2-arch1-1-ARCH #1 SMP PREEMPT Wed May 15 00:09:47 UTC 2019 x86_64 GNU/Linux
$ weechat -v
2.4
```

**Comment by apetresc** [comment]
Are you providing a relative or absolute path? (And just to confirm - are you running weechat on the same machine as the files are on? This is something I often forget when SSHed into weechat and I try to upload a file from the laptop :smile:)

**Comment by trygveaa** [comment]
The upload command apparently didn't have any error reporting at all, so that's why you didn't get any output. I've added error handling and error reporting now, so try again with latest master and see what error you get.

**Comment by gianarb** [comment]
Hello! Thanks for adding some output.
I did:
```
$ touch /tmp/ciao.txt
```
and I tried to load that file I got:

```
ERROR: Couldn't upload file. Error: no_file_data
```
I thought maybe I can only load tar or file with content so I created a tar.gz (7mb size) and I uploaded it, I got this error message:

```
ERROR: Couldn't upload file. Got return code -2. Error:
```

**Comment by trygveaa** [comment]
> $ touch /tmp/ciao.txt
> and I tried to load that file I got:
> ERROR: Couldn't upload file. Error: no_file_data

Slack doesn't allow you to upload empty files, so this is expected.

> ERROR: Couldn't upload file. Got return code -2. Error:

-2 means that weechat couldn't run curl, or that it timed out. Is curl available on your machine? What is slack_timeout set to? Try to upload a smaller file, create one with `echo test > /tmp/testfile.txt`

**Comment by pshevtsov** [comment]
I also get the same error message when I'm trying to upload the 1.4M file using either absolute or relative (starting with `~`) paths:

```
ERROR: Couldn't upload file. Got return code -2. Error:
```

Some info:

```
$ uname -a
Linux inspiron 4.9.0-9-amd64 #1 SMP Debian 4.9.168-1 (2019-04-12) x86_64 GNU/Linux
$ weechat -v
2.5
$ curl --version
curl 7.52.1 (x86_64-pc-linux-gnu) libcurl/7.52.1 OpenSSL/1.0.2r zlib/1.2.8 libidn2/0.16 libpsl/0.17.0 (+libidn2/0.16) libssh2/1.7.0 nghttp2/1.18.1 librtmp/2.3
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS IDN IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz TLS-SRP HTTP2 UnixSockets HTTPS-proxy PSL

plugins.var.python.slack.slack_timeout  string  "20000"
```

**Comment by pshevtsov** [comment]
Increasing `plugins.var.python.slack.slack_timeout` to `30000` worked for me.

**Comment by gianarb** [comment]
Same for me closing thanks
