### ISSUE TITLE
/thread xxx does not show first message in thread in thread buffer

### ISSUE THREAD

**Issue by mkaito** [wee-slack/wee-slack#705]
When there's more than 2-3 threads going around in the same channel, the `/thread` command is a godsent to keep them straight. However, it's annoying that the new thread buffer doesn't include the very first message in the thread (which I suppose is not technically part of the thread) for context.

**Comment by trygveaa** [comment]
The first message is shown in the title of the buffer. However, I have seen that this is impractical when the message is long, so maybe we should print it as the first message too.

**Comment by mkaito** [comment]
I think that would be ideal, and probably more intuitive.
