### ISSUE TITLE
User typing indicator no longer works for DMs

### ISSUE THREAD

**Issue by marceldev89** [wee-slack/wee-slack#706]
It seems like the user typing indicator for DMs no longer works. I tried debugging the bar_item callback thingy but I couldn't get the `dbg` or `w.prnt` call to work in there so I gave up.

WeeChat version: 2.5
wee-slack version: current master

**Comment by trygveaa** [comment]
It's working fine for me. You can just use `print` in the function, and it will be printed in the core buffer. E.g. try `print(typers)` at the end of `typing_bar_item_cb` and it should continuously output `[]` when no one is typing and the nick when someone is typing.

**Comment by marceldev89** [comment]
Using `print` in `typing_bar_item_cb` doesn't print anything either. It's as if the callback never gets called. Adding `print` to `typing_update_cb` does print stuff but it's kinda useless in this case.

**Comment by trygveaa** [comment]
Then you probably have removed the bar item from the bar. Check `weechat.bar.status.items` (if the status bar was where you had it).

**Comment by marceldev89** [comment]
Waaaiiitt, that's something else. I'm talking about the buffer list. Oops, my bad

**Comment by trygveaa** [comment]
The typing indicator in the buffer list is just for channels, not DMs.

**Comment by marceldev89** [comment]
Alright, I could've sworn it used to work but it seems I'm imagining
things. Thanks anyway. :)

Op vr 5 jul. 2019 00:00 schreef Trygve Aaberge <notifications@github.com>:
