### ISSUE TITLE
Tons of Whitespace Added In Latest Version

### ISSUE THREAD

**Issue by jandrusk** [wee-slack/wee-slack#708]
I just pulled the latest version and noticed that there's a lot of new white space between the time field and the handle names of posted messages in the left window pane. Also seems to be some extra white space in the third pane where all of the user handles are listed.

Was this the intent?

**Comment by auscompgeek** [comment]
I cannot reproduce this.

**Comment by jandrusk** [comment]
I'm going to be closing this as this turns out to be the end result of people with ridiculously long username handles.
