### ISSUE TITLE
Latest master does not load messages

### ISSUE THREAD

**Issue by antoyo** [wee-slack/wee-slack#714]
Hi.
With the current latest commit on master, the messages do not load.
No messages are in the `slack-debug` buffer, but there are the following errors in the core buffer:
```
Error: a buffer with same name (url.slack.com.#channel) already exists
# […] a bunch of other errors "a buffer with same name…"
Connected to Slack team adgear (url.slack.com) with username antoyo
python: stdout/stderr (slack): Traceback (most recent call last):
python: stdout/stderr (slack):   File "/home/antoyo/.weechat/python/autoload/wee_slack.py", line 630, in handle_next
python: stdout/stderr (slack):     EVENTROUTER.handle_next()
python: stdout/stderr (slack):   File "/home/antoyo/.weechat/python/autoload/wee_slack.py", line 618, in handle_next
python: stdout/stderr (slack):     self.handlers[function_name](j, self, **kwargs)
python: stdout/stderr (slack):   File "/home/antoyo/.weechat/python/autoload/wee_slack.py", line 2764, in handle_conversationsmembers
python: stdout/stderr (slack):     channel.members = set(members_json['members'])
python: stdout/stderr (slack): KeyError: u'members'
python: stdout/stderr (slack): Traceback (most recent call last):
python: stdout/stderr (slack):   File "/home/antoyo/.weechat/python/autoload/wee_slack.py", line 630, in handle_next
python: stdout/stderr (slack):     EVENTROUTER.handle_next()
python: stdout/stderr (slack):   File "/home/antoyo/.weechat/python/autoload/wee_slack.py", line 618, in handle_next
python: stdout/stderr (slack):     self.handlers[function_name](j, self, **kwargs)
python: stdout/stderr (slack):   File "/home/antoyo/.weechat/python/autoload/wee_slack.py", line 2764, in handle_conversationsmembers
python: stdout/stderr (slack):     channel.members = set(members_json['members'])
python: stdout/stderr (slack): KeyError: u'members'
python: stdout/stderr (slack): Traceback (most recent call last):
python: stdout/stderr (slack):   File "/home/antoyo/.weechat/python/autoload/wee_slack.py", line 630, in handle_next
python: stdout/stderr (slack):     EVENTROUTER.handle_next()
python: stdout/stderr (slack):   File "/home/antoyo/.weechat/python/autoload/wee_slack.py", line 618, in handle_next
python: stdout/stderr (slack):     self.handlers[function_name](j, self, **kwargs)
python: stdout/stderr (slack):   File "/home/antoyo/.weechat/python/autoload/wee_slack.py", line 2764, in handle_conversationsmembers
python: stdout/stderr (slack):     channel.members = set(members_json['members'])
python: stdout/stderr (slack): KeyError: u'members'
python: stdout/stderr (slack): Traceback (most recent call last):
python: stdout/stderr (slack):   File "/home/antoyo/.weechat/python/autoload/wee_slack.py", line 630, in handle_next
python: stdout/stderr (slack):     EVENTROUTER.handle_next()
python: stdout/stderr (slack):   File "/home/antoyo/.weechat/python/autoload/wee_slack.py", line 618, in handle_next
python: stdout/stderr (slack):     self.handlers[function_name](j, self, **kwargs)
python: stdout/stderr (slack):   File "/home/antoyo/.weechat/python/autoload/wee_slack.py", line 2764, in handle_conversationsmembers
python: stdout/stderr (slack):     channel.members = set(members_json['members'])
python: stdout/stderr (slack): KeyError: u'members'
```
Thanks to fix the issue.

**Comment by auscompgeek** [comment]
> a buffer with the same name already exists

From my experience, this one happens when you /upgrade with wee-slack loaded. Dunno if there's an issue open for that one already.

The KeyErrors are interesting though. Could you turn on record events and send a copy of the conversations.members responses with no members key? (They'll be recorded in /tmp/weeslack-debug/http iirc.)

**Comment by trygveaa** [comment]
Can you try it with this patch and post what's printed?

```
diff --git a/wee_slack.py b/wee_slack.py
index 164490d..2df7679 100644
--- a/wee_slack.py
+++ b/wee_slack.py
@@ -2758,10 +2758,14 @@ def handle_history(message_json, eventrouter, **kwargs):
 
 
 def handle_conversationsmembers(members_json, eventrouter, **kwargs):
-    request_metadata = members_json['wee_slack_request_metadata']
-    team = eventrouter.teams[request_metadata.team_hash]
-    channel = team.channels[request_metadata.channel_identifier]
-    channel.members = set(members_json['members'])
+    try:
+        request_metadata = members_json['wee_slack_request_metadata']
+        team = eventrouter.teams[request_metadata.team_hash]
+        channel = team.channels[request_metadata.channel_identifier]
+        channel.members = set(members_json['members'])
+    except:
+        print(format_exc_only())
+        print(user_json)
 
 
 def handle_usersinfo(user_json, eventrouter, **kwargs):
```

Did the "a buffer with same name (url.slack.com.#channel) already exists" errors happen after `/upgrade`? Do they still happen after a reload of wee-slack?

**Comment by trygveaa** [comment]
> Sorry for the confusion, the buffers are not loading (I had two wee-slack loaded).

How did you manage that? Normally weechat won't let you load a script that is already loaded.

> Also, I assume you meant members_json instead of user_json

Sorry, yeah. Okay, so you got the error `fetch_members_failed`. We should handle that, though not sure we can do anything other than ignore the error and go on without the member list. The error message didn't say any reason, so I don't know what causes it.

> I still the get error with buffer already exists.

Do you still get it after unloading both instances of wee-slack and loading it again?

**Comment by trygveaa** [comment]
I've added error handling for the members error now.

> So, what I was doing was closing weechat, updating the plugin, and opening weechat. I had two plugins in the directory, that's why I had two versions.

Even if I try with two wee-slack scripts in the directory, it isn't loaded two times for me. It says "python: unable to register script "slack" (another script already exists with this name)" and stops loading the second one. The only way I can reproduce the "buffer already exists" error is by running `/upgrade`.

You haven't been using the `/upgrade` command, or the `--upgrade` option?

How do you see that wee-slack is loaded two times?

> Do you still want that I test "Do you still get it after unloading both instances of wee-slack and loading it again?" now that you know how I reload the plugin?

Please do, with the latest commit I pushed.

**Comment by trygveaa** [comment]
What do you mean by "the channels do not load"? All channels, or just the ones shared between slack teams? How do they not load? Are the buffers missing, the messages missing, or something else?

**Comment by trygveaa** [comment]
If you unload the script, all the slack buffers should disappear. Does that happen?

If you then try `/script load wee_slack.py`, do you then get the errors about buffers already existing?

**Comment by trygveaa** [comment]
Hm, that's weird. I can't reproduce it. But I'll try to fix the similar issue about buffers already existing after `/upgrade` and maybe that will help for you too. I'm not sure when I'll have time to do that though.

**Comment by auscompgeek** [comment]
Are you still able to reproduce after clean restarting weechat?

**Comment by Phyks** [comment]
Hi,

I've been having a similar issue lately, very often in threads. "Error: A buffer with the same name (…) already exists" in the weechat core window. It seems to happen quite randomly, but when this happens, I will no longer receive any new incoming message in this thread. Closing the buffer means I can never reopen it again :/

Thanks!

**Comment by immae** [comment]
I’m using this workaround to avoid it:
```
diff --git a/wee_slack.py b/wee_slack.py
index d42bc7b..84b9629 100644
--- a/wee_slack.py
+++ b/wee_slack.py
@@ -2253,8 +2253,9 @@ class SlackThreadChannel(SlackChannelCommon):
 
     def open(self, update_remote=True):
         self.create_buffer()
-        self.active = True
-        self.get_history()
+        if self.channel_buffer:
+            self.active = True
+            self.get_history()
         # if "info" in SLACK_API_TRANSLATOR[self.type]:
         #    s = SlackRequest(self.team.token, SLACK_API_TRANSLATOR[self.type]["info"], {"name": self.identifier}, team_hash=self.team.team_hash, channel_identifier=self.identifier)
         #    self.eventrouter.receive(s)
@@ -2273,6 +2274,8 @@ class SlackThreadChannel(SlackChannelCommon):
         """
         if not self.channel_buffer:
             self.channel_buffer = w.buffer_new(self.formatted_name(style="long_default"), "buffer_input_callback", "EVENTROUTER", "", "")
+            if not self.channel_buffer:
+                self.channel_buffer = w.buffer_search("python", self.formatted_name(style="long_default"))
             self.eventrouter.weechat_controller.register_buffer(self.channel_buffer, self)
             w.buffer_set(self.channel_buffer, "localvar_set_type", 'channel')
             w.buffer_set(self.channel_buffer, "localvar_set_nick", self.team.nick)
```
It avoids the issue of losing messages and buffers, but it has some annoying drawbacks (duplicating all the messages when he fetches history, or merging threads when they happen to share the same hash), that’s why I don’t propose it as a PR yet.

**Comment by trygveaa** [comment]
> I've been having a similar issue lately, very often in threads. "Error: A buffer with the same name (…) already exists" in the weechat core window. It seems to happen quite randomly, but when this happens, I will no longer receive any new incoming message in this thread. Closing the buffer means I can never reopen it again :/

This has now been fixed.

**Comment by antoyo** [comment]
It works.
Thanks.
