### ISSUE TITLE
Suspend/resume causes new messages to not hit the hotlist

### ISSUE THREAD

**Issue by zingyb** [wee-slack/wee-slack#715]
I'm not sure if this is a wee-slack problem, but suspending/resuming any of my devices will cause any messages sent to me during the sleep cycle to not show up in my hotlist. Perhaps more broadly, the history seems to not reload when resuming.

This causes me to need to run `/script reload slack` every time I resume.

Arch Linux
weechat 2.5 (python 2)
python2-websocket-client 0.56.0
wee-slack only behind the latest bunch of master commits.

**Comment by trygveaa** [comment]
> wee-slack only behind the latest bunch of master commits.

So you have commit e89ab6822327f6b20c86fca9a7b97e9d56a7d4d0? I thought I fixed this with that.

**Comment by trygveaa** [comment]
Okay. What is `plugins.var.python.slack.background_load_all_history` set to?

**Comment by zingyb** [comment]
On 2019-08-28 10:46, Trygve Aaberge wrote:
>Okay. What is `plugins.var.python.slack.background_load_all_history` set to?

true

**Comment by trygveaa** [comment]
This should now be fixed as long as `background_load_all_history` is set to `true` (which is now the default).

Currently, it would be possible to make it work with it set to false, but it would mean a lot of extra http requests, and that option exists to reduce the number of requests. Also, some API's are being deprecated in November, so after that I don't think it's possible to support this without calling the history API. Therefore, I don't think it's worth doing, and I've noted in the [readme](https://github.com/wee-slack/wee-slack#known-issues) that it won't work with this option set to false.
