### ISSUE TITLE
Unable to use a secured token

### ISSUE THREAD

**Issue by dannycolin** [wee-slack/wee-slack#717]
**Step to reproduce**

0. `/slack register`
0. Open URL https://slack.com/oauth/authorize?client_id=...
0. Allow wee-slack
0. Add the token after `?code=` to `slack_token` with `/secure set`
0. Set `plugins.var.python.slack.slack_api_token = "${sec.data.slack_token}"`
0. `python reload slack`

Note: I've tried both with the token after `?=code` as  is and also by adding `xoxp-` in front of it.

**Actual Behavior**

I got the error

```
ERROR: Failed connecting to Slack with token starting with [the code in the secure var]: invalid_auth
ERROR: Token does not look like a valid Slack token. Ensure it is a valid token and not just a OAuth code.
```

**Expected Behavior**

Wee-slack should connect to Slack since it seems to be able to see the secure variable I've set.

**Comment by auscompgeek** [comment]
> Add the token after ?code= to slack_token with /secure set

This is incorrect. You must complete the OAuth handshake using `/slack register`. `code` is not a valid OAuth token.

**Comment by dannycolin** [comment]
> This is incorrect. You must complete the OAuth handshake using `/slack register`. `code` is not a valid OAuth token.

I'm not sure I'm following you because it works with `/slack register [token after ?=code]`

**Comment by auscompgeek** [comment]
Yes, that is expected behaviour. `code` is not valid for use as a token - it is only used to obtain a token.

**Comment by trygveaa** [comment]
@dannycolin: There are two different codes/tokens. There is the one after `?code=` which is only used for the oauth process, and there is the actual slack token which starts with `xo` which is used for communication with the API. The slack token is obtained by running `/slack register <code>` where `<code>` is the one after `?code=`. When you run this, the token which starts with `xo` is appended to the `slack_api_token` option. Therefore, you can't use the code directly with `/secure set`, you have to run `/slack register <code>` with it.

If you want the token stored securely, you will need to copy it out of `slack_api_token` yourself after running `/slack register <code>`.
