### ISSUE TITLE
websocket

### ISSUE THREAD

**Issue by daneoshiga** [wee-slack/wee-slack#718]
Hi, I really like wee-slack and enjoy your hard work,
I've upgraded weechat through apt and it probably broke websocket

Upgrade: weechat:amd64 (2.5-1, 2.6-1), weechat-plugins:amd64 (2.5-1, 2.6-1), weechat-ruby:amd64 (2.5-1, 2.6-1), weechat-core:amd64 (2.5-1, 2.6-1), weechat-perl:amd64 (2.5-1, 2.6-1), weechat-python:amd64 (2.5-1, 2.6-1), weechat-curses:amd64 (2.5-1, 2.6-1)

When I try to load weechat, I got the the following message

```
python: stdout/stderr (?): Traceback (most recent call last):
python: stdout/stderr (?):   File "~/.weechat/python/autoload/wee_slack.py", line 33, in python: stdout/stderr (?):     from websocket import ABNF, create_connection, WebSocketConnectionClosedException
python: stdout/stderr (?): ModuleNotFoundError: No module named 'websocket'
```

Trying to install websocket with pip only changes the exception for 

```
python: stdout/stderr (?): ImportError: cannot import name 'ABNF'
```

Thanks again for your project

**Comment by dmilith** [comment]
Have you tried `pip install websocket-client`?

**Comment by daneoshiga** [comment]
oh sorry.. missed the correct pip, sorry, worked like a charm

**Comment by flopex** [comment]
Worth noting that `weechat` was just updated to be compiled with `python3` by default which is why it broke after an `apt upgrade`. https://weechat.org/files/changelog/ChangeLog-devel.html#v2.6

```
pip3 install websocket
```
or
```
sudo apt install python3-websocket
```
should fix it.
