### ISSUE TITLE
autosort plugins returns warning when using wee-slack

### ISSUE THREAD

**Issue by dannycolin** [wee-slack/wee-slack#720]
I got a lot of `autosort: usage: ${info:autosort_replace,old,new,text}` message in weechat when wee-slack and autosort are both loaded. It wsan't happening before installing wee-slack. So, it seems to create a conflict with autosort. Those warnings appear whenever there's a new message in a wee-slack buffer.

**Comment by auscompgeek** [comment]
I can't seem to reproduce this. I've had autosort.py loaded for a few days now...

**Comment by jgresty** [comment]
This was a problem with an older version of autosort, nothing to do with this project. Updating your autosort plugin and regenerating the config should fix this issue.

See https://github.com/de-vri-es/weechat-autosort/issues/17 for more details.

**Comment by trygveaa** [comment]
@jgresty: Thanks for the info!

**Comment by dannycolin** [comment]
Thanks.
