### ISSUE TITLE
Disconnect from server

### ISSUE THREAD

**Issue by technowar** [wee-slack/wee-slack#727]
How do I disconnect from the Slack server I joined?

**Comment by auscompgeek** [comment]
https://github.com/wee-slack/wee-slack#removing-a-team

**Comment by technowar** [comment]
Thank you!

**Comment by hasufell** [comment]
This isn't so much disconnecting. I want to temporarily disconnect from the corporate slack (e.g. over weekend), not remove the token.

**Comment by trygveaa** [comment]
@hasufell: Right. Please open a new issue though.
