### ISSUE TITLE
Setting a topic that contains newlines via multiline doesn't seem to work

### ISSUE THREAD

**Issue by stevana** [wee-slack/wee-slack#728]
E.g. `/topic foo↩bar`

**Comment by auscompgeek** [comment]
What happens instead? Do you get a topic "foo" and a message "bar", or something completely different?

**Comment by stevana** [comment]
>  Do you get a topic "foo" and a message "bar"

Yes

**Comment by sudoforge** [comment]
Multine sends two successive messages, not a single message with a newline.

**Comment by trygveaa** [comment]
Weechat handles parsing the input and triggering the appropriate command callback in wee-slack. This callback only gets the first line, so there is no way to solve this without a change in weechat. I think https://github.com/weechat/weechat/pull/1063 would solve it, but that's been open for a long time.

**Comment by trygveaa** [comment]
I found another workaround I could use, so this works now.

**Comment by sudoforge** [comment]
> I found another workaround

Awesome! What is it?

**Comment by trygveaa** [comment]
In the `input_text_for_buffer` modifier, you can change the string coming from the input field. This is called before the input is split into multiple lines. This was also what was used before, but I now realized that I can replace the newlines with carriage returns, and change them back again in the `input_callback` function. WeeChat only splits on newline, not on carriage return, so with this we avoid the splitting. Carriage return won't be used for anything other than separating lines, so it's safe to use this as a replacement character.

See https://github.com/wee-slack/wee-slack/commit/15168752c666d821b55a3074cbab9d6d857af5d6
