### ISSUE TITLE
Certify wee-slack integration on Slack

### ISSUE THREAD

**Issue by gianarb** [wee-slack/wee-slack#730]
Hello,
I was digging a bit inside a few channels that do not enable wee-slack :( sadly...

![2019-11-06-09-08-42_911x119](https://user-images.githubusercontent.com/1630267/68280119-32b33380-0075-11ea-8bd6-e71af5e4062c.png)

From my understanding, it is possible to be certified by Slack in some way. did we tried already?! I think it will may simplify the process of using wee-chat. But I am not sure.

**Comment by trygveaa** [comment]
I have my doubts because we use the client oauth scope, but I haven't asked Slack about it. Also, see https://github.com/wee-slack/wee-slack/issues/560#issuecomment-395358980

**Comment by gianarb** [comment]
Thanks @trygveaa ! I closed this one because it is a duplicate of #560
