### ISSUE TITLE
No notification in hotbar for chats opened in multiple buffers

### ISSUE THREAD

**Issue by xmadscientist** [wee-slack/wee-slack#740]
I have 5 buffers open to have 5 different chats at the same time. But when I get a message in an inactive buffer, I don't get any notification in my hotbar for it. 

Is this expected behaviour? If so, how do you display a notif in the hotbar for inactive (but open) buffers?

**Comment by trygveaa** [comment]
Do you mean using split windows when you say buffers open at the same time? If so, yes this is expected. It behaves the same with irc buffers.

You can change `weechat.look.hotlist_add_conditions` to change this behavior.

**Comment by xmadscientist** [comment]
@trygveaa So I changed the behaviour to send a notification for my open/split windows and buffers, but for any buffers outside of the opened ones, I don't get a notification at all. I looked at the documentation for said option bu there is literally nothing on the web that talks about this.

**Comment by trygveaa** [comment]
What did you change it to?

**Comment by xmadscientist** [comment]
I did this:

/set weechat.look.hotlist_add_conditions = "${away} || ${buffer.num_displayed} == 0 || ${buffer.active} == 0"

**Comment by trygveaa** [comment]
Hm, it seems to be working for me. But that `=` should not be there, as it will end up being part of the variable. So try running it without it:

```
/set weechat.look.hotlist_add_conditions "${away} || ${buffer.num_displayed} == 0 || ${buffer.active} == 0" 
```

**Comment by xmadscientist** [comment]
Ok that seemed to partially work for me. I am now getting notifications for outside buffers, but for any buffers open in split windows (but still inactive), I'm not getting anything. @trygveaa any insights?

**Comment by trygveaa** [comment]
Right, `buffer.active` doesn't do what you think it does. It has to do with multiple buffers merged into one window, not split windows. Try this instead:
```
/set weechat.look.hotlist_add_conditions "${away} || ${window.buffer} != ${buffer}"
```

What it does is check that the buffer that's active in the window that's active is not the same as the buffer which receives the message. `buffer.num_displayed` shouldn't be necessary when you have this check, so I removed that.

**Comment by xmadscientist** [comment]
That looks like it worked, thanks a million! @trygveaa do you know off the top of your head if there is a setting that has conditions for "reading" hotlist notifications? I essentially want the hotlist entry to disappear once the buffer is focussed.

**Comment by trygveaa** [comment]
No, unfortunately not. There is an open issue for it in weechats repo: https://github.com/weechat/weechat/issues/170

There's also a workaround mentioned there, you could try that.

**Comment by xmadscientist** [comment]
Nice, thanks a lot for pointing me in the right direction @trygveaa.
