### ISSUE TITLE
Only getting notifications in hotlist for private chats

### ISSUE THREAD

**Issue by xmadscientist** [wee-slack/wee-slack#744]
For some reason, I am only getting notifications in my hotlist for private chats (1 on 1). For any slack channels, even if I am tagged, it does not appear in my hotlist or send a notification. I have checked the notification level for all channels and they are all set to: "all".

Any insights?

**Comment by xmadscientist** [comment]
Anyone?

**Comment by trygveaa** [comment]
This is probably because you changed `weechat.look.hotlist_add_conditions`? Check if you can reproduce with it set to the default value.

**Comment by trygveaa** [comment]
Since you didn't respond, I'll assume the issue was what I mentioned above.
