### ISSUE TITLE
Emoji autocomplete isn't working

### ISSUE THREAD

**Issue by jsatk** [wee-slack/wee-slack#745]
I ran:
```sh
$ cd ~/.weechat
$ curl -O https://raw.githubusercontent.com/wee-slack/wee-slack/master/weemoji.json
```
And then in Weechat ran:
```
/set weechat.completion.default_template "%(nicks)|%(irc_channels)|%(emoji)"
/save
/python reload slack
```

But when I type `:sm<TAB>` it doesn't show auto-complete suggestions. Any help?

**Comment by trygveaa** [comment]
You can't place the directory at the end of the curl command like that. It will treat it as another url to download, and will download the file to the current directory. It should still work if you were in that directory though. Have you verified that `~/.weechat/weemoji.json` exists and contains the correct content?

If it does, try enabling [debug mode](https://github.com/wee-slack/wee-slack#development) and look for "Couldn't load emoji list:" in the debug buffer. It will show the error message if an error has occurred when reading the file.

**Comment by jsatk** [comment]
> You can't place the directory at the end of the curl command like that. It will treat it as another url to download, and will download the file to the current directory. It should still work if you already were in the `.weechat` directory though. Have you verified that `~/.weechat/weemoji.json` exists and contains the correct content?
> 
> If it does, try enabling [debug mode](https://github.com/wee-slack/wee-slack#development) and look for "Couldn't load emoji list:" in the debug buffer. It will show the error message if an error has occurred when reading the file.

You're right. I was attempting to shorten my comment/be clever and it backfired. I updated it.

To answer your question, yes. `~/.weechat/weemoji.json` exists and is a list of emoji names. I'll fire it up with the debugger when I'm back at my personal computer and try to figure out what's going on.

**Comment by jsatk** [comment]
@trygveaa I've confirmed `~/.weechat/weemoji.json` is the same thing as what's in this repo. I also turned on debug mode. It doesn't print anything in channel #slack-debug. I tried going to Slack channels and typing `:h<TAB>` (which doesn't do the autosuggestion) and going back into #slack-debug. Nothing.

**Comment by trygveaa** [comment]
It won't print anything when you execute completion, it only prints the message I mentioned with an error reason when the script loads if it can't load the weemoji file (so it will be one of the first lines in the slack-debug buffer).

But I made a new branch which prints some more info to help you debug here: https://github.com/trygveaa/wee-slack/blob/debug-emoji-completion/wee_slack.py
It will print how many emojis it has loaded into completion, and when you execute completion, it will print which word is it completing, how many emojis it adds to the completion list, and if it aborts for any reason. This will be printed to the core buffer, please paste the output after loading it and trying completion here.

**Comment by jsatk** [comment]
> It won't print anything when you execute completion, it only prints the message I mentioned with an error reason when the script loads if it can't load the weemoji file (so it will be one of the first lines in the slack-debug buffer).

Given this info, I think it's loading correctly then. I see no error messages.

**Comment by trygveaa** [comment]
I'm cleaning up old branches now, so I deleted it, but if you still need it, here is the diff which can be applied on commit 8c509af:

```
diff --git a/wee_slack.py b/wee_slack.py
index f35a2af..803aed1 100644
--- a/wee_slack.py
+++ b/wee_slack.py
@@ -1029,15 +1029,24 @@ def emoji_completion_cb(data, completion_item, current_buffer, completion):
     """
     current_channel = EVENTROUTER.weechat_controller.buffers.get(current_buffer)
     if current_channel is None:
+        print('emoji completion: not in slack channel, aborting')
         return w.WEECHAT_RC_OK
 
     base_word = w.hook_completion_get_string(completion, "base_word")
+    print('emoji completion: completing word {}'.format(base_word))
     if ":" not in base_word:
+        print("emoji completion: word doesn't contain :, aborting")
         return w.WEECHAT_RC_OK
     prefix = base_word.split(":")[0] + ":"
 
+    print("emoji completion: searching through {} emojis".format(len(current_channel.team.emoji_completions)))
+
+    i = 0
     for emoji in current_channel.team.emoji_completions:
+        i += 1
         w.hook_completion_list_add(completion, prefix + emoji + ":", 0, w.WEECHAT_LIST_POS_SORT)
+
+    print("emoji completion: added {} emojis to completion list".format(i))
     return w.WEECHAT_RC_OK
 
 
@@ -1279,6 +1288,7 @@ class SlackTeam(object):
 
     def load_emoji_completions(self):
         self.emoji_completions = list(EMOJI)
+        print('Loaded {} emojis for team'.format(len(self.emoji_completions)))
         if self.emoji_completions:
             s = SlackRequest(self.token, "emoji.list", {}, team_hash=self.team_hash)
             self.eventrouter.receive(s)
@@ -4506,9 +4516,12 @@ def load_emoji():
     try:
         DIR = w.info_get("weechat_dir", "")
         with open('{}/weemoji.json'.format(DIR), 'r') as ef:
-            return json.loads(ef.read())["emoji"]
+            emoji = json.loads(ef.read())["emoji"]
+            print('Loading {} emojis'.format(len(emoji)))
+            return emoji
     except:
         dbg("Couldn't load emoji list: {}".format(format_exc_only()), 5)
+        print("Couldn't load emoji list: {}".format(format_exc_only()))
     return []
 
 
@@ -4961,6 +4974,7 @@ if __name__ == "__main__":
             w.hook_modifier("input_text_for_buffer", "input_text_for_buffer_cb", "")
 
             EMOJI.extend(load_emoji())
+            print('Loaded {} emojis'.format(len(EMOJI)))
             setup_hooks()
 
             # attach to the weechat hooks we need
```
