### ISSUE TITLE
Should automatically rehistory after message delete

### ISSUE THREAD

**Issue by c-alpha** [wee-slack/wee-slack#748]
When I delete the last message using `s///`, things seem to get out of sync:
- I cannot delete any further message (further `s///` have no effect);
- the display can get messed up when the deleted one was a multiline message.

Doing a `/slack rehistory` immediately after each delete avoids all of the above.

Posting a new message works as expected, however.

It would hence seem useful to me, if and when a message has been deleted by the user (`s///`), an automatic `rehistory` of the channel or chat were performed after a short delay (e.g. 2 seconds). The delay allows for seeing the `(deleted)` marker.

**Comment by trygveaa** [comment]
>  I cannot delete any further message (further s/// have no effect)

The deleted message is still counted, so to delete the message before it, you have to write `2s///`.

> the display can get messed up when the deleted one was a multiline message.

By messed up, do you mean that blank lines remain between the deleted message and the next, or do you experience anything else?

**Comment by c-alpha** [comment]
> > I cannot delete any further message (further s/// have no effect)
> 
> The deleted message is still counted, so to delete the message before it, you have to write `2s///`.

I see. That seems logical, but counter-intuitive. In the slack web client, a deleted message disappears immediately. Hence I hadn't expected it to still exist in wee-slack.

> > the display can get messed up when the deleted one was a multiline message.
> 
> By messed up, do you mean that blank lines remain between the deleted message and the next, or do you experience anything else?

I enter three messages, which are longer than a screen line, but **not** multi-line messages (i.e. do not contain line breaks). Then I delete the last one using `s///` which gives me the following result:

<img width="732" alt="Screenshot 2020-02-06 at 17 05 38 " src="https://user-images.githubusercontent.com/2213269/73955420-9ca4d880-4903-11ea-99c7-69a31f5943ba.png">

If I then issue a `2s///` to delete the next message back, the result is:

<img width="732" alt="Screenshot 2020-02-06 at 17 06 26 " src="https://user-images.githubusercontent.com/2213269/73955552-ce1da400-4903-11ea-9bcf-18c6b81131c2.png">

See what I mean?

---

Now repeating the same experiment with messages which **do** contain line breaks. Result after `s///`:

<img width="732" alt="Screenshot 2020-02-06 at 17 20 08 " src="https://user-images.githubusercontent.com/2213269/73956330-18ebeb80-4905-11ea-9248-8b6dab302228.png">

And then doing a `2s///`:

<img width="732" alt="Screenshot 2020-02-06 at 17 20 23 " src="https://user-images.githubusercontent.com/2213269/73956378-27d29e00-4905-11ea-9424-494668466d98.png">

---

The replacement with blank lines seems to work for as long as nothing ever wraps around. But as soon as text is wrapped, the calculation goes wrong. I guess you would need to extrapolate the number of lines to clear (parse the message text line-by-line and divide line length by buffer window width).

**Comment by trygveaa** [comment]
That is strange, it doesn't happen for me:
![image](https://user-images.githubusercontent.com/601966/73958967-f52aa480-4908-11ea-9acc-446c2c0a7ac9.png)
(Without line breaks that is. Blank lines when the message had line breaks is expected, because unfortunately it's not possible to delete lines without clearing the whole buffer).

Wee-slack doesn't handle any line wrapping itself, that is done by weechat, so this seems like a bug in weechat to me. What happens if you press Ctrl-l after deleting the message?

**Comment by c-alpha** [comment]
> [...]
> Wee-slack doesn't handle any line wrapping itself, that is done by weechat, so this seems like a bug in weechat to me. What happens if you press Ctrl-l after deleting the message?

Ctrl-L does clear the "orphan" lines below the "(deleted)" lines.

**Comment by trygveaa** [comment]
Okay, now I can reproduce it. The reason I couldn't reproduce it last time seems to be that it only happens when the weechat window is certain sizes.

This is a bug in weechat as far as I can see. I opened an issue there: https://github.com/weechat/weechat/issues/1449
