### ISSUE TITLE
workflow robot threaded messages not in threads

### ISSUE THREAD

**Issue by carnott-snap** [wee-slack/wee-slack#749]
Thread messages sent by workflow robots, see [docs](https://slack.com/help/articles/360035692513), show up in channel logs and not thread logs. `/slack rehistory` does not fix this.

**Comment by trygveaa** [comment]
Do you have an example of a workflow robot? What's the easiest way to reproduce this?

**Comment by carnott-snap** [comment]
@trygveaa look at the [linked docs](https://slack.com/help/articles/360035692513), they should allow you to create one and reproduce the behaviour. I can post logs from my tests, but it should be trivial to reproduce.

**Comment by trygveaa** [comment]
It seems that I don't have any paid team where I have access to creating workflows.

**Comment by carnott-snap** [comment]
Hmm, that is certainly where I produced the issue, but I was not aware that feature was paid only, my apologies. Happy to provide logs or other info to assist.

**Comment by trygveaa** [comment]
Could you post the json of a message triggering this issue? Either by enabling `record_events` and finding it in `/tmp/weeslack-debug`, by calling the `channels.history` api or by printing `message_json` in `process_message`.
