### ISSUE TITLE
feature: parse HAR files

### ISSUE THREAD

**Issue by waynew** [wee-slack/wee-slack#759]
I've been exploring alternate clients and wee-slack is pretty awesome. But it would be even better if it could parse HAR files like Ripcord does.

I'm not sure exactly how it's done, and it sounds like there might be a bit of magic involved from one of the issues (said they used stuff from a response maybe?), but it would be pretty awesome if wee-slack could parse them. That would eliminate the need to install another app - which for community Slack's can be a dealbreaker.

**Comment by trygveaa** [comment]
You mean for getting the login token? Going via a HAR file seems like a cumbersome solution. You can instead get the token directly. emacs-slack has it described in their readme: https://github.com/yuya373/emacs-slack#how-to-get-token
You can use the token you get from that in `/set plugins.var.python.slack.slack_api_token [YOUR_SLACK_TOKEN]`

**Comment by waynew** [comment]
Ah! That'll certainly do :+1:
