### ISSUE TITLE
Failed connecting to slack team

### ISSUE THREAD

**Issue by THE-Alan-Hicks** [wee-slack/wee-slack#760]
Greetings,

I've been using wee-slack for a couple years now, but a few days ago it quit working correctly. When I start weechat, the screen is populated with channels and I can view the contents of those channels, but they never update. (In other words, if I connect at 9:00 a.m, I can see everything before 9:00 a.m., but never anything after that.) Furthermore, channel 1:weechat is filled with the following message repeated every few seconds:

  Failed connecting to slack team XXXXXXXX.slack.com, retrying.

Furthermore, it somehow sets my status to auto-away and anything I type into a channel apparently never reaches the slack servers. I'm currently using the latest version from HEAD but I've also tried version 2.4.0 recently. Before this issue, I was running version 2.2.0 for many months without issue.

**Comment by trygveaa** [comment]
Try to enable [debug mode](https://github.com/wee-slack/wee-slack#development) and look for `connect failed with exception` in the slack_debug buffer that appears. That should give you the reason it's failing to connect.

> Furthermore, it somehow sets my status to auto-away

It's Slacks servers that sets you auto-away. They have always done so, but wee-slack haven't shown it before.

> I'm currently using the latest version from HEAD but I've also tried version 2.4.0 recently. Before this issue, I was running version 2.2.0 for many months without issue.

Does it work if you try 2.2.0 again?

**Comment by THE-Alan-Hicks** [comment]
Thanks for getting back to me.

No, it does not work with version 2.2.0, version 2.4.0, or HEAD.

Here's the relevant information from the debug buffer:
13:07 error: [Errno 4] Interrupted system call
13:07 DEBUG: connect failed with exception:
13:07 Traceback (most recent call last):
13:07   File "/home/alan/.weechat/python/autoload/wee_slack.py", line 1409, in connect
13:07     ws = create_connection(self.ws_url, sslopt=sslopt_ca_certs)
13:07   File "/usr/lib64/python2.7/site-packages/websocket/_core.py", line 494, in create_connection
13:07     websock.connect(url, **options)
13:07   File "/usr/lib64/python2.7/site-packages/websocket/_core.py", line 217, in connect
13:07     options.pop('socket', None))
13:07   File "/usr/lib64/python2.7/site-packages/websocket/_http.py", line 120, in connect
13:07     sock = _open_socket(addrinfo_list, options.sockopt, options.timeout)
13:07   File "/usr/lib64/python2.7/site-packages/websocket/_http.py", line 186, in _open_socket
13:07     raise error
13:07 error: [Errno 4] Interrupted system call

**Comment by trygveaa** [comment]
This looks like the same issue as #679. It's fixed by upgrading websocket-client version 0.56.0 or greater.

**Comment by THE-Alan-Hicks** [comment]
Thanks for the heads up. I've updated websockets to the latest release and while this hasn't entirely fixed things, has improved them quite a bit. The connection failure messages have vanished and things I type into a buffer go into the appropriate slack channel, but the buffers themselves aren't updating when new content appears.

Based on this, I believe I've probably got some old libraries laying around that need to be upgraded rather than a problem with wee-slack itself.

**Comment by trygveaa** [comment]
> I've updated websockets

Do you really mean websockets? That is a [different package](https://pypi.org/project/websockets/) that is not relevant. The one that's used is https://pypi.org/project/websocket_client/
