### ISSUE TITLE
Error on (un)subscribe to a thread

### ISSUE THREAD

**Issue by virus-found** [wee-slack/wee-slack#764]
Subscription to thread is a highly desirable feature indeed.

But all my attempts to (un)subscribe always fail with
```
Error: Couldn't add thread subscription: not_allowed_token_type
```

**Comment by trygveaa** [comment]
Unfortunately, (un)subscribing is not officially supported in the API, so it doesn't work with legacy or OAuth tokens (the two token types described in the readme). To use it you have to pull the token out of the web client. Note that this token can't be revoked, so be careful with it. I haven't quite decided how to document this yet, but in the mean time you can read [this description](https://github.com/yuya373/emacs-slack#how-to-get-token) on how to get such a token.
