### ISSUE TITLE
RFE: allow searching history

### ISSUE THREAD

**Issue by sanjayankur31** [wee-slack/wee-slack#765]
Would it be possible to allow searching of channel histories, similar to how the slack web UI allows it?

**Comment by trygveaa** [comment]
There are some limited options for searching available. You can either press ctrl-r to search the history in the current buffer (though, it won't search further back than what's in the buffer), or you can use the [grep.py script](https://weechat.org/scripts/source/grep.py.html/) to search your log files.

As for searching through messages you have not logged, that is not implemented. #485 is open for that, so I'll close this as a duplicate.
