### ISSUE TITLE
file download does not appear to work on non-public Slack

### ISSUE THREAD

**Issue by waynew** [wee-slack/wee-slack#767]
I just added a file download location, and it *appeared* to work, but when I tried to open the image it turned out that it was an HTML file. Looks like it wasn't properly downloading the file, or perhaps it wasn't providing the token correctly?

It definitely failed for my private workspace, I haven't tried it on a public workspace yet.

**Comment by trygveaa** [comment]
Hm, I can't reproduce this. What you're saying is that you set `plugins.var.python.slack.files_download_location`, and the files that appeared in that directory contained html markup?

What did the html file contain?

> It definitely failed for my private workspace, I haven't tried it on a public workspace yet.

What do you mean by public workspace? I'm not aware of Slack having that.

**Comment by waynew** [comment]
A Slack that anyone can join? Though they do have to sign up via an app.

Anyway, here's the page that gets saved instead of the file.
[not-an-image.txt](https://github.com/wee-slack/wee-slack/files/4525127/not-an-image.txt)

**Comment by trygveaa** [comment]
> A Slack that anyone can join? Though they do have to sign up via an app.

As far as I know, the ones anyone can join are just using workarounds to give out invites, their not different from private workspaces. Anyways, that's probably not relevant.

I'm not sure how that could happen. Can you try this patch

```
diff --git a/wee_slack.py b/wee_slack.py
index 23330ca..712e689 100644
--- a/wee_slack.py
+++ b/wee_slack.py
@@ -3069,6 +3069,7 @@ def download_files(message_json, team):
         for fileout in fileout_iter(os.path.join(download_location, filename)):
             if os.path.isfile(fileout):
                 continue
+            print('download token: `{}`'.format(team.token))
             w.hook_process_hashtable(
                 "url:" + f['url_private'],
                 {
```

It should print your token when downloading a file. Check if it prints the same token as you have registered. Also, what kind of token are you using (how did you get it)? And what version of weechat are you using?

**Comment by waynew** [comment]
I'm using the token that I get from https://github.com/yuya373/emacs-slack#how-to-get-token - `weechat -v` gives me 1.9.1

**Comment by trygveaa** [comment]
WeeChat 1.9.1 doesn't support setting HTTP headers for downloads, so we can't download files from Slack. You need at least WeeChat version 2.2.

**Comment by trygveaa** [comment]
I added info about it in the option description.

**Comment by waynew** [comment]
I've upgraded to weechat 2.8 but now I'm seeing it just simply not download.
It's definitely getting to the `w.hook_process_hashtable` line... ah. I see what's going on here - the `f['url_private']` seems to not be present...

**Comment by waynew** [comment]
haha, oops, my bad. I was redefining f :upside_down_face:

**Comment by waynew** [comment]
cool, yeah it's working now :tada:
