### ISSUE TITLE
Windows 10 Cygwin issues

### ISSUE THREAD

**Issue by xmadscientist** [wee-slack/wee-slack#768]
Wee-Slack works PERFECT on my Mac setup, but I've been having a lot of trouble setting it up and getting it working with my Windows 10 PC. I'm trying to use Cygwin to run it. 

When I try to load wee-slack, I get the following errors:

![image](https://user-images.githubusercontent.com/33380015/80624479-f4d20f00-8a08-11ea-883d-8e09ef4ae261.png)

I have python 3 installed and have installed websocket-client and even websocket via pip/pip3. I also followed the installation instructions down to a T in the readme. What am I missing?

**Comment by trygveaa** [comment]
First check that weechat is using python 3 by running `/python version`. Next, check if you can import python outside of weechat by running `python3` in a shell and then running `import websocket`.

If that works run `websocket.__path__` in the repl to check where it is installed. Compare that with the output of `/python eval import sys; print(sys.path)` in weechat.

**Comment by xmadscientist** [comment]
Running `/python version` gives me this: 
![image](https://user-images.githubusercontent.com/33380015/80625887-0caa9280-8a0b-11ea-84f1-b7e5d1812216.png)

I tried running `python3` in a shell and got this:

![image](https://user-images.githubusercontent.com/33380015/80626180-47acc600-8a0b-11ea-9565-f67da2665942.png)


Could this be what's causing the issue?

**Comment by trygveaa** [comment]
> I tried running python3 in a shell and got this:

That's strange. What does `which python`, `which pip` and `which pip3` output?

> Running python also gives me this:

That gives you python 2 as expected, so won't help for debugging the issue, but interesting that it works while python 3 doesn't.

> websocket via pip/pip3

Don't install `websocket`. `websocket-client` unfortunately uses the same name when importing, so they may conflict with each other. But that would give you a different error message, so I don't think that's the problem.

**Comment by xmadscientist** [comment]
`which python`:
![image](https://user-images.githubusercontent.com/33380015/80628281-5b0d6080-8a0e-11ea-98fa-9c519907fe81.png)

`which pip`:
![image](https://user-images.githubusercontent.com/33380015/80628305-63fe3200-8a0e-11ea-8150-fe3e8984486c.png)

`which pip3`:
![image](https://user-images.githubusercontent.com/33380015/80628333-6eb8c700-8a0e-11ea-9f80-9d9f849b6349.png)

See any discrepancies?

**Comment by trygveaa** [comment]
Hm, I don't know much about cygwin, so not sure why it would place python3 and pip3 in those paths. How did you install python3?

You could try making python3 executable and see if that fixes the permissions problem by running:
```
chmod +x /cygdrive/c/Users/User/AppData/Local/Microsoft/WindowsApps/python3
```

**Comment by xmadscientist** [comment]
Thanks for sending that command over.

Very weird, even when running it as admin, I keep getting this error:

![image](https://user-images.githubusercontent.com/33380015/80631547-1e903380-8a13-11ea-9b62-d9f4323e9615.png)

**Comment by xmadscientist** [comment]
Any ideas?

**Comment by trygveaa** [comment]
No, as I said, I don't know much about cygwin. It seems like there is something wrong with your python 3 installation though. You didn't answer this question:

> How did you install python3?

**Comment by xmadscientist** [comment]
Sorry, I didn't see that part of your message. It's been a while now but I believe I downloaded a setup exe from Python's official website and installed it that way.

**Comment by trygveaa** [comment]
Try these commands and report what they output:

In weechat:
```
/python eval import sys; print(sys.path)
/plugin listfull python
```

The second one will output lots of lines. I don't need all of them, just the first one which looks like this: `python [v2.8]: Support of python scripts (<path>)`

Then run these in a shell:
```
pip3 show -f websocket-client
ldd <path>
```

Replace `<path>` with the path you got in `python [v2.8]: Support of python scripts (<path>)` from the second command in weechat.

**Comment by xmadscientist** [comment]
Thanks for that!

`/python eval import sys; print(sys.path)`:

![image](https://user-images.githubusercontent.com/33380015/80733645-3925e380-8acb-11ea-936c-d4a89931c5ed.png)

`/plugin listfull python`:

![image](https://user-images.githubusercontent.com/33380015/80733694-45aa3c00-8acb-11ea-9b58-78e46ca72e65.png)

`pip3 show -f websocket-client`:

![image](https://user-images.githubusercontent.com/33380015/80733829-75f1da80-8acb-11ea-871f-4514504155b7.png)

And the last one:

`ldd <path in second screenshot>`:
![image](https://user-images.githubusercontent.com/33380015/80733986-b5b8c200-8acb-11ea-9db2-33f3b4da7a31.png)


See anything funky here?

**Comment by trygveaa** [comment]
So, weechat is using your global python 3 installation at `/usr/lib/python3.6`, but you also have another installation in appdata. When running `pip3` you are using the installation in appdata, so weechat doesn't see what you install there.

Do you have `/usr/bin/pip3` or `/usr/local/bin/pip3`? If so, try `/usr/bin/pip3 install websocket-client`.

**Comment by xmadscientist** [comment]
Looks like I had `usr/bin/pip3.8` (I also had just `pip` in there too) and the /usr/local/bin/ directory was empty. I ran `usr/bin/pip3.8 install websocket-client`. It installed and I tried to run weeslack again, but I got the same error. 

![image](https://user-images.githubusercontent.com/33380015/80737521-e0594980-8ad0-11ea-9e0d-47b7b76c7ab1.png)

Tried the same thing for all of the pip versions above but I'm still getting that same error on Weehcat.

**Comment by xmadscientist** [comment]
So I tried updating pip and did the same steps above to no avail. I did notice though that in the previous screenshot I sent (command with` print(sys.path)`), it was showing the path as /usr/lib/python3.6

**Comment by trygveaa** [comment]
So you have 3 python 3 installations?

Or have you upgraded python without upgrading the python plugin for weechat? Though, if that was the reason, I would have expected the plugin to fail when loading, but apparently you have some of 3.6 left.

These are things you can try:
1. Install a new version of the weechat python plugin, which is linked against 3.8.
2. Find where you have `pip3.6`, if you have that somewhere.
3. If none of that works, you should be able to use a virtualenv to install the dependency, and launch weechat inside the virtualenv.

**Comment by xmadscientist** [comment]
Looks like I got it working by just copying the contents of `/usr/lib/python3.8/site-packages` to `/usr/lib/python3.6/site-packages`.

For anyone else encountering this issue, I got the first directory by running `pip show -f websocket-client` and I got the second directory by going in Weechat and running `/python eval import sys; print(sys.path)` and looking for the directory that says "site-packages".

**Comment by trygveaa** [comment]
Great that you got it to work, even if it was a bit hacky solution.
