### ISSUE TITLE
ModuleNotFoundError: No module named 'websocket'

### ISSUE THREAD

**Issue by ahmedelgabri** [wee-slack/wee-slack#770]
```
python: stdout/stderr (?): Traceback (most recent call last):
python: stdout/stderr (?):   File "/Users/ahmed/.config/weechat/python/autoload/wee_slack.py", line 35, in <module>
python: stdout/stderr (?):     from websocket import ABNF, create_connection, WebSocketConnectionClosedException
python: stdout/stderr (?): ModuleNotFoundError: No module named 'websocket'
python: unable to parse file "/Users/ahmed/.config/weechat/python/autoload/wee_slack.py"
```
- I have installed `weechat` with homebrew
- My default python is `3.7.7` 
- I use a custom `WEECHAT_HOME=~/.config/weechat`
- if edit `wee_slack.py` inside `cd $WEECHAT_HOME/python` to only have this 

```python
from websocket import ABNF, create_connection, WebSocketConnectionClosedException

print(ABNF)
```

And run `python wee_chat.py` it works fine & prints `<class 'websocket._abnf.ABNF'>`
- `pip list` & `pip2 list` both contain `websocket-client 0.57.0`

So, I'm not sure where is the problem or why it doesn't work when I launch `weechat`?

**Comment by trygveaa** [comment]
I would assume the problem is that weechat uses python 3, and pip uses python 2, but to verify run this in weechat:
```
/python eval import sys; print(sys.path)
```

And these two in a shell:
```
pip2 show -f websocket-client | grep Location
pip3 show -f websocket-client | grep Location
```

And report what they output.

**Comment by ahmedelgabri** [comment]
> I would assume the problem is that weechat uses python 3, and pip uses python 2, but to verify run this in weechat:
> 
> ```
> /python eval import sys; print(sys.path)
> ```

This was enough to show the problem & I have no clue were this `3.8` version came from. Will have to check then.

```
['/Users/ahmed/.config/weechat/python', '', '/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python38.zip', '/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8',
'/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/lib-dynload', '/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages']
```

There is no need for this, but here you go

> And these three in a shell:
> 
> ```
> pip show -f websocket-client | grep Location
> pip2 show -f websocket-client | grep Location
> pip3 show -f websocket-client | grep Location
> ```
> 
> And report what they output.

```
Location: /usr/local/lib/python3.7/site-packages
Location: /Users/ahmed/Library/Python/2.7/lib/python/site-packages
Location: /usr/local/lib/python3.7/site-packages
```

Thanks, for the tips.
