### ISSUE TITLE
Couldn't load members for channel ....  Error: ratelimited

### ISSUE THREAD

**Issue by d3xt3r01** [wee-slack/wee-slack#775]
Upon connection I get tons of these messages in the server buffer.... for about 20 seconds .. about > 2000 messages for various channels...

```
13:14:49 ....slack.com =!= | Couldn't load members for channel %.... Error: fetch_members_failed
13:14:49 ....slack.com =!= | Couldn't load members for channel %.... Error: fetch_members_failed
13:14:49 ....slack.com =!= | Couldn't load members for channel %.... Error: fetch_members_failed
13:14:49 ....slack.com =!= | Couldn't load members for channel %.... Error: fetch_members_failed
13:14:49 ....slack.com =!= | Couldn't load members for channel %.... Error: fetch_members_failed
13:14:49 ....slack.com =!= | Couldn't load members for channel %.... Error: fetch_members_failed
13:14:49 ....slack.com =!= | Couldn't load members for channel %.... Error: fetch_members_failed
13:14:49 ....slack.com =!= | Couldn't load members for channel %.... Error: fetch_members_failed
13:14:49 ....slack.com =!= | Couldn't load members for channel %.... Error: fetch_members_failed
13:14:49 ....slack.com =!= | Couldn't load members for channel %.... Error: fetch_members_failed
.............
13:15:19 ....slack.com =!= | Couldn't load members for channel %.... Error: ratelimited
13:15:19 ....slack.com =!= | Couldn't load members for channel %.... Error: ratelimited
13:15:19 ....slack.com =!= | Couldn't load members for channel %.... Error: ratelimited
13:15:19 ....slack.com =!= | Couldn't load members for channel %.... Error: ratelimited
```

**Comment by trygveaa** [comment]
You say "Error: ratelimited" in the title, but the error message says "Error: fetch_members_failed". Do you see both, or which is it?

Are any of the channels listed multiple times, or are all the error messages unique?

**Comment by d3xt3r01** [comment]
My bad, yeah, Both.
Initially they're fetch_members_failed .. then it moves to ratelimited !

**Comment by d3xt3r01** [comment]
```$ grep -ic fetch_members_failed \$channel_20200525*
155
$ grep -ic ratelimited \$channel_20200525*
2229```

**Comment by d3xt3r01** [comment]
I guess they're unique
```
$ awk -F '%' '{print $2}' \$channel_20200525* | wc -l
2386
$ awk -F '%' '{print $2}' \$channel_20200525* | sort -u |  wc -l
2385
```

**Comment by d3xt3r01** [comment]
I guess it's trying to get members of all channels on this instance for some reason ?

**Comment by trygveaa** [comment]
Yeah, it tried to get the members for all shared channels. We only need the member list for the channels you have joined, so I changed it to that now.

I'm not sure when the `fetch_members_failed` errors occurs, but I'm guessing it only happens for channels you are not a member of (it doesn't happen for all channels you are not a member of though). If so, it should be fixed now.

I haven't implemented handling of rate limiting yet, but unless you are a member of many shared channels, you shouldn't run into it anymore.

**Comment by d3xt3r01** [comment]
Can confirm it works. Thanks !
