### ISSUE TITLE
Connecting to slack with SSO enabled behind firewall and zero app permission

### ISSUE THREAD

**Issue by tobocop2** [wee-slack/wee-slack#776]
The only documented ways of connecting to slack are using the oauth token which requires the permission to access external applications and using the session token. 

Where I work I'm unable to have app permission for wee-slack and 'my.slack.com' is blocked behind the firewall. Is there any other way to get the session token? I've tried using the token and enterprise token values in local storage without any success. I was hoping maybe there could be another way to get the session token referenced in the README without accessing 'my.slack.com'

**Comment by trygveaa** [comment]
`my.slack.com` is just a link that works for all teams. You can replace `me` with your team name.

**Comment by tobocop2** [comment]
I tried pasting the following as outlined in the README:

```
javascript:window.prompt("Session token:", TS.boot_data.api_token)
```

I don't get any window prompts. I tried just running that code in the console as well and it doesn't work. I tried also using the token values in the cookies and those do not work either.

**Comment by trygveaa** [comment]
Write just `TS.boot_data.api_token` in the console, and it should print the token.

**Comment by tobocop2** [comment]
```
ReferenceError: TS is not defined
```

**Comment by trygveaa** [comment]
You have to be on the customization page, i.e. where you can add custom emojis.

**Comment by tobocop2** [comment]
ok I got the token, this time it seems to be the right one, but now I'm stuck with this error:

```
Failed connecting to slack team with token <token>  will not retry after too many failed attempts. If this persists, try increasing slack_timeout. Error (code -2):
```

**Comment by trygveaa** [comment]
Have you tried increasing `slack_timeout` as the error message says?

It could probably be because it's blocked by the firewall/proxy too. You can check if it works outside of wee-slack. Try to go to `https://slack.com/api/rtm.connect?token=<your token>`. If that works try to connect to the websocket url it returns.

**Comment by tobocop2** [comment]
I think I resolved the proxy/cert issue now, it doesn't just fail as before, but just hangs. Any idea how to troubleshoot that now? It's stuck on Connecting to 1 slack team.

**Comment by trygveaa** [comment]
You probably have to set proxy authentication. Configure the proxy with the `/proxy` command instead of editing the code.

**Comment by tobocop2** [comment]
yeah i did it directly with weechat, not with the code, I just pasted the code directly from wee_slack into a python to see the explicit reason for failure (i set local variables in the shell for the proxy and port) 

I have the proxy settings set correctly and the proxy_curl setting set to the name of my http proxy. Right now,  it's still stuck on

```
Connecting to 1 slack team.
```

**Comment by trygveaa** [comment]
Try to enable [debug mode](https://github.com/wee-slack/wee-slack#development) and check what's printed there.

**Comment by tobocop2** [comment]
I am getting zero useful logging information @trygveaa 

After some digging, it's stuck in the following conditional:

https://github.com/wee-slack/wee-slack/blob/3e8f96f6ca004be3f006d36d83f0430683b7eb76/wee_slack.py#L583

**Comment by trygveaa** [comment]
That sounds like something caused by your proxy or other part of your network stack. If you still get 403 outside of wee-slack, that's probably the reason. I don't know anything about your proxy, so can't really help you with that.

**Comment by tobocop2** [comment]
OK, i just confirmed that the websocket url is in fact blocked by the corporate firewall. I have no idea how slack itself is working from the web client, but cannot access that websocket url programmatically. I am assuming at this point I will have to use official slack client :( 

Given the official slack client works, I feel like there must be a way that I can get around this but it looks like I will be stuck with the official client for a while now.

**Comment by trygveaa** [comment]
If you look at the network calls for the web client you can see that it connects to `wss-primary.slack.com`, while wee-slack connects to what the `rtm.start`/`rtm.connect` API methods returns, which is `cerberus-xxxx.lb.slack-msgs.com` (at least for me), so that might be the reason.

I don't know if it's possible to make wee-slack work with the same domain that the web client uses.
