### ISSUE TITLE
formatted_name renders variables as text when opening threads

### ISSUE THREAD

**Issue by lxcode** [wee-slack/wee-slack#783]
https://github.com/wee-slack/wee-slack/blob/3d050458497f4ce97d6586fc7f9006abd242e773/wee_slack.py#L2493

When displaying a thread in the sidebar, formatted_thread grabs the value of buflist.format.indent and includes it before the name/hash of the thread. If you have a custom setting for indent, such as:

`indent = "${color:237}${if:${buffer.next_buffer.local_variables.type}=~^(channel|private)$?├─:└─}"`

The string is printed out entirely literally, instead of the conditionals and variables being evaluated. I've worked around it in my local install just by putting a hokey `return "{}+{}".format(" ", name)`, but I'm not familiar enough with weechat to know what a better fix would be.

**Comment by trygveaa** [comment]
If you want the tree view to display nicely, you have to change the option to account for threads. You can use one of these depending on the style you want:

```
"${color:237}${if:${slack_thread}?──:${if:${buffer.next_buffer.local_variables.type}=~^(channel|private)$?├─:└─}}"
```

```
"${color:237}${if:${buffer.next_buffer.local_variables.type}!~^(channel|private)$||${slack_thread}?└─:${if:${buffer.local_variables.slack_type}==thread?│ :├─}}"
```

**Comment by trygveaa** [comment]
I had to remove the indent value from threads completely, as it caused various issues (see afe461ceaf0536b4d74fd17051f6e06500e2f73d for details). That means that the option values I wrote above won't work anymore. But it's still possible to get the same nice indenting of threads, you just have to set the option differently. This is the new values you have to use to get the same display as the ones I wrote in the last comment:

```
/set buflist.format.indent "${color:237}${if:${buffer.local_variables.slack_type}==thread?├───:${if:${buffer.next_buffer.local_variables.type}=~^(channel|private)$?├─:└─}}"
```

```
/set buflist.format.indent "${color:237}${if:${buffer.local_variables.slack_type}==thread?${if:${buffer.next_buffer.local_variables.slack_type}==thread?│ ├─:│ └─}:${if:${buffer.next_buffer.local_variables.type}=~^(channel|private)$?├─:└─}}"
```

Choose one of them depending on the style you want.
