### ISSUE TITLE
python errors trying to autoload wee_slack.py (newest version)

### ISSUE THREAD

**Issue by mckila** [wee-slack/wee-slack#786]
python: stdout/stderr (?): Traceback (most recent call last):
 python: stdout/stderr (?):   File "/Users/mckila/.weechat/python/autoload/wee_slack.py", line 35, in
 <module>
  python: stdout/stderr (?):     from websocket import ABNF, create_connection,
  WebSocketConnectionClosedException
  python: stdout/stderr (?): ModuleNotFoundError: No module named 'websocket'
  python: unable to parse file "/Users/mckila/.weechat/python/autoload/wee_slack.py"
  python: stdout/stderr (?): Traceback (most recent call last):
  python: stdout/stderr (?):   File "/Users/mckila/.weechat/python/autoload/slack.py", line 35, in <module>
  python: stdout/stderr (?):     from websocket import ABNF, create_connection,
  WebSocketConnectionClosedException
  python: stdout/stderr (?): ModuleNotFoundError: No module named 'websocket'
  python: unable to parse file "/Users/mckila/.weechat/python/autoload/slack.py"
  script: 364 scripts for WeeChat 2.9
  Plugins loaded: alias, buflist, charset, exec, fifo, fset, irc, logger, lua, perl, python, relay, ruby,
  script, spell, tcl, trigger, xfer

not sure what is going on here python 3 dependencies appear to be satisfied

**Comment by trygveaa** [comment]
You need to install the websocket-client dependency, see the readme. If you have installed it, make sure it's in a place weechat can find it.

**Comment by mckila** [comment]
thanks for the quick response bro!.. i have installed it.. just not quite sure how to tell weechat were it is at tho lol

**Comment by mckila** [comment]
oh i see this https://github.com/wee-slack/wee-slack/issues/540

**Comment by trygveaa** [comment]
Yes, for pyenv you have to do what I said in the comment there.

Might be easier to install websocket-client with your distros package manager instead.

**Comment by mckila** [comment]
i wish i could but im on a mac, and brew doesnt seem to have it.  That being said i think i am going the docker route for weechat..  seems like python setup is so touchy (especially on macs)..  and i am in a good space with my spacevim editor so  i dont wanna change anything that being said.. it might just be easier running the slack client in a docker machine.  (fingers crossed).. i love the client and the terminal workflow it adds to.. just not all the python management. :p 

cheers!

**Comment by trygveaa** [comment]
Right, on mac I guess you have to install it with pip. You could install it globally with pip or use a normal virtualenv instead of pyenv though. Both those options should work fine.
