### ISSUE TITLE
add a slack_buffer info that behave like irc_buffer

### ISSUE THREAD

**Issue by pascalpoitras** [wee-slack/wee-slack#787]
In my buflist, I have an expand/collapse arrow that I can click on to hide/show irc channels and privates under their server. Instead of setting a localvar on all the buffer, i set it only on the server buffer. I get the server buffer pointer using the info [irc_buffer](https://weechat.org/files/doc/devel/weechat_plugin_api.en.html#_infolist_get). I wonder if you could create an info like slack_buffer, which behave like irc_buffer but return the pointer of a slack buffer

**Comment by unhammer** [comment]
I see this was closed, how did you solve it?

**Comment by pascalpoitras** [comment]
@unhammer I use the new buffer info available in weechat 4.1.0 

you give the full name of the buffer to the buffer info

for example ${info:buffer,full_name_here}

I created a trigger to collapse/expand matrix and slack if you are interested

[collapse/expand](https://gist.github.com/pascalpoitras/8406501#utils_search_server_buffer_ptr)
