### ISSUE TITLE
No thread notifications on reconnect

### ISSUE THREAD

**Issue by hasufell** [wee-slack/wee-slack#789]
When I reconnect to weechat slack, I have no idea whether any of the threads I am subscribed to received new replies. I'm not even sure I will see it if I'm highlighted.

**Comment by trygveaa** [comment]
What version of wee-slack are you running?

**Comment by hasufell** [comment]
2.6.0

**Comment by trygveaa** [comment]
Try the latest version from master. It has some fixes that haven't been released yet.

**Comment by hasufell** [comment]
Doesn't work. Even when I'm connected I don't get notifications. I have to open the thread explicitly.

**Comment by trygveaa** [comment]
What do you mean by notifications? By default, a line is printed in the team buffer. If you rather want a buffer to open and see it in the hotlist, set [`auto_open_threads`](https://github.com/wee-slack/wee-slack/blob/master/docs/Options.md#auto_open_threads) to `true`.

**Comment by trygveaa** [comment]
Also see [`notify_subscribed_threads`](https://github.com/wee-slack/wee-slack/blob/master/docs/Options.md#notify_subscribed_threads).

**Comment by hasufell** [comment]
Cool, that did the trick. Except the thread is shown below an unrelated channel :confused:

**Comment by trygveaa** [comment]
Hm, that could be a bug. It appears in the correct place for me, but wee-slack doesn't explicitly set the position of the buffer. I'll have to look into it.

**Comment by hasufell** [comment]
Sidenote: the thread is from a private conversation and it ends up below a channel that probably has a lot of traffic. I'm wondering if maybe there are thread name collisions?

**Comment by trygveaa** [comment]
I had `autosort.py` loaded, which moved it to the correct place. Without it, it's just placed last. I guess that's what happens for you?

I'll change it to be placed after the channel it belongs to.

> Sidenote: the thread is from a private conversation and it ends up below a channel that probably has a lot of traffic. I'm wondering if maybe there are thread name collisions?

Thread id's are only unique within a channel, but I don't think that is what's causing the problem.

**Comment by hasufell** [comment]
I also have autosort loaded. My config is

```
[sorting]
case_sensitive = off
debug_log = off
replacements = ""
rules = ""
signal_delay = 5
signals = "buffer_opened buffer_merged buffer_unmerged buffer_renamed"
sort_limit = 100
sort_on_config_change = on

[v3]
helpers = "{"core_first": "${if:${buffer.full_name}!=core.weechat}", "irc_raw_first": "${if:${buffer.full_name}!=irc.irc_raw}", "irc_raw_last": "${if:${buffer.full_name}==irc.irc_raw}", "hashless_name": "${info:autosort_replace,#,,${info:autosort_escape,${buffer.name}}}", "script_or_plugin": "${if:${script_name}?${script_name}:${plugin}}"}"
rules = "["${core_first}", "${info:autosort_order,${info:autosort_escape,${script_or_plugin}},core,*,irc,bitlbee,matrix,slack}", "${script_or_plugin}", "${irc_raw_first}", "${server}", "${info:autosort_order,${type},server,*,channel,private}", "${hashless_name}", "${buffer.full_name}", "irc.server.*.&* = 0", "irc.server.*.#* = 1", "irc.server.*.\\*status = 2"]"
```

**Comment by trygveaa** [comment]
Hm, then I don't get why it's not working. What's the output of `/buffer`?

**Comment by hasufell** [comment]
`/buffer` shows that the thread is indeed a child of the private conversation namespace, so I guess this could be some sort-related issue.

From what I see the sorting is as follows:

1. private channels a,b,c sorted
2. public channels a,b,c sorted
  - these are mixed with threads from private convos, so `trygveaa.acd` thread will come after `#random` channel and before `#zoo` channel
3. conversations a,b,c sorted

**Comment by trygveaa** [comment]
Turns out this was caused by threads in direct messages having the wrong localvar type set. It should be correct with the latest commit.

**Comment by hasufell** [comment]
I can confirm this works. Thanks!
