### ISSUE TITLE
Uses deprecated APIs to be removed on 24th February 2021?

### ISSUE THREAD

**Issue by matthijskooijman** [wee-slack/wee-slack#792]
I got an e-mail from slack, saying:

> The Conversations API is a one-size-fits-all replacement for a variety of APIs
> that are used to read and write information about channels, private channels,
> direct messages and multi-party direct messages. On 24th February 2021, Slack
> will end support for any methods preceding the Conversations API.
> 
> We have detected that you've created Slack apps using these legacy methods. If
> users expect your app to work in channels of any kind, you'll need to verify use
> of the Conversations API by following these suggested next steps.

I believe the only Slack API client I use, is wee-slack, so I'm guessing this applies to wee-slack.

Looking at their deprecation tool, it says I have a single app called "Slack API Tester" using the deprecated "mpim.history" method. Interestingly enough the last use is august 17th, but maybe the deprecated APIs are only used sometimes by wee-slack.

The code seems to confirm that non-conversations APIs are indeed being used still: https://github.com/wee-slack/wee-slack/blob/31f2970b9cee84398a8bea8bcde2b46f84bff217/wee_slack.py#L77-L124

I highly suspect that this is not a surprise, but I thought it would be good to have an open issue to track this issue.

**Comment by trygveaa** [comment]
Yes, I know about this and have it on my todo list, but thanks for the notice.

Initially I wanted to wait as long as possible to do this because it wasn't possible to mark channels as read with the new API, and Slack said they didn't want to support it. However, I recently saw that they have added it after all \o/, so I don't think there's any reason to wait anymore.

**Comment by sdelafond** [comment]
Hi @trygveaa, is this still on your radar at all? :)

**Comment by trygveaa** [comment]
@sdelafond: Yeah. As you may have seen, I haven't worked on wee-slack lately, but I still hope/plan to get this done before February 24.

**Comment by sdelafond** [comment]
Cool, thanks for confirming that. And thanks for all your work on wee-slack: it's a life-changer for a lot of us!

**Comment by trygveaa** [comment]
As far as I can see, using the new API the same way works fine (except for channels not being marked as unread when wee-slack loads if background_load_all_history is set to false, see details in the commit message).

I have done some testing and it seems to work fine for me. If you experience any issues with this, please open an issue.

**Comment by matthijskooijman** [comment]
Thanks!

I just updated to this revision and it seems to connect properly again (before, wee-slack failed to connect, not sure what the problem was). If I find anything weird with the new API, I'll let you know, if you don't hear anything, I guess everything is ok :-)
