### ISSUE TITLE
wee-slack hangs when trying to connect to slack

### ISSUE THREAD

**Issue by adam-drewery** [wee-slack/wee-slack#793]
Hi,

After authenticating with slack and typing `python reload slack`. I get a message saying "Connecting to 1 slack team." and then nothing happens. wee-slack becomes frozen and unresponsive.

What could be wrong?

Thanks,
Adam

**Comment by trygveaa** [comment]
> wee-slack becomes frozen and unresponsive.

What do you mean by this, all of weechat hangs, or that wee-slack doesn't do anything more? For how long?

Try to enable [debug mode](https://github.com/wee-slack/wee-slack#development) and check what is printed in the debug buffer that appears.

**Comment by adam-drewery** [comment]
My apologies, I'll clarify- all of weechat hangs, seemingly forever.
That said though, I've tried a few times now- I was about to see what http requests are being made by debugging with fiddler, but then it connected with no problems. Not sure if that's a coincidence or if the fiddler http proxy made something work differently.

If I run into the issue again I'll be sure to enable debug mode and see what the cause is. Thanks.

**Comment by trygveaa** [comment]
wee-slack unfortunately blocks weechat when connecting to the websocket (#239), because it's not easy to do this in a non-blocking way, so if the network hangs, or the domain is blocked by a firewall, it could cause weechat to hang.

I thought it had a timeout of this, but I see that the timeout was only used for normal http calls, not the websocket connection. I changed that to use the `slack_timeout` config now, so now it should at least not hang for a longer duration than that (default 20 seconds).

**Comment by trygveaa** [comment]
I don't think I can do more here without more info, so I'll close this.

**Comment by tshrinivasan** [comment]
I am getting the same issue, for past one week. 


Enabled logging with
/set plugins.var.python.slack.debug_mode on
/set plugins.var.python.slack.debug_level 5


Please check the below logs.

15:31 python: script "slack" unloaded
15:31 python: loading script "/home/shrini/.weechat/python/autoload/wee_slack.py"
15:31 python: registered script "slack", version 2.6.0 (Extends weechat for typing notification/search/etc on slack.com)
15:31 Connecting to 1 slack team.
15:31 python: stdout/stderr (slack): Traceback (most recent call last):
15:31 python: stdout/stderr (slack):   File "/home/shrini/.weechat/python/autoload/wee_slack.py", line 743, in handle_next
15:31 python: stdout/stderr (slack):     EVENTROUTER.handle_next()
15:31 python: stdout/stderr (slack):   File "/home/shrini/.weechat/python/autoload/wee_slack.py", line 736, in handle_next
15:31 python: stdout/stderr (slack):     self.handlers[function_name](j, self, team, channel, metadata)
15:31 python: stdout/stderr (slack):   File "/home/shrini/.weechat/python/autoload/wee_slack.py", line 3044, in handle_rtmstart
15:31 python: stdout/stderr (slack):     channels[item["id"]] = SlackMPDMChannel(eventrouter, users, login_data["self"]["id"], **item)
15:31 python: stdout/stderr (slack):   File "/home/shrini/.weechat/python/autoload/wee_slack.py", line 2400, in __init__
15:31 python: stdout/stderr (slack):     for user_id in kwargs["members"]
15:31 python: stdout/stderr (slack): KeyError: 'members'

**Comment by trygveaa** [comment]
@tshrinivasan: That issue should be fixed in the latest version, so please upgrade to that.

**Comment by tshrinivasan** [comment]
@trygveaa thanks for the quick reply.
got the recent version installed. 
all works now.

Tons of thanks for the great work.
