### ISSUE TITLE
redirect_uri must not contain anchor (#) tags. Passed URI: https://wee-slack.github.io/wee-slack/oauth#

### ISSUE THREAD

**Issue by krestivo-kdinfotech** [wee-slack/wee-slack#795]
I am trying to authorize the wee-slack app

> Something went wrong when authorizing wee-slack.
> Try going back to wee-slack and authorizing again. If problems persist, contact support for help.

> Error details
> redirect_uri must not contain anchor (#) tags. Passed URI: https://wee-slack.github.io/wee-slack/oauth#

Taking the # anchor out causes the first step of the auth to succeed, but then fails after pasting the command it shows into weechat:

> 6:23 ERROR: Couldn't get Slack OAuth token: bad_redirect_uri

**Comment by trygveaa** [comment]
Which version of wee-slack are you running? This was fixed in v2.6.0.

**Comment by krestivo-kdinfotech** [comment]
Upgrading fixed it, thank you!
