### ISSUE TITLE
Cannot send messages

### ISSUE THREAD

**Issue by wavexx** [wee-slack/wee-slack#797]
I started to have a new problem recently: messages I'm writing to threads do not appear in slack. The message is received by the python plugin, but nothing seems to happen...

```
16:26:21 | DEBUG: <@UJ20QKNP5>: test message
16:26:21 | DEBUG: Sent {"type": "message", "text": "<@UJ20QKNP5>: test message...
16:26:21 | DEBUG: RECEIVED FROM QUEUE
16:26:21 | DEBUG: SET FROM REPLY
16:26:21 | DEBUG: running reply
16:26:25 | DEBUG: RECEIVED FROM QUEUE
16:26:25 | DEBUG: SET FROM type
```

However I'm receiving messages normally.

**Comment by wavexx** [comment]
To continue, when the message is correctly shown, I also see a "reply ok" in the debug.

```
16:32:09 | DEBUG: REPLY {'ok': True, 'reply_to': 68, 'ts': '1601908329.059500', 'text':
         | "<@UJ20QKNP5>: test message ...
```

This is missing when I don't see my own messages.

**Comment by ecksun** [comment]
I have a similar problem that might be related, however I private messages doesnt work either, I get this error:

```
16:37 python: stdout/stderr (slack): Traceback (most recent call last):
16:37 python: stdout/stderr (slack):   File "/home/user/.weechat/python/autoload/wee_slack.py", line 743, in handle_next
16:37 python: stdout/stderr (slack):     EVENTROUTER.handle_next()
16:37 python: stdout/stderr (slack):   File "/home/user/.weechat/python/autoload/wee_slack.py", line 734, in handle_next
16:37 python: stdout/stderr (slack):     self.proc[function_name](j, self, team, channel, metadata)
16:37 python: stdout/stderr (slack):   File "/home/user/.weechat/python/autoload/wee_slack.py", line 3479, in process_reply
16:37 python: stdout/stderr (slack):     process_message(original_message_json, eventrouter, team=team, channel=channel, metadata={})
16:37 python: stdout/stderr (slack):   File "/home/user/.weechat/python/autoload/wee_slack.py", line 3355, in process_message
16:37 python: stdout/stderr (slack):     message = SlackMessage(subtype or "normal", message_json, team, channel)
16:37 python: stdout/stderr (slack):   File "/home/user/.weechat/python/autoload/wee_slack.py", line 2730, in __init__
16:37 python: stdout/stderr (slack):     self.ts = SlackTS(message_json['ts'])
16:37 python: stdout/stderr (slack): KeyError: u'ts'
```

**Comment by trygveaa** [comment]
Are you sure it's specific to thread? Multiple people have experienced this for messages in channels today. Some have experienced it earlier in the last weeks, but more often today.

The error from Slack is this (if it's the same): `{'code': 4, 'msg': 'cannot process message', 'source': 'gs-lhr-l3a6'}`

I guess there's some error on Slacks side, since sending it again works after some retries. Hopefully they will fix it (I have not reported it to them yet though).

Otherwise, I guess we have to retry sending. Error handling should be improved/implemented either way.

**Comment by trygveaa** [comment]
This might be related: https://status.slack.com/2020-10/e8c094cc99aabf64

**Comment by wavexx** [comment]
It's not exclusive to threads. How do I see the error? I don't have anything extra on the debug buffer.

**Comment by trygveaa** [comment]
Unfortunately, the logging is lacking and the error handling is missing here. I saw it by using this patch:

```
diff --git a/wee_slack.py b/wee_slack.py
index eb69b3f..a8697e8 100644
--- a/wee_slack.py
+++ b/wee_slack.py
@@ -714,10 +714,12 @@ class EventRouter(object):
                     team = request.team
                     channel = request.channel
                     metadata = request.metadata
+                    url = request.url
                 else:
                     team = j.get("wee_slack_metadata_team")
                     channel = None
                     metadata = {}
+                    url = ""
 
                 if team:
                     if "channel" in j:
@@ -727,6 +729,10 @@ class EventRouter(object):
                         user_id = j["user"]["id"] if type(j["user"]) == dict else j["user"]
                         metadata['user'] = team.users.get(user_id)
 
+                if not j.get("ok", True):
+                    w.prnt("", "callback {} for team={}, channel={}, metadata={}, url={} was not ok: {}".format(
+                        function_name, team, channel, metadata, url, j))
+
                 dbg("running {}".format(function_name))
                 if function_name.startswith("local_") and function_name in self.local_proc:
                     self.local_proc[function_name](j, self, team, channel, metadata)
```

**Comment by wavexx** [comment]
Yup, I can confirm this errors are also present in the slack web client.
Probably the web client does a retry or two automatically, as it does require less attempts compared to wee-slack.

But this patch would be useful to add in the debug also for the future!

**Comment by Mic92** [comment]
Can wee-slack detect somehow if a message was not sent?

**Comment by dmilith** [comment]
Have same issue, not only with threads but all Slack channels

**Comment by trygveaa** [comment]
Now an error is printed to the core buffer if sending the message fails.

**Comment by oxzi** [comment]
Since we are talking about the consequence of the backend failure ITT, I would like to note that even a `slack_timeout` of one second my WeeChat client freezes like all the time. Is there something I can do?

**Comment by krestivo-kdinfotech** [comment]
I am experiencing this too. Can't send any messages. Started happening after Slack announced they had "fixed" their outage today https://status.slack.com/2020-10-05 so I am now dark on slack.

**Comment by krestivo-kdinfotech** [comment]
And, wee are not alone: https://github.com/slackapi/node-slack-sdk/issues/1100

**Comment by trygveaa** [comment]
Don't know why Slack set the status page to fixed before it was fixed, but now it does seem to be fixed, so I'll close this.
