### ISSUE TITLE
Two threads have the same id

### ISSUE THREAD

**Issue by ptixed** [wee-slack/wee-slack#800]
See the title, not much else I can add. Obviously that leads to some other issues. Like when i try to open the thread by id it opens first one and I can open second one only when there is some new activity on it. Are those ids generated by slack or wee-slack?

**Comment by trygveaa** [comment]
The versions are generated by wee-slack, and they should be unique. Which version of wee-slack are you using?

**Comment by ptixed** [comment]
I am using current master version
