### ISSUE TITLE
Long nicknames should be cut to reduce the number of chars

### ISSUE THREAD

**Issue by rludva** [wee-slack/wee-slack#805]
Very long nicknames should be cut to for example to 12 characters max by default. Or a new option for `MAX_NICKNAME_LENGTH` should be introduced to reduce horizontal space.

**Comment by trygveaa** [comment]
Use `weechat.look.prefix_align_max` to limit the nick length in the chat, and `weechat.bar.nicklist.size_max` for the nicklist.
