### ISSUE TITLE
Disable unfurl

### ISSUE THREAD

**Issue by ta** [wee-slack/wee-slack#809]
Hi,

I'm a loving user of wee-slack - thanks for continuing to update and make this software available.

I'd like to know if it is possible to disable unfurling entirely. These are the settings that I can find which are related to furling:

```
  plugins.var.python.slack.unfurl_auto_link_display             string   "url"
  plugins.var.python.slack.unfurl_ignore_alt_text               string   "true"
```

I think I've tried all permutations of the above settings without any luck.

Is there a way to disable unfurling entirely?

**Comment by trygveaa** [comment]
Duplicate of #526?

**Comment by ta** [comment]
Indeed. A search for "furl" in issues turned up empty, so making the issue searchable by the settings keyword is going to be my (first) contribution :-)

I'm closing this and will be following #526 instead, thanks.
