### ISSUE TITLE
Print button url

### ISSUE THREAD

**Issue by lzmartinico** [wee-slack/wee-slack#811]
When displaying a button block, a URL should be printed if present, so that it can be opened in a web browser.

**Comment by trygveaa** [comment]
I [can't see this field documented](https://api.slack.com/legacy/interactive-message-field-guide#action_fields), but if visiting the URL indeed triggers the action, then yes we should print it.

**Comment by lzmartinico** [comment]
This is again related to the Jitsi integration (as in issue #810): the /jitsi command invokes a [button](https://github.com/jitsi/jitsi-slack/blob/880bfa00908be7bdef1f9976b2be99399864ee0c/slack_messages.go#L33) that contains the url for a meeting; so by clicking on the button it triggers the "action" of joining a meeting. This is a pretty straightforward case, but I am not sure if it would apply to other types of buttons.
