### ISSUE TITLE
Cannot open new group DM

### ISSUE THREAD

**Issue by Coffei** [wee-slack/wee-slack#825]
I'm trying to open new group chat with multiple people using `/query` or `/slack talk` and it doesn't always work. I noticed it works when opening a group I already chatted with in the past, but not when creating new combination that I never previously opened.

Opening new chat to single user works fine, even if I never chatted with that person, but the same doesn't work with groups.

**Comment by Coffei** [comment]
After a bit of inspection, this might have something to do with `mpim.open` API being deprecated. The documentation even claims it will stop working in February 2021 (https://api.slack.com/methods/mpim.open). The doc says we should use `conversations.open` instead, which is exactly what is used for DMs to single user.

Is there any reason why the plugin uses different APIs for single and multi user DMs?

I'll try to test the change locally and can submit PR if it works alright.

**Comment by Coffei** [comment]
Hm.. tried removing the if at https://github.com/wee-slack/wee-slack/blob/master/wee_slack.py#L4518 so that `conversations.open` is used but that didn't work too, so not sure what is going on.

**Comment by mandus** [comment]
I am seeing the same issue. I tested changing https://github.com/wee-slack/wee-slack/blob/master/wee_slack.py#L93 to use `conversations.open` and that seems to work now.

**Comment by Coffei** [comment]
That seems to work for 2-people DMs but not for bigger groups, for me at least :-/
