### ISSUE TITLE
The history is empty 

### ISSUE THREAD

**Issue by PoisonousJohn** [wee-slack/wee-slack#827]
Suddenly without an update, all slack buffers became empty when I open them.
After you open the buffer, and someone sends you a message, it gets updated.
So it seems the problem is in history.

**Comment by trygveaa** [comment]
You need to upgrade to version 2.7.0 of wee-slack. The API that earlier versions of wee-slack used has been shut down.

**Comment by PoisonousJohn** [comment]
Thanks, will do
