### ISSUE TITLE
Can't tab complete most (but not all) nicks anymore

### ISSUE THREAD

**Issue by nuxi** [wee-slack/wee-slack#829]
Like everyone, I recently updated wee-slack in order for it to keep working. After I did that I stopped being able to tab-complete some (but not all) of my coworkers names. There doesn't seem to be any pattern to who I can or cannot tab complete. The list of people in any given channel is also missing many names, even if someone has spoken in the channel recently. I'm seeing it across multiple workspaces on multiple computers. Other people I know running wee-slack are also seeing the issue.

In at least one case I can tab complete someone's nickname in one channel but not another channel on the same slack workspace.

I'm currently running revision bf9ef6f which is the tip of the repository, so I have the change in 86b2f0d and it didn't help. I think the last revision I was on that worked was 8bd734c. I'm running weechat 3.0.1 from Debian Sid.

**Comment by trygveaa** [comment]
I pushed a commit that hopefully fixes this. Please check and comment if it's still an issue.

**Comment by trygveaa** [comment]
The previous commit didn't fix all cases, so i pushed a new fix. It should work now.
