### ISSUE TITLE
[BUG] Chats with more than one members are lost

### ISSUE THREAD

**Issue by hissssst** [wee-slack/wee-slack#833]

**Comment by trygveaa** [comment]
Please provide more details.

Also, check if #825 is the problem you're experiencing.

**Comment by hissssst** [comment]
### Overview
subj

### Desired behaviour

Group chats are displayed in chat buffer and notifications about new messages and mentions are received

### Actual behaviour

If I am invited to the group chat while wee-slack is closed, the chat is not displayed in the chat list buffer. But I can see the event on the wee-slack buffer that the chat was created. However, I do not receive notifications for messages or mentions from this chat (with `notify-send` plugin).

However, when I send a message from official slack client, group chat appears in chat list buffer and works as desired

### Enviroment
```
weechat 3.1
wee-slack defd8a0e1a46b786bd3880632477e742a4d6d56c
```

**Comment by hissssst** [comment]
@trygveaa ping
What do you think? Can this issue be fixed?
By the way, I've missed chat with my boss and I had a lot of trouble because of it :/

**Comment by trygveaa** [comment]
@hissssst: I'm sorry you missed chats, but since I just develop wee-slack on my spare time and provide it for free, I can't give any guarantees. That said, the issue should be fixed now.

**Comment by hissssst** [comment]
@trygveaa I totally understand that. Thank you for this awesome programm, anyway)
I just thought that sharing this story will help to draw your attention to this issue

By the way, this issue is fixed now
