### ISSUE TITLE
Contributing docs don't say how to format the source

### ISSUE THREAD

**Issue by devkev** [wee-slack/wee-slack#842]
I'm not familiar with Python ecosystem things like flake/black/pipenv, so it'd be nice if docs/contributing.md told me exactly which commands I need to install and run before sending a PR.  I tried to use pipenv, but it was very difficult to install and I couldn't get it working.

**Comment by trygveaa** [comment]
I added some documentation for it now. Pipenv will install all the tools for you, but you can also install the tools separately without using pipenv.

**Comment by devkev** [comment]
Great, thanks!
