### ISSUE TITLE
Session tokens no longer working

### ISSUE THREAD

**Issue by frh** [wee-slack/wee-slack#844]
[<img alt="Issuehunt badges" src="https://img.shields.io/badge/IssueHunt-%24432%20Funded-%2300A156.svg" />](https://issuehunt.io/r/wee-slack/wee-slack/issues/844)

This morning my session token expired. I logged in to my browser and got a new one, but wee-slack can't log in with it:
`ERROR: Failed connecting to Slack with token xoxc-...: invalid_auth`

I've been using session tokens for several months and getting new ones every time they expired, and this is the first time I've had any issues.

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $432.00)

- [<img src='https://avatars.githubusercontent.com/u/687943?v=4' alt='yardenac' width=24 height=24> yardenac](https://issuehunt.io/u/yardenac) ($40.00)
- [<img src='https://avatars.githubusercontent.com/u/79942?v=4' alt='opensourcealchemist' width=24 height=24> opensourcealchemist](https://issuehunt.io/u/opensourcealchemist) ($100.00)
- $292.00 have been anonymously funded.
### Submitted pull Requests
- [#857 Support new session tokens (xoxc tokens)](https://issuehunt.io/r/wee-slack/wee-slack/pull/857)
---

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/wee-slack/wee-slack/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
</details>

**Comment by trygveaa** [comment]
So apparently, the customize page now has a token starting with `xoxc` instead of `xoxs`. These are two different types of tokens. After they changed to `xoxc` in the main app interface a long time ago, I feared they would change it on the customize page at some point too :(

Tokens starting with `xoxc` can't currently be used by wee-slack. I'm not sure how to get them to work, or if it is even possible for us to use them, but I guess I'll have to look into it.

**Comment by b123400** [comment]
I tried to look at the request from the Slack web interface, and attempted to create a minimum request that connects to a websocket. It looked like this:

URL: `wss://wss-primary.slack.com/?token=xoxc-xxxxxx&gateway_server=<workspace_id>`
Cookie: `d=ynd9q%2FWq...`

It would fail if any of the `token`, `gateway_server` or `d` in Cookie is missing.
The `d` cookie's expiry is 10 years.

**Comment by WA9ACE** [comment]
https://cancel.fm/ripcord has a working authentication flow so it should be possible to use that cookie in conjunction with the xoxc token to authenticate again. It'll probably require a PR to work with the new flow.

**Comment by DmitrySandalov** [comment]
Fine with just `d` cookie?
[emacs-slack/issues/553](https://github.com/yuya373/emacs-slack/issues/553)
[emacs-slack/pull/552/commits](https://github.com/yuya373/emacs-slack/pull/552/commits)

Slack's position on `xoxc` tokens:
https://stackoverflow.com/a/62777057

**Comment by trygveaa** [comment]
I tested a bit, and saw that the `rtm.start` API can't be used with xoxc-tokens. So we need to rewrite to use other API endpoints to get the data we use from `rtm.start`. Currently `rtm.start` is used to populate much of the initial info, i.e. the profile, users, bots, user groups, preferences (muted channels and highlight words) and list of channels and direct messages. So this might be a rather large task, which requires calling multiple other endpoints. The biggest issue is probably that wee-slack currently expects to be aware of all the users and channels on the team (which `rtm.start` does return), while the new API endpoints only return a limited amount and are paginated to get more.

After that is done, we can add support for specifying the `d` cookie in addition to the token, which should be pretty easy. Though the current `slack_api_token` is already a bit inconvenient, and would be even worse with a cookie as well, so we should probably change the config to have a section per team, like in the irc config.

**Comment by dustymabe** [comment]
Hi all.. Any workarounds we can use for now even if it's complicated?

**Comment by megalithic** [comment]
> I'd be happy to chip in on a bounty for this one. I don't have the time nor knowledge of the codebase nor slack protocol to contribute directly, but I'll happily support anyone who does. Anyone with me? Using slack without wee-slack is severely slowing me down @ dayjob.

Count me in as contributing to a bounty for this!

**Comment by bougyman** [comment]
> > I'd be happy to chip in on a bounty for this one. I don't have the time nor knowledge of the codebase nor slack protocol to contribute directly, but I'll happily support anyone who does. Anyone with me? Using slack without wee-slack is severely slowing me down @ dayjob.
> 
> Count me in as contributing to a bounty for this!

@megalithic can you set the project up on IssueHunt or a similar site so I can get this ball rolling?

**Comment by Enqueued** [comment]
Is there a current work around with the Oauth token instead of the session token? 
I would really like to set up IRC slack integration so I can monitor slack on my pinephone.

**Comment by smaslennikov** [comment]
To get proper read status on threads, I moved to session tokens and just found that it's a broken feature. While that's the case, it's probably best to remove the session tokens from documentation to avoid new users running into the issue.

**Comment by bougyman** [comment]
Any word on this?

**Comment by bruno-** [comment]
Is there a funding goal we need to reach to get this feature going? Thanks
I love wee-slack!

**Comment by trygveaa** [comment]
Support for this has now been added in PR #857 (not merged yet). Please test it out and report any issues.

**Comment by JackTheMico** [comment]
@trygveaa I have tested #857, it's partly working. All the channels and messages with multi users are able to load, but messages with a single user are not loaded.

**Comment by JackTheMico** [comment]
> @trygveaa I have tested #857, it's partly working. All the channels and messages with multi users are able to load, but messages with a single user are not loaded. Is there anything I can do to help you debug this?

@trygveaa It's totally working for both channels and private chat with a single user today.

**Comment by colin-arnott-xero** [comment]
Channels work great and I see the same behaviour around dms (they disappear on reload). 1:1 dms come back with `/query` and `/slack talk` which is annoying, but not the end of the world, however while I can create group dms and they show up when others create them, they too are lost on reload, and I cannot reopen them with `/query` or `/slack talk`.

**Comment by trygveaa** [comment]
@JackTheMico, @colin-arnott-xero: Unfortunately the API doesn't return if a DM or MPDM is open anymore, which caused no DMs and all MPDMs to open on start. It's now changed to only open the DMs and MPDMs with unread messages.

@colin-arnott-xero: The bug with not being able to open MPDMs is now fixed.

**Comment by trygveaa** [comment]
> @JackTheMico, @colin-arnott-xero: Unfortunately the API doesn't return if a DM or MPDM is open anymore, which caused no DMs and all MPDMs to open on start. It's now changed to only open the DMs and MPDMs with unread messages.

As I posted in the PR, this wasn't correct. The info just isn't available in the API to list conversations, but the API for info about a conversation has it. So it's been fixed, the version in master now opens the DMs/MPDMs which are open in the web client. This should also match the ones you had open in weechat the last time you ran it, unless of course you opened/closed anyone in the web/mobile client in the meantime.
