### ISSUE TITLE
Autoload instructions should mention alternate path for XDG directories

### ISSUE THREAD

**Issue by craSH** [wee-slack/wee-slack#847]
In the README section for `2. Download wee_slack.py to ~/.weechat/python`, the title and body should mention that if the user's weechat installation is using XDG directories, the destination directory would be `/home/crash/.local/share/weechat/python` (and `/home/crash/.local/share/weechat/python/autoload`)

Reference from Weechat's documentation on these paths: https://weechat.org/files/doc/stable/weechat_user.en.html#xdg_directories

XDG paths are used in current Arch linux packages for WeeChat (3.2-1)

**Comment by mhite** [comment]
Ran into this issue on Ubuntu 18.04.

```
$  lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.6 LTS
Release:        18.04
Codename:       bionic
```

**Comment by el-iot** [comment]
I encountered this issue as well: would be great if this information was available in the README! Thanks for the fix!

**Comment by hut8** [comment]
Also happens if you install from their Debian/Ubuntu repos on seemingly all versions (including Focal)
