### ISSUE TITLE
/slack away

### ISSUE THREAD

**Issue by dyipon** [wee-slack/wee-slack#856]
Hi,

how can I make "/slack away" command to work in a multiple team enviroment? If I use this command, it sets the away status on actual team only.

**Comment by trygveaa** [comment]
You can use the standard `/away` command to set yourself away in all teams. I.e. `/away -all away` to set yourself away, and `/away -all` to remove the away status. Note that this will also set/remove away in your IRC servers, and that the message (the word(s) after -all) is only used for IRC, not Slack, except to determine if you're setting or removing the away status.

**Comment by dyipon** [comment]
oh sorry, thanks for the answer!
