### ISSUE TITLE
edited messages are no longer updating in-place without reloading the script

### ISSUE THREAD

**Issue by sudoforge** [wee-slack/wee-slack#861]
Historically, edited messages would be updated in-place and `(edited)` would appear at EOL. I am no longer experiencing this; instead, the original message appears unmodified until the script is reloaded via `/python reload slack`.

I'd be happy to provide debug logs; let me know what is needed.

**Comment by trygveaa** [comment]
Sorry for the late reply here. I have not experienced this, I see edits. Do you still have the issue? Is it consistently reproducable?

Can you try to enable `plugins.var.python.slack.record_events` and see if you get any files named `<number>.<number>-message.json` in `/tmp/weeslack-debug/<team>/websocket` containing `"subtype": "message_changed"`?

Or alternatively, add a print in the `subprocess_message_changed` function and check if it get's called when a message is edited.

**Comment by sudoforge** [comment]
I am no longer able to reproduce this. :man_shrugging:
