### ISSUE TITLE
'getting channel history...' lasting forever

### ISSUE THREAD

**Issue by Rahmerh** [wee-slack/wee-slack#867]
I have weechat 3.6 installed together with the latest of wee-slack.

I've installed this on the Macbook pro, with M1 max chip, monterey version 12.5.1.

When I open any chat, I get the 'getting channel history...' message which doesn't go away. Debug logs don't show my anything interesting, just this message:

`Sent {"type": "typing", "channel": "<channel>", "id": 7}...` 

I can sent the complete logs if needed.

Sending and receiving messages is completely fine, it's just getting the message history which doesn't seem to work.

**Comment by trygveaa** [comment]
For reference, we talked on IRC. It turned out to be the same issue as https://github.com/weechat/weechat/issues/1723. The workaround to set the environment variable `OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES` before starting weechat worked.
