### ISSUE TITLE
Is there a way to capture the thread ID for using in a custom command?

### ISSUE THREAD

**Issue by lifepillar** [wee-slack/wee-slack#872]
Is it possible to customize right-clicking on a thread so that, instead of pasting the thread id into the input line, the thread is opened at once? Ideally, I would like to right-click on a thread and have it open in a split window.

**Edit:** essentially, I'd like to use the thread ID in my own key bindings.

**Comment by DonnieWest** [comment]
Not sure about right clicking to open, but this is more of a weechat question than wee-slack

Here's their documentation on modifying windows and buffers, which would allow you to open a split and navigate through those https://weechat.org/files/doc/stable/weechat_quickstart.en.html#buffer_window

**Comment by lifepillar** [comment]
Thanks for the lightning reply! My question is more about how one captures the thread id, so that it can be used in a key binding or in a trigger.

**Comment by lifepillar** [comment]
I have changed the title and update the text to better reflect the intent of my question.

**Comment by trygveaa** [comment]
It's not possible to use the thread id directly in your own keybindings unfortunately. However, it is possible to do the specific things you're asking for.

To open the thread by right clicking it:
```
/key bindctxt mouse @chat(python.*):button2 hsignal:slack_cursor_thread
```

To open it in a split window:
```
/key bindctxt mouse @chat(python.*):button2 /window splith; hsignal:slack_cursor_thread
```

You can see the available actions you can bind to here: https://github.com/wee-slack/wee-slack#cursor-and-mouse-mode

**Comment by lifepillar** [comment]
Thank you! That is exactly what I wanted!
