### ISSUE TITLE
add thread "also send to <channel>" syntax

### ISSUE THREAD

**Issue by colin-arnott-xero** [wee-slack/wee-slack#878]
currently when messaging a thread `/reply` (and the default message input) only accepts a message, but in the slack ui, there is a boolean for "also send to <channel>". it is possible to see these messages, they use the `[+ 000] messsage`syntax, but I do not know how to create one using wee-slack.

spitballing a ux for this one, we can steal the existing read syntax:
```irc
/reply + 000 my message text
/reply + $000 my message text
```

**Comment by trygveaa** [comment]
This is supported with the `-alsochannel` option to `/reply`. See `/help reply`.
