### ISSUE TITLE
an info to get the text of a message using a message id

### ISSUE THREAD

**Issue by pascalpoitras** [wee-slack/wee-slack#889]
Hi,

As discussed with @trygveaa I would like to have an info to retreive the content of a message

for example

`/eval -n ${info:slack_message_id,<id>}`

it would return the text of this message id. 

it may be useful to also have an info slack_message where you give a count instead of a message_id

**Comment by trygveaa** [comment]
Nice idea. Try the `info-slack-message` branch I pushed now.

I named it just `slack_message` instead of `slack_message_id`, and you can give it either a message id or a count, both will work.

**Comment by trygveaa** [comment]
Might want to support providing the channel as an argument too, rather than always using the current buffer as I did now.

**Comment by trygveaa** [comment]
Also, it returns the full rendered message, which includes reactions, prefix/suffix for thread messages/parents and `(edited)` if the message is edited. Not sure if this is wanted, or if it should return just the raw message.

**Comment by pascalpoitras** [comment]
this is awesome! good works
I think it's best this way, more information is more useful, anyway the syntax is constant so we could get only the part we want easily
