### ISSUE TITLE
issue with websocket

### ISSUE THREAD

**Issue by caywin25** [wee-slack/wee-slack#892]
Hello

I am under archlinux and since a recent update of python-websocket-client I can no longer use wee-slack, I have this error message : 

```
python: loading script "/home/test/.weechat/python/wee_slack.py"
python: stdout/stderr (?): Traceback (most recent call last):
python: stdout/stderr (?):   File "/home/test/.weechat/python/wee_slack.py", line 34, in <module>
python: stdout/stderr (?):     from websocket import (  # noqa: E402
python: stdout/stderr (?): ModuleNotFoundError: No module named 'websocket'
=!= python: unable to parse file "/home/test/.weechat/python/wee_slack.py"
```
python3 version : 3.11

Can you help me please ?
Thanks

**Comment by trygveaa** [comment]
It still works for me with an up to date Arch system. Can you post the output of `pacman -Qi python-websocket-client`?

**Comment by caywin25** [comment]
Hello 

```
$  pacman -Qi python-websocket-client
Name            : python-websocket-client
Version         : 1.6.0-1
Description     : WebSocket client library for Python
Architecture    : any
URL             : https://github.com/websocket-client/websocket-client
Licenses        : LGPL
Groups          : None
Provides        : None
Depends On      : python
Optional Deps   : None
Required By     : None
Optional For    : None
Conflicts With  : None
Replaces        : None
Installed Size  : 664.20 KiB
Packager        : Brett Cornwall <ainola@archlinux.org>
Build Date      : Sat 17 Jun 2023 08:20:49 PM CEST
Install Date    : Thu 22 Jun 2023 07:39:06 AM CEST
Install Reason  : Explicitly installed
Install Script  : No
Validated By    : SHA-256 Sum
```
Thans

**Comment by trygveaa** [comment]
Okay, that's the same version as I have. Do you have WeeChat installed from the Arch repo, or from somewhere else? Can you run this in WeeChat and post the output? `/python eval import sys; print(sys.path)`

**Comment by caywin25** [comment]
Hello

I tested both installations:

- arch repo install
- install via curl.

The command output:
```
['/home/test/.weechat/python', '/usr/share/weechat/python', '', '/usr/lib/python311.zip', '/usr/lib/python3.11', '/usr/lib/python3.11/lib-dynload', '/home/test/lib/python3.11/site-packages']
```
Thanks

**Comment by trygveaa** [comment]
Hm, there is something weird with your Python or WeeChat installation or your environment. `/usr/lib/python3.11/site-packages` (where `python-websocket-client` is installed) is normally in `sys.path`, but you have `/home/test/lib/python3.11/site-packages` there instead. Do you have any Python venv loaded? Or have you set any environment variables relating to Python?

**Comment by caywin25** [comment]
Yes it is possible as I do a lot of testing with my computer.

Is there a way to put /usr/lib/python3.11/site-packages back in the python sys.path?
Thanks

**Comment by caywin25** [comment]
I tried many solutions to restore:
/usr/lib/python3.11/site-packages in sys.path but without success :(

**Comment by trygveaa** [comment]
> Is there a way to put /usr/lib/python3.11/site-packages back in the python sys.path?

Not sure (other than editing the script to hacking it in), it probably depends on why it's gone. Can you run these commands and see what they print?

```
which python
env | grep 'PY\|ENV'
```

**Comment by caywin25** [comment]
Hello 

Victory \o/
Issue is solved !!!

for some unknown reason the python3 binary was pointing to: /home/test/bin/python3

I deleted this path and now the binary points to /bin/python3 and I have no more worries :)

Thanks a lot for your help.
Good day

**Comment by trygveaa** [comment]
Great that you got it solved!
