### ISSUE TITLE
Some messages with images won't show

### ISSUE THREAD

**Issue by antoyo-light** [wee-slack/wee-slack#893]
Hi.
Since yesterday, I started seeing messages where the text is "This message contains interactive elements." instead of the real message.
This seems to happen when there's an image attached to it.
Thanks to fix this issue.

**Comment by cwegener** [comment]
For me this started happening three days ago (3 July 2023)
Any received message that contains both text + images will say "This message contains interactive elements." and only the image URL will be displayed, and the original text from the send is no longer shown.

**Comment by trygveaa** [comment]
I've also started getting this in the last days. Looks like we now have to use the rich_text block (which is undocumented) to get the text of these messages. I'll look into supporting it.

**Comment by trygveaa** [comment]
It looks like this isn't happening anymore for new messages, so it may have been an unintentional change. But I had already done most of the fix when I saw that, and the fix also fixes some other things so I kept it. I also see that messages sent in these three days still show up with that text, it's only new messages it's fixed for.

**Comment by cwegener** [comment]
Yes. I can confirm that the issues has just disappeared. Very curious.

The `rich_text` block support sounds really interesting. I'll definitely will test it out myself. Some of the bugs it fixes sound like bugs that I've certainly encountered myself here and there, but that were low priority enough to ignore.
