### ISSUE TITLE
Change color of bot nicks 

### ISSUE THREAD

**Issue by edganiukov** [wee-slack/wee-slack#895]
Since some recent changes bot's nicks are now have black color and in the terminals with dark background almost not visible.
Is there  a way to configure bot nick's color?

**Comment by edganiukov** [comment]
Hi @trygveaa,
Indeed bots were colored "offline". Thanks!

**Comment by trygveaa** [comment]
This has been fixed in v2.10.0 (commit 5ce50c2). I reverted the change that caused this issue. I might re-introduce the change later, but then I'll make sure to do it in a way that doesn't cause this issue.
