### ISSUE TITLE
updates in other channels not loaded

### ISSUE THREAD

**Issue by yazgoo** [wee-slack/wee-slack#903]
Since I upgraded to the version with https://github.com/wee-slack/wee-slack/issues/901

I don't receive updates for other channels / threads.
I have to go to the buffer to receive the updates.

**Comment by trygveaa** [comment]
Can you give some more details here? What do you mean that you don't receive updates? Are you saying that the buffers are not added to the hotlist, but when you switch to the buffer, the messages are there?

**Comment by yazgoo** [comment]
> Are you saying that the buffers are not added to the hotlist, but when you switch to the buffer, the messages are there?

Yes, correct

**Comment by yazgoo** [comment]
Sorry, PEBKAC (wrong configuration)

**Comment by trygveaa** [comment]
What was the wrong configuration? (In case others run into the same issue)

**Comment by yazgoo** [comment]
I just set
```
buflist.hidden = on
```
:facepalm:
