### ISSUE TITLE
Angle brackets within code blocks get removed

### ISSUE THREAD

**Issue by sesse** [wee-slack/wee-slack#908]
It seems there is some odd HTML stripping at work within code blocks (triple backticks). The simplest way to reproduce is to send a message to yourself containing

```
```<a>```
```
It comes out as

```
12:40:07 Sesse | ```
12:40:07       | a
12:40:07       | ```
```

 This is rather cumbersome when trying to discuss the subtleties of HTML :-)

``<a`` or ``a>`` comes out just fine, so I guess there's some stripping at work; the web client displays the tags verbatim. It also works just fine if I'm using double backticks only.

**Comment by trygveaa** [comment]
Ah, this is caused by the rendering changes I did a little while ago (commit 74da3034, to fix #893 among others). I did a related fix in commit 6478c141, but apparently I only considered normal text and inline code there, not code blocks. It should be fixed now.
