### ISSUE TITLE
threads are still marked as unread while starting

### ISSUE THREAD

**Issue by stacyharper** [wee-slack/wee-slack#927]
Hey there,

I got this setting, maybe it cause this? `auto_open_threads: true`

When loading, every thread are open back (which is what I want), but all threads are marked as unread and are in the weechat hotlist.

Known issue?

Also, thanks for this project!

**Comment by trygveaa** [comment]
Are you using a session token (starts with `xoxc-`) or an oauth token (starts with `xoxp-`)?

Which version of wee-slack are you using?

**Comment by stacyharper** [comment]
a `xoxc-` token, I'm using master iirc (I curled it)

**Comment by trygveaa** [comment]
Have you switched to these thread buffers to mark them as read? The way `auto_open_threads` works is that it opens every unread thread and marks it as unread.

**Comment by stacyharper** [comment]
Yes I did so, and switched out of them afterward too

**Comment by stacyharper** [comment]
I was using an oauth token, and not a session token. I think, as mentioned in the README known issue part, that was the root of my problem.
