### ISSUE TITLE
Fail to start correctly today

### ISSUE THREAD

**Issue by stacyharper** [wee-slack/wee-slack#930]
Hello,

Starting from today, the buffers does not get loaded while loading the module. Here the log I have when enable debug:

```
09:02 python: stdout/stderr (slack): Traceback (most recent call last):
09:02 python: stdout/stderr (slack):   File "/home/stacy/.local/share/weechat/python/wee_slack.py", line 895, in handle_next
09:02 python: stdout/stderr (slack):     EVENTROUTER.handle_next()
09:02 python: stdout/stderr (slack):   File "/home/stacy/.local/share/weechat/python/wee_slack.py", line 879, in handle_next
09:02 python: stdout/stderr (slack):     callback(j, self, team, channel, metadata)
09:02 python: stdout/stderr (slack):   File "/home/stacy/.local/share/weechat/python/wee_slack.py", line 7365, in handle_rtmconnect
09:02 python: stdout/stderr (slack):     highlight_words=initial_data["prefs"]["highlight_words"],
09:02 python: stdout/stderr (slack):                     ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
09:02 python: stdout/stderr (slack): KeyError: 'highlight_words'
```

A change in Slack apis?

**Comment by jfriesse** [comment]
Also hit by this issue. Simply removing/commenting `highlight_words=initial_data["prefs"]["highlight_words"]` helps as a workaround.

**Comment by illambias** [comment]
Also same issue here, commenting the line was a workaround for today's work day, but I'd like to understand what caused the issue.
Happens with weechat version 4.3.1 on debian sid.

**Comment by trygveaa** [comment]
This is caused by a change in the API (this functionality is using a non-documented API, so it's more prone to changes without notice). I updated the code to match the new API now, and made it safer so if it changes again a warning will be printed instead of it crashing.

**Comment by illambias** [comment]
Thanks ! And indeed, what a quick fix !

**Comment by flokli** [comment]
@trygveaa any chance you can push a release containing this fix? That's probably the easiest way for this fix to land in downstream distributions, other than them manually cherry-picking commits…

**Comment by trygveaa** [comment]
@flokli: Sorry for not making a release of this yet! I made one now.

**Comment by flokli** [comment]
Ok, I did a bump in nixpkgs in https://github.com/NixOS/nixpkgs/pull/347944.
