### ISSUE TITLE
All emojis provided as unicode should be supported in reactions

### ISSUE THREAD

**Issue by zaeph** [wee-slack/wee-slack#951]
Hi,

First of all, thanks for the great work on wee-slack.  It’s a great tool that makes Slack tolerable in my professional life.

Onto the issue:

## SitRep
- Reaction emojis can be added in one of two ways: via actual unicode (e.g. `🙂`), or via their unicode name flanked by colons (e.g. `:slightly_smiling_face:`)
- Some emojis are supported in the latter mode, but not in the former.
  - `+:saluting_face:` produces a reaction with the emoji `🫡`.
  - `+🫡` raises the following error: `Error: Couldn't add reaction 🫡: invalid_name`
- I’ve had a cursory look at the Python code, and whilst the C encoding and the unicode name are present in weemoji.json, I don’t think the mapping is happening here.

## Next steps
- I’m happy to fix it myself and PR if you point me in the right direction.

**Comment by trygveaa** [comment]
Sending `+🫡` to add a reaction works fine for me. Are you sure that the weemoji.json file that wee-slack is reading contains this emoji? (e.g. if you copied over the weemoji.json file to the weechat dir before this emoji was added, and is a different one than the one you see contains the emoji)

When we add a reaction the Slack API requires us to use the name, it won't accept the emoji. So we have to convert the emoji into the name. This is done by looking up the code in the weemoji.json file.

**Comment by zaeph** [comment]
Hi again,

Indeed, it works when you update the actual weemoji.json.  I’d misplaced the updated file under `.weechat/python/` rather than `.weechat/`.  Thanks.

Closing.
